### ISSUE TITLE
max_allowed_packet and serialized columns

### ISSUE THREAD

**Issue by ptolts** [zdennis/activerecord-import#100]
My apologies, looks like my single column was over 10mB. 

Maybe ar-import should throw an exception if an insert is over the max_allowed_packet?

*\* Edited **

I won't have an opportunity to prove this, but I believe theres a bug in calculating the size of each insert if one of the columns is serialized by Rails. 

Background:

I'm saving many HTML documents into a database. They are stored per language in a hash, which I serialize so I can access them easily later. As you can imagine, this involves a ton of escape characters. I did some greping in the log files, it looks like a 10mB insert ballooned into a 30 mB one.

More often than not there's probably no issue, but if whats being serialized happens to need a ton of escapes, its possible it'll go over the max_allowed_packet.

I'd love to work on this for a bit, but I'm under a deadline at the moment.

Thanks for the great gem.

**Comment by jkowens** [comment]
@ptolts I know this is a really old issue, but do you remember the behavior that was displayed when max_allowed_packet size was exceeded?

 I'm trying to determine if no inserts were performed or if inserts were attempted, but MySQL returned errors?

**Comment by ptolts** [comment]
I haven't been able to reproduce this. I may have been barking up the wrong tree all those years ago.

**Comment by ptolts** [comment]
I vaguely remember it double escaping the final sql string. This could have been fixed in ActiveRecord itself?

**Comment by jkowens** [comment]
Hm yeah, it's hard to say. There definitely have been many updates/improvements to AR since the v3 days. I also think @zdennis tweaked the the code that splits up the value sets based on max_allowed_packet shortly after this issue was reported. Is it ok if I close this issue for now and we can address later if need be?

**Comment by ptolts** [comment]
I think it's safe to close, thanks!
