### ISSUE TITLE
Support join table inserts

### ISSUE THREAD

**Issue by christopherchiu** [zdennis/activerecord-import#101]
I don't mind making a second call to the library but since the import method is tied to a specific model there's no model to make the call to. 

Example: If I have store and customers, there's no way for me to insert into stores_customers even if I have both ids. 

My proposed solution would be to call ActiveRecord::Base import some_columns, some_rows, table_name: :stores_customers.

**Comment by philipgiuliani** [comment]
I would need the same currently. What i did was changing `has_and_belongs_to_many` to a `has_many :abc, trough: :abc`

**Comment by dcdieci** [comment]
same here. support for habtm would be appreciated.

**Comment by akanshmurthy** [comment]
+1

Yes, please!

**Comment by jkowens** [comment]
For future reference, another option is to create a model for the join table. So in the example above the model would be:

```
class StoresCustomer < ActiveRecord::Base
end
```

With that model you could then import the necessary records.

**Comment by KyleRAnderson** [comment]
What actually is the best way of accomplishing this without support for it in this gem? I know there's [`ActiveRecord::Persistence::ClassMethods#insert_all`](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all) but that skips all callbacks and validations.
