### ISSUE TITLE
id is returning nil

### ISSUE THREAD

**Issue by nicdal** [zdennis/activerecord-import#113]
Trying to insert into a table without any primary key (MySQL Archive table).

Search.new({id: 1234}).id_before_type_cast => nil

Search.new({id: 1234}).read_attribute_before_type_cast('id') => 1234

The first option is used in import.rb:188. But fails to import my searches because field 'id' is returning nil. After changing line 188 to model.read_attribute_before_type_cast(name) it works.

**Comment by anthonator** [comment]
I know this is old but I'm seeing this issue as well on 0.15.0.

**Comment by jkowens** [comment]
@anthonator it looks like the suggested change has been implemented. Can you provide some details about the models you are importing? Is it a table without a primary key as above?

**Comment by anthonator** [comment]
I believe this is because I was using UUID's as primary keys. I believe you already fixed this.

**Comment by jkowens** [comment]
Cool I was hoping that was the case 👍🏻
