### ISSUE TITLE
#import and counter_cache

### ISSUE THREAD

**Issue by simo2409** [zdennis/activerecord-import#128]
It seems that if I import something which has a counter_cache setup, the import operation didn't update counter_cache field.
Probably it's because it doesn't perform inserts via active_record but it should be warned in readme

**Comment by lmatiolis** [comment]
Just arrived at this issue looking for this info about counter_cache.

What i see on the proposed README change is good! :+1:

**Comment by jkowens** [comment]
I added an entry to the wiki about this, so I think that is enough to close for now.
