### ISSUE TITLE
Rails 4.1 enums are not working

### ISSUE THREAD

**Issue by thomas-mcdonald** [zdennis/activerecord-import#139]
From experimenting with my importer today it appears that enum fields are being inserted as `0` regardless of the string/integer value assigned to them.

**Comment by zamirkhan** [comment]
That fix works for me - thanks!

**Comment by iamWh1sp3r** [comment]
This is a must have

**Comment by sebastianvera** [comment]
:+1:

**Comment by zdennis** [comment]
I'm all for this, we need an associated test though, not just the implementation. If someone can update #164 with a test, this will get pulled in much faster.

**Comment by dbenjamin57** [comment]
+1, we wasted half a day until googling to find there's an issue with enums. Makes this gem un-useable

**Comment by sinelaw** [comment]
+1 isn't this bug somewhat...critical?

**Comment by arashm** [comment]
+1
Made a lot of changes on my code to use this, and then this bug...

**Comment by vmendoza** [comment]
please fix this.

**Comment by zdennis** [comment]
@arashm deserves all the credit for fixing this. A 0.10.0 gem has been pushed to ruby gems incorporating his fix.
