### ISSUE TITLE
{ClassName}.import causes datetime fields to be validated incorrectly due to {field_name}_before_type_cast

### ISSUE THREAD

**Issue by trandoanhung1991** [zdennis/activerecord-import#140]
Currently I'm using AR-import 0.5.0 in my project and I encountered this problem.

The class I'm using to import has a datetime field. When I call import, due to the way the attributes are taken out using _before_type_cast, the UTC time is taken out. However, when assigning the attributes, line 257, ```model.send("#{k}=", v)``` is used, which causes the UTC time to be parsed once again from the timezone into UTC.

This messes up a validation where I check the datetime field for duplication, since the timestamp is potentially non-existent.

A possible fix is to assign the attributes directly by using ```model[k] = v```, though I'm not sure if it'll break other things.

**Comment by jkowens** [comment]
@zdennis this can be closed because #259 has been merged.

**Comment by zdennis** [comment]
:thumbsup:
