### ISSUE TITLE
How would you handle something like this?

### ISSUE THREAD

**Issue by homerlex** [zdennis/activerecord-import#146]
I understand that you cannot handle doing inserts for has_many associations (and I understand why).  So is there any way to handle something like this?

Model Posts has_many tags
The data we are importing is coming from a csv file containing info about the each post as well as the tags for each. Something like this:
```
post_text, post_date, tags
my text, 2014-06-17, tag1:tag2:tag3
```
I can easily convert this data into a Post object that has 3 Tag object.  Is there any possible way for me to bulk create the post objects and then the tag objects?  I don't see how since we can get the ids of newly created post records.

**Comment by jkowens** [comment]
@zdennis this was resolved by the `:recursive` option for Posgres. There is another issue open for implementing it for SQLite and MySQL.
