### ISSUE TITLE
Validation Required if there are Uniqueness Constraints?

### ISSUE THREAD

**Issue by homerlex** [zdennis/activerecord-import#147]
I understand that imports are faster when skipping validation.  However, if I skip validation and there is a uniqueness constraint violation it blows up with a PG::UniqueViolation exception.

It would be nice if that were handled gracefully and report as a failure in the import results object.  So, for now I am going to be required to force validation?

**Comment by smikkelsen** [comment]
I am having the same issue with mysql. When importing, I get the duplicate key violation. There is an option to update duplicate keys, but it is not working for me. No matter what I try, it still fails.

**Comment by jkowens** [comment]
@homerlex with PG 9.5+ now supporting UPSERT functionality, activerecord-import 0.12.0+ provides the options `:on_duplicate_key_update` and  `on_duplicate_key_ignore: true`. Setting one of these options will allow the insert to complete without error. 

@smikkelsen you are correct, you should be able to use the `:on_duplicate_key_update` or `:ignore` options for MySQL to allow the insert to proceed without error. If you continue to have issues with that, I would recommend opening a new issue specifically for that with details about how to reproduce.

@zdennis I think this issue can be closed.
