### ISSUE TITLE
Problem with Postgres Sequence

### ISSUE THREAD

**Issue by homerlex** [zdennis/activerecord-import#148]
Our tables are configure to default the value of the primary key column like this:
nextval('activity_item_tags_id_seq'::regclass).

So we don't even want activerecord-import to try inserting the value for the primary key.  Right now it tries to look up the sequence for the primary key and it comes up blank and the whole thing blows up in the postgresql_adapter.

For now I just hacked up the activerecord-import code and hardcoded it to ignore the primary key column.  Is there some built in way to do this that I am missing?

**Comment by nelsonjchen** [comment]
Just throwing this out there, we have an app that also used to be on a MySQL database but then got moved to a PG DB. Thanks for posting your fix!
