### ISSUE TITLE
Name clash with the `elasticsearch` gem

### ISSUE THREAD

**Issue by aurels** [zdennis/activerecord-import#149]
Hi,

I'm trying to use both `activerecord-import` and `elastiquesearch-rails` gems. But both of them seems to define `ActiveRecord::Base#import` so it clashes when I do an indexation with ElasticSearch.

Do you think there is a solution to that ? Renaming one of the methods at runtime ?

Thanks

**Comment by amal007** [comment]
@aurels  perfect  :+1:  :+1:

**Comment by strukturedkaos** [comment]
Worked great @aurels - Thank you.

**Comment by snehaldpatel1992** [comment]
I am trying to use elastic search and active-record import on rails model class. I can insert multiple records in database but can update indexing in elastic-search. Can anyone suggest me where I am going wrong.

File : Customer.rb
require 'elasticsearch/model'
class Customer < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
end
Customer.__elasticsearch__.import 

File : customers_controller.rb
class CustomersController < ApplicationController
  def import
    @customers= []
    10.times do |i| 
       @customers << Customer.new(:name => "customer#{i}")
    end
    Customer.import @customers
    if Customer.import @customers
        render json: @customers, status: :created
    else
        render json: @customers.errors, status: :unprocessable_entity
    end
  end
end

**Comment by amal007** [comment]
the answer giver by @aurels  works fine. Just copy pasting the above answer below.

you just need to add the below code to config/application.rb file
 
require File.expand_path('../boot', __FILE__)
require 'rails/all'
require 'activerecord-import/base'

class ActiveRecord::Base
  class << self
    alias :ar_import :import
    remove_method :import
  end
end

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(:default, Rails.env)

    
And then use **ar_import**  for all the ActiveRecord Import .

**Comment by snehaldpatel1992** [comment]
I tried to rename active record's import method to ar_import. I am able to insert multiple records using ar_import method. But I am still not able to change indexing of Elastic search. 

My gem file is

```
gem 'activerecord-import', '~> 0.13.0', :require => false
gem 'elasticsearch-model', '~> 0.1.9', :require => false
gem 'elasticsearch-rails', '~> 0.1.9', :require => false
```

Customer.rb

```
require 'elasticsearch/model'
class Customer < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
 
  has_many :contracts
  has_many :segments 

  has_many :payouts
  has_many :incentives, through: :payouts
end

Customer.import # for auto sync model with elastic search
```

I think the problem is the customer model is not able to import elastic search gems.

Can you suggest me how to manually load elastic search gems  in Customer model  so that it can have import method of elastic search?

**Comment by ChladWick** [comment]
nice
