### ISSUE TITLE
ActiveRecord::Store values are not encoded

### ISSUE THREAD

**Issue by iamWh1sp3r** [zdennis/activerecord-import#150]
I have a model with `store :my_store, accessors: [:my_attr], coder: JSON`.
The value gets saved as "--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess".

**Comment by sgil-carecloud** [comment]
having same problem

**Comment by DWC01** [comment]
Hey all, 

Having same issue here, anyone find a fix to this?

**Comment by ben-av** [comment]
I encountered the same issue.
Looks like using accessors is not supported in AR-Import.

Managed to get around it by skipping the accessors and providing a hash.
```
Model.new(my_store: {my_attr: 'test'}) # works
Model.new(my_attr: 'test') # attribute will not be saved
```

**Comment by jkowens** [comment]
Store accessors should now be supported.
