### ISSUE TITLE
How check exist object?

### ISSUE THREAD

**Issue by chip-and-dail** [zdennis/activerecord-import#154]
If the object exists that update, but not create. How I can do it? Only with validator on model?

**Comment by jkowens** [comment]
The best way to handle this is to make use of the `:on_duplicate_key_update` option if your database adapter supports it. Currently MySQL and Postgres 9.5+ support on duplicate key update.

See: https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update
