### ISSUE TITLE
Returns information should be in the readme

### ISSUE THREAD

**Issue by globalkeith** [zdennis/activerecord-import#174]
Hey, great gem. 

Just wanted to suggest that the [returns stuff](https://github.com/zdennis/activerecord-import/blob/506f765a7462ed4cbfcc1d42e769bd987a8680dc/lib/activerecord-import/import.rb#L6) is added to the readme/examples.

I was just about to fork to implement this functionality but I see its already been done, just not mentioned in the help file.

thanks

**Comment by globalkeith** [comment]
Seems like the "num_inserts" value is incorrect by -1

**Comment by oniofchaos** [comment]
@jkowens I'm a little confused on what this one is asking for? Do you have a little more guidance on what needs to be added/copied over into the README file?

**Comment by jkowens** [comment]
The link above was outdated, here is the return object that I believe this was referring to:

https://github.com/zdennis/activerecord-import/blob/506f765a7462ed4cbfcc1d42e769bd987a8680dc/lib/activerecord-import/import.rb#L6

**Comment by oniofchaos** [comment]
Thoughts @jkowens ?

**Comment by jkowens** [comment]
Maybe we could just display sample return objects in the examples:

```
articles = [
  Article.new(author_id: 1, title: 'First Article', content: 'This is the first article'), 
  Article.new(author_id: 2, title: 'Second Article', content: ''),
  Article.new(author_id: 3, content: '')
]
Article.import articles, returning: :title # => #<struct ActiveRecord::Import::Result failed_instances=[#<Article id: 3, author_id: 3, title: nil, content: "", created_at: nil, updated_at: nil>], num_inserts=1, ids=["1", "2"], results=["First Article", "Second Article"]>
```

The ids and results attributes will only be useful for those using Postgres. They will just be empty arrays for MySQL and SQLite.
