### ISSUE TITLE
Getting "ActiveRecord could not connect" error when using with threads

### ISSUE THREAD

**Issue by alainmeier** [zdennis/activerecord-import#175]
I am attempting to show a [progress bar](https://github.com/jfelchner/ruby-progressbar) as I run the import. Because `import` is a lengthy task, I thought I would just open a new thread and until it's done, update my progress bar. This seems to work for about 2000 entries (I am loading them in batches of 500), but every time it will then crap out and I'll get the error:

```
could not obtain a database connection within 5.000 seconds (waited 5.002 seconds)
```

The code snippet is:

```ruby
t1 = Thread.new { MyModel.import items, validate: false }
@progress_bar.refresh until t1.join(0.10)
```

Has anyone ever used `activerecord-import` with threading successfully? Alternatively, does anyone know of a better (working) way of trying to accomplish what I am doing?

**Comment by alainmeier** [comment]
Alright, figured it out if anyone has a similar problem. Basically because I made my own thread, the number of ActiveRecord connections was being exhausted. Gotta wrap that bad boy in a block which explicitly defines the connection you will use and then close it after use.

Updated code snippet:

```ruby
t1 = Thread.new do
     ActiveRecord::Base.connection_pool.with_connection do
          MyModel.import items, validate: false
     end
end
@ progress_bar.refresh until t1.join(0.10)
```

**Comment by zdennis** [comment]
Ah, I didn't know that. Thanks for posting what you found!
