### ISSUE TITLE
Benchmarks don't run, need updating

### ISSUE THREAD

**Issue by johnnaegle** [zdennis/activerecord-import#182]
I've tried running the benchmarks (mysql) to compare current values with what is in the wiki/readme.  However, they don't run for me.

I get this:

    activerecord-import/benchmarks> ruby benchmark.rb 
    /Users/johnnaegle/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- boot (LoadError)
	    from /Users/johnnaegle/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	    from benchmark.rb:3:in `<main>'

I started pulling on that thread to get things to run, but I couldn't get ActiveRecord to initialize correctly.

Just copying the code from ```test/test_helper.rb``` didn't get me past initializing the logger.

Help?  I'd love to run the benchmarks, add more and add some for postgresql.

**Comment by jkowens** [comment]
@johnnaegle looks you fixed this?

**Comment by johnnaegle** [comment]
Yes, I think so

https://github.com/zdennis/activerecord-import/pull/183
