### ISSUE TITLE
Import + hstore

### ISSUE THREAD

**Issue by pkurek** [zdennis/activerecord-import#186]
Hello,

Is it possible to use `AR.import` with postgresql hstore extension ? Right now I'm getting this error

```ruby
ActiveRecord::Import::MissingColumnError: Missing column for value <field> at index 0
```
Edit 1:

I think the gem itself has problems with STI in general. Example it duplicates the "type" field when trying to inject.

**Comment by jkowens** [comment]
I'm not sure about STI, but the MissingColumnError could be caused by the way the store values are being set. See #150 and #151. Could you post sample code of how you are attempting to import?
