### ISSUE TITLE
Support INSERT ... ON CONFLICT DO NOTHING/UPDATE (also known as UPSERT) for PostgreSQL 

### ISSUE THREAD

**Issue by JustusLauten** [zdennis/activerecord-import#187]
The feature exists already for MySQL databases and can be used with the :on_duplicate_key_update parameter. Upcoming versions of PostgreSQL will feature a similar functionality: 

http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=168d5805e4c08bed7b95d351bf097cff7c07dd65

It would be cool to see this feature in activerecord-import, also for PostgreSQL databases.

**Comment by zdennis** [comment]
@JustusLauten ooh, that will be nice for Postgres to get. Any idea what version they are planning on including this in?

**Comment by johnnaegle** [comment]
Postgres 9.5: https://wiki.postgresql.org/wiki/UPSERT

**Comment by pasku** [comment]
+ 1

**Comment by bkingon** [comment]
@zdennis any chance we could get this implemented?

**Comment by ptolts** [comment]
https://github.com/zdennis/activerecord-import/pull/209


^^ Quick and dirty. Maybe someone wants to take it on and make it merge worthy.

**Comment by jkowens** [comment]
Postgres 9.5 was released yesterday with the UPSERT feature. :+1: 

http://www.postgresql.org/about/news/1636/

**Comment by ptolts** [comment]
It's butter

**Comment by shlima** [comment]
+1

**Comment by jkowens** [comment]
The implementation for UPSERT with Postgres is going to have to be slightly different than that for MySQL.

Postgres requires that the constraint that may result in a duplicate key error be specified, where MySQL does not. It can referenced by either column name(s):

>INSERT INTO countries (country, updated_at) VALUES ('France', now()),('Japan', now()) ON CONFLICT **(country)**  DO UPDATE SET countries.updated_at = EXCLUDED.updated_at;

Or by constraint name:

>INSERT INTO countries (country, updated_at) VALUES ('France', now()),('Japan', now()) ON CONFLICT **ON CONSTRAINT countries_pkey**  DO UPDATE SET countries.updated_at = EXCLUDED.updated_at;

The [documentation](http://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) indicates column name should be preferred (see the "Tip" for on conflict clause). That being said, I was thinking it would be acceptable to just make column names the requirement for identifying the unique constraint.

Any thoughts about what this more explicit syntax should look like? I was thinking that even though it doesn't match the Postgres syntax, it might be nice to stick with the :on_duplicate_key_update parameter. This would be a hash with an attribute for the key and one for the columns that should be updated.

`Country.import [country], on_duplicate_key_update: { key: :country, columns: [:updated_at] }`

:key would have to take either a single value or array of column names and :columns could be either an array or hash similar to the existing MySQL functionality.

Thoughts on the naming? Other suggestions?

**Comment by rwilliams** [comment]
![image](https://cloud.githubusercontent.com/assets/29144/12228283/f0f56f90-b7ed-11e5-8718-c15d2daafa34.png)
