### ISSUE TITLE
Cannot serialize HashWithIndifferentAccess

### ISSUE THREAD

**Issue by sgil-carecloud** [zdennis/activerecord-import#191]
Hello there, 

Love the work you guys have put into this project. I have one small issue though and i dont know if it has been solved yet or if this is the expected behavior.

When i save to the database, any column with a  serialized HashWithIndifferentAccess object  is turned into a normal hash. 

for example: 
if i save without ar-import. my object looks like this in the database
--- !map:HashWithIndifferentAccess 
be_id: "16"
from_date: 06/03/2011
to_date: 06/03/2011
or like this:
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
be_id: '2052'
date_range: ''
from_date: 04/01/2014
to_date: 04/04/2014

but if i save with ar-import my object looks like this in the database:
---
be_id: '1706'
date_range: ''
from_date: 01/01/2011
to_date: 06/11/2012

Please let me know about this. i dont know if this is an issue that has been seen before or what. ar-import is amazing but if we cant save serialized objects correctly then its a problem :(

**Comment by zdennis** [comment]
Just out of curiosity what'd you find to close the issue?

**Comment by sgil-carecloud** [comment]
since my records were coming in from a API call they were changed to a normal hash. I was having the same problem with this about a year back but gave up on it because i couldn't find the problem. After i wrote the issue it clicked in my head lol.
