### ISSUE TITLE
NoMethodError: undefined method `cast' with Rails 5

### ISSUE THREAD

**Issue by tolien** [zdennis/activerecord-import#192]
With full recognition that Rails 5 isn't released yet, etc. :)

From Gemfile.lock:

    remote: https://github.com/zdennis/activerecord-import
    revision: 1ac1be50290315dc4140d88514b14d9f309d265d
    remote: git://github.com/rails/rails.git
    revision: ae5f2b4e79f3e41aad8280109d8bfc788a1a2733

When I call ModelObject.import list_of_modelobjects, I get:

    NoMethodError: undefined method `type_cast' for #<ActiveRecord::ConnectionAdapters::Column:0xc1a2a14>

It looks like Import#values_sql_for_columns_and_attributes]
(https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L464) falls over because https://github.com/rails/rails/commit/b93b39eff6829ee05ffec1cc8c505f69cbb53fdc removes #type_cast_from_user  from ActiveRecord:ConnectionAdapters:Column. I figured the solution would be to add a third branch, i.e. if

    column.respond_to?(:type_cast_from_user)

and

    column.respond_to?(:type_cast)

are false, do something different. Any thoughts on what the "something different" should be?

**Comment by zdennis** [comment]
`activerecord-import` now has Rails 5 compatibility as of 0.11.0 and I just released 0.12.0 so we should be good to go here. Let me know if you see any issues. Thanks!
