### ISSUE TITLE
Switch sqlite3-ruby to sqlite3 in Gemfile

### ISSUE THREAD

**Issue by fenec** [zdennis/activerecord-import#194]
Since sqlite3-ruby is just a wrapper around sqlite3 gem (see here https://rubygems.org/gems/sqlite3-ruby) it is safe to switch it in Gemfile. As recommended by sqlite3 team: 

> Hello! The sqlite3-ruby gem has changed it's name to just sqlite3.  Rather than
installing `sqlite3-ruby`, you should install `sqlite3`.  Please update your
dependencies accordingly.

> Thanks from the Ruby sqlite3 team!

> <3 <3 <3 <3

PR: https://github.com/zdennis/activerecord-import/pull/195

**Comment by zdennis** [comment]
Merged as part of #195 .
