### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by fabioperrella** [zdennis/activerecord-import#202]
Hi, is there a changelog file? I am updating from version 0.5.0 to 0.10.0 and it would be great if I could check the updates

**Comment by fabioperrella** [comment]
:+1:

**Comment by descentintomael** [comment]
:+1:

**Comment by zdennis** [comment]
I have been relying on the Github compare feature in the past as well, but I have now added a [CHANGELOG](https://github.com/zdennis/activerecord-import/blob/master/CHANGELOG.md) and will keep it updated with each release moving forward.

**Comment by seanlinsley** [comment]
Thanks @zdennis :-)
