### ISSUE TITLE
Add support for import batch size

### ISSUE THREAD

**Issue by bsutherland** [zdennis/activerecord-import#207]
Using `import`, I brought down our QA server when it tried to insert 500,000 records in a single INSERT statement.

Of course I can fix this myself externally, but a batch size option with a sensible default would be nice!

By the way, thanks for the great work.. activerecord-import is giving us about a 10x speedup on our import tasks.

**Comment by zdennis** [comment]
This is a great suggestion @bsutherland. I will put this on the docket to get in place.

**Comment by benmanns** [comment]
In the meantime, you can batch inserts somewhat easily by yourself:

```ruby
records.each_slice(500) do |slice|
  MyModel.import [:column, :column2], slice
end
```

**Comment by jkowens** [comment]
Any thoughts on what should be the default batch size should be?

**Comment by bsutherland** [comment]
Thanks for following up!

ActiveRecord itself uses 1000 as a default. Not sure how that was decided
though. Maybe it's explained in the source? Might be exposed as a named
constant too?

http://api.rubyonrails.org/classes/ActiveRecord/Batches.html

**Comment by jkowens** [comment]
@bsutherland well I took a stab at this feature, but I think 500,000 records loaded up into memory might still cripple a server :wink:

**Comment by bsutherland** [comment]
Great, thanks! Yes, 500,000 ActiveRecords can take some time, but it's a batch process on a server dedicated to that purpose.
