### ISSUE TITLE
import method unknown in production (Rails 4.0.5)

### ISSUE THREAD

**Issue by generationloss** [zdennis/activerecord-import#210]
I just discovered this gem, and it works like a charm (using version 0.10.0 and and ActiveRecord 4.0.5) in development, but when I deployed to production I get an unknown method 'import' error on my class...if I go into the Rails console in production and try it there it recognizes the method.  So is this a loading issue, where my model is getting loaded before the gem is for some reason?  Anyone got any ideas?

**Comment by manusajith** [comment]
Is this issue resolved? @generationloss this is a curious case. I am using the gem in production I have faced no such issues.

**Comment by generationloss** [comment]
Yes, it turns out it was a problem with Capistrano not updating the symlink to our most current deployment...doing a hard reset of Unicorn fixed it.  Go figure.

**Comment by zdennis** [comment]
@generationloss, thank you for following up with the resolution. @manusajith, thank you for jumping in as well as I'm a little late to the conversation!
