### ISSUE TITLE
Serialization fails when serializing to JSON

### ISSUE THREAD

**Issue by MaxGabriel** [zdennis/activerecord-import#211]
activerecord-import supports saving serialized fields, as described in this spec:

```ruby
  describe "importing serialized fields" do
    it "imports values for serialized fields" do
      assert_difference "Widget.unscoped.count", +1 do
        Widget.import [:w_id, :data], [[1, {:a => :b}]]
      end
      assert_equal({:a => :b}, Widget.find_by_w_id(1).data)
    end
  end
```

However, this fails when `serialize :data, JSON` is used instead of `serialize :data, Hash`. Instead of serializing to JSON, the data is serialized to YAML (the ActiveRecord default). This can be reproduced by changing the `serialize` line in `widget.rb` to `serialize :data, JSON`, as demonstrated [in this branch](https://github.com/zdennis/activerecord-import/compare/master...MaxGabriel:serializeJSON?expand=1).

**Comment by MaxGabriel** [comment]
The tests passed when using `serialize :data, JSON` prior to [this commit](https://github.com/zdennis/activerecord-import/commit/e85ad6ceaa02f5cfc6c01c65461fcdd68c6c37a9), if you also change the serialized fields test to use Strings instead of Symbols (serializing to JSON doesn't preserve the string/symbol distinction).

**Comment by MaxGabriel** [comment]
This problem is potentially limited to Rails 4.1

**Comment by zdennis** [comment]
Thanks for reporting and following up with additional info @MaxGabriel. This appears to work for ActiveRecord 4.0 and higher. I don't see an issue with ActiveRecord 4.1 specifically so if there's a specific version you're concerned with feel free to post that and I will verify.

I've added a test around this with #220 . It will be merged soon.

**Comment by MaxGabriel** [comment]
Hey @zdennis, I forget what the reason was, but I think I concluded this was only limited to our specific version or something. I think this is OK to close.

**Comment by zdennis** [comment]
Thanks @MaxGabriel

**Comment by elben** [comment]
I'm running `activerecord (4.0.13)` (migrating a Rails 3 app) and `activerecord-import (0.10.0)` (I've also tried HEAD d1f6967) and I'm having problems with serialized JSON attributes. The SQL statements look like:

```
class MyModel < ActiveRecord::Base
   serialize :a, JSON
end

  Class Create Many Without Validations Or Callbacks (0.6ms)  INSERT INTO `my_models`  ... VALUES ('--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\n\'@mainColor\': \'#555\'\nselect_thing: cow\ndummy: mouse\n\'@dummy1\': \'#ff0000\'\n' ...
```

I spent some time trying to debug in activerecord and this gem, but couldn't get a breakthrough. I'd be happy to help debug some more, but I'm not too familiar with Rails internal:

In my app `MyModel.columns[i].coder` returns `nil` (where `i` is the correct value to get the serialized column), but when I do `MyModel.serialized_attributes`, I see the proper coder. Also, something like this works:

```ruby
m = MyModel.new.type_cast_attribute_for_write(MyModel.columns[i], {a: :b, "b" => "c"})
m.serialize
# "{\"a\":\"b\",\"b\":\"c\"}"
```

**Comment by elben** [comment]
I bumped down to version `0.6.0` and that version seems to work, basing off commit https://github.com/zdennis/activerecord-import/commit/e85ad6ceaa02f5cfc6c01c65461fcdd68c6c37a9

**Comment by zdennis** [comment]
@elben, can you see if this is still an issue with activerecord-import 0.11.0 ?

**Comment by elben** [comment]
Not fixed. Here is my debugger session:

```
[492, 501] in /mnt/www/tweetriver/shared/bundle/ruby/2.0.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb
   492:              connection_memo.next_value_for_sequence(sequence_name)
   493:           elsif column
   494: if column.name == "variables"
   495: debugger
   496: end
=> 497:             if respond_to?(:type_caster) && type_caster.respond_to?(:type_cast_for_database) # Rails 5.0 and higher
   498:               connection_memo.quote(type_caster.type_cast_for_database(column.name, val))
   499:             elsif column.respond_to?(:type_cast_from_user)                      # Rails 4.2 and higher
   500:               connection_memo.quote(column.type_cast_from_user(val), column)
   501:             else                                                                # Rails 3.1, 3.2, and 4.1

(byebug) val.class
ActiveSupport::HashWithIndifferentAccess

(byebug) val
{"@mainColor"=>"#555", "select_thing"=>"cow", "dummy"=>"mouse", "@dummy1"=>"#ff0000"}

(byebug) column.type_cast(val)
{"@mainColor"=>"#555", "select_thing"=>"cow", "dummy"=>"mouse", "@dummy1"=>"#ff0000"}

(byebug) connection_memo.quote(column.type_cast(val), column)
"'--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\\n\\'@mainColor\\': \\'#555\\'\\nselect_thing: cow\\ndummy: mouse\\n\\'@dummy1\\': \\'#ff0000\\'\\n'"
```

Stepping deeper into the `column.type_cast` method is interesting—`coder` is nil:

```
[497, 506] in /mnt/www/tweetriver/shared/bundle/ruby/2.0.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb
   497:             if respond_to?(:type_caster) && type_caster.respond_to?(:type_cast_for_database) # Rails 5.0 and higher
   498:               connection_memo.quote(type_caster.type_cast_for_database(column.name, val))
   499:             elsif column.respond_to?(:type_cast_from_user)                      # Rails 4.2 and higher
   500:               connection_memo.quote(column.type_cast_from_user(val), column)
   501:             else                                                                # Rails 3.1, 3.2, and 4.1
=> 502:               connection_memo.quote(column.type_cast(val), column)
   503:             end
   504:           end
   505:         end
   506:         "(#{my_values.join(',')})"
(byebug) step

[87, 96] in /mnt/www/tweetriver/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/column.rb
   87:         end
   88:       end
   89: 
   90:       # Casts value (which is a String) to an appropriate instance.
   91:       def type_cast(value)
=> 92:         return nil if value.nil?
   93:         return coder.load(value) if encoded?
   94: 
   95:         klass = self.class
   96: 
(byebug) value
{"@mainColor"=>"#555", "select_thing"=>"cow", "dummy"=>"mouse", "@dummy1"=>"#ff0000"}
(byebug) coder
nil
(byebug) encoded?
nil
```

Using [the code](https://github.com/zdennis/activerecord-import/blob/2fdc7015f5e032f349a9b2f6d661ffbe978bd148/lib/activerecord-import/import.rb#L335-L336) in 0.6.0 produces the correct result:

```
(byebug) connection_memo.quote(serialized_attributes[column.name].dump(val), column)
"'{\\\"@mainColor\\\":\\\"#555\\\",\\\"select_thing\\\":\\\"cow\\\",\\\"dummy\\\":\\\"mouse\\\",\\\"@dummy1\\\":\\\"#ff0000\\\"}'"
```
