### ISSUE TITLE
Issue with Rails5

### ISSUE THREAD

**Issue by darnreich** [zdennis/activerecord-import#222]
Hello,
I am currently working on an app with Rails 5 (Beta1) and want to use Activerecord-import.
Unfortunately the execution comes to an exception in method values_sql_for_columns_and_attributes.
Here there is a check whether the Column objects responds to :type_cast_from_user, and if so it is used, if not, method :type_cast is called.
Unfortunately both those methods don't exist.
The column object is of class ActiveRecord::ConnectionAdapters::Column.

Is this a problem with activerecord-import and with Rails 5?

Thanks and regards!

**Comment by zdennis** [comment]
Hey @darnreich, thanks for reporting this. It looks there are some removal/restructuring of code in ActiveRecord 5.0.0.beta1. I've started a changeset at #223 that resolves most of the test failures, but not all of them.

**Comment by zdennis** [comment]
@darnreich, I think PR #223 is just about ready. I'm planning on pushing a new release this afternoon that updates ar-import to work with ActiveRecord 5.0.

**Comment by zdennis** [comment]
This was just released in activerecord-import 0.11.0 gem. The only adapter that currently won't work is `em-synchrony` since it is not AciveRecord 5.0.0 compatible yet.

**Comment by darnreich** [comment]
Thank you!
