### ISSUE TITLE
Bulk uniqueness validation

### ISSUE THREAD

**Issue by sferik** [zdennis/activerecord-import#228]
If I bulk import _n_ records with a uniqueness constraint, _n_ `SELECT` queries will be executed before the `INSERT`.

For example, given the following Active Record model:

``` ruby
class User < ActiveRecord::Base
  validates :email, uniqueness: true
end
```

``` ruby
> users = 10.times.map { User.new(email: "#{rand}@example.com") }
> User.import(users)
  User Exists (2.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.5941205541221567@example.com' LIMIT 1
  User Exists (0.5ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.7343287052445423@example.com' LIMIT 1
  User Exists (0.7ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.322860914726271@example.com' LIMIT 1
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.4479100997353238@example.com' LIMIT 1
  User Exists (0.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.8518056478659825@example.com' LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.12517651279963693@example.com' LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.8874450255741644@example.com' LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.5142328998773664@example.com' LIMIT 1
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.863622688265132@example.com' LIMIT 1
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = '0.4563742277940873@example.com' LIMIT 1
```

Ideally, these 10 queries would be combined into a single `SELECT`:

``` sql
SELECT "users"."email" FROM "users" WHERE "users"."email" IN ("0.5941205541221567@example.com", "0.7343287052445423@example.com", "0.322860914726271@example.com", "0.4479100997353238@example.com", "0.8518056478659825@example.com", "0.12517651279963693@example.com", "0.8874450255741644@example.com", "0.5142328998773664@example.com", "0.863622688265132@example.com", "0.4563742277940873@example.com")
```

Records that contain `email` values returned by this query would not be inserted as duplicates.

**Comment by fenec** [comment]
+1 it will save tons of time on huge bulks

**Comment by jkowens** [comment]
If someone takes this on it would be good to keep in mind that `ActiveRecord::Validations::UniquenessValidator` takes an options hash that should be considered when implementing a new validation method.

```
      # Configuration options:
      #
      # * <tt>:message</tt> - Specifies a custom error message (default is:
      #   "has already been taken").
      # * <tt>:scope</tt> - One or more columns by which to limit the scope of
      #   the uniqueness constraint.
      # * <tt>:conditions</tt> - Specify the conditions to be included as a
      #   <tt>WHERE</tt> SQL fragment to limit the uniqueness constraint lookup
      #   (e.g. <tt>conditions: -> { where(status: 'active') }</tt>).
      # * <tt>:case_sensitive</tt> - Looks for an exact match. Ignored by
      #   non-text columns (+true+ by default).
      # * <tt>:allow_nil</tt> - If set to +true+, skips this validation if the
      #   attribute is +nil+ (default is +false+).
      # * <tt>:allow_blank</tt> - If set to +true+, skips this validation if the
      #   attribute is blank (default is +false+).
      # * <tt>:if</tt> - Specifies a method, proc or string to call to determine
      #   if the validation should occur (e.g. <tt>if: :allow_validation</tt>,
      #   or <tt>if: Proc.new { |user| user.signup_step > 2 }</tt>). The method,
      #   proc or string should return or evaluate to a +true+ or +false+ value.
      # * <tt>:unless</tt> - Specifies a method, proc or string to call to
      #   determine if the validation should not occur (e.g. <tt>unless: :skip_validation</tt>,
      #   or <tt>unless: Proc.new { |user| user.signup_step <= 2 }</tt>). The
      #   method, proc or string should return or evaluate to a +true+ or +false+
      #   value.
```

**Comment by jkowens** [comment]
One more advantage of eliminating uniqueness validations is that the remaining validations could be run in combination with `:on_duplicate_key_update` :stuck_out_tongue_winking_eye:

**Comment by jkowens** [comment]
Resolved by #301.

**Comment by jkowens** [comment]
Uniqueness validation is bypassed as of the v0.18.0 release.

**Comment by Fivell** [comment]
@jkowens , it was not necessary , it can be skipped using validation contexts

sort of 
```
class User < ActiveRecord::Base
  validates :email, uniqueness: true, unless: -> { validation_context == :import } 
end
User.import(users, context: :import)

```


Now 0.18.0 have regression, failed instances are not populated if they are invalid by uniqueness validator

**Comment by jkowens** [comment]
@Fivell that's true, that would have been a way to conditionally validate uniqueness. The issue though was that uniqueness validation just didn't quite work right.

It never checked to make sure that all the items in the import data were actually unique. It just ran N+1 queries against the database. So if an import contained duplicates those would all be inserted if the database query returned 0 or it would raise an exception if the database had a unique index.

Another issue is that validation couldn't work along with the `:on_duplicate_key_update` option which I thought was a problem. 

So for those reasons I thought bypassing uniqueness validation leaned more towards a bug fix than a regression.

If someone needs to validate uniqueness, I could possibly see this as a new import option, say `:validate_uniqueness`, that first checked to make sure import data was unique and then executed a single query to validate that there are no existing records in the database that match (similar to what @sferik described above). 

Here is a nice blog post about a method of validating uniqueness before import:

https://hashrocket.com/blog/posts/rails-quick-tips-easy-activerecord-optimizations

**Comment by Fivell** [comment]
@jkowens , I understand cases why you did this, I generally I'm ok with new default behaviour,  but I would like to see such changes optional or at least opportunity to leave old behaviour
 , to allow users of this gem like me to update without regressions.

**Comment by amitsaxena** [comment]
This should be better documented. When I read that it does validations, I assumed that it honoured all ActiveRecord validations and was surprised to see records which violated the uniqueness constraint getting created. Came across this bug report after searching around. It will be helpful to mention this explicitly in the main documentation and on wiki examples.

**Comment by amitsaxena** [comment]
Here's an attempt at this:
https://github.com/zdennis/activerecord-import/pull/516

Please let me know if this needs any changes to language, or if there are other places where I can add this as well.
