### ISSUE TITLE
Multi-level Imports

### ISSUE THREAD

**Issue by allenwlee** [zdennis/activerecord-import#231]
The README strongly suggests that we can import multi-level objects, e.g.:
 
> Say you had a schema like this:
> 
> Publishers have Books
> Books have Reviews
> and you wanted to bulk insert 100 new publishers with 10K books and 3 reviews per book. This library will follow the associations down and generate only 3 SQL insert statements - one for the publishers, one for the books, and one for the reviews.

where `search has_many :tiers through: :searches_tiers`
I've tried the following:
```
s=Search.new(name: 'Foo')
s.tiers << Tier.new(name: 'Bar')
Search.import [s]
```

`search` gets imported
`tier` does not

should this work?

Also, pull request #104  , although mainly about returning ids in Postgres, has a subconversation about multi-level importing, which was implemented in [this fork](https://github.com/GoodMeasuresLLC/activerecord-import) by @GoodMeasuresLLC, now stale.  Can someone please clarify whether multi-level import is available or not?

**Comment by johnnaegle** [comment]
Multilevel import does work, however, it is only implemented for autosave associations (I believe there is an issue or PR to change that behavior) and you need to import with ```:recursive => true```

The tests have an example:
```
Topic.import new_topics, :recursive => true
```

I think if you change your has_many :tiers association, and maybe the :searches_tiers to be autosave true and add the recursive option to the import, you'll get tiers imported.

**Comment by allenwlee** [comment]
Thanks for your response @johnnaegle .  You were right about the `recursive: true`, but I also needed to add the following to my models: 

For Rails 4.2.0:
Models
```
class Search
  has_many :company_tiers_searches, inverse_of: :search, dependent: :destroy
end

class CompanyTiersSearch
  belongs_to :search
end
```  
then
```
s=Search.new(period_start: DateTime.now); 
s.company_tiers_searches.build(company_role_id: 4, company_tier_id: 1);
Search.import [s], recursive: true
```
successfully resulted in
`#<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=["6912"]>`
