### ISSUE TITLE
Change to Wiki

### ISSUE THREAD

**Issue by allenwlee** [zdennis/activerecord-import#232]
Forgive me, this is the first time I am doing this, but I have some helpful additions to the Wiki (I added a Multi-tier Import example).  I believe it is not possible to update the wiki via a pull request so I am including a link to the edited wiki in my fork here:

https://github.com/allenwlee/activerecord-import/wiki

**Comment by zdennis** [comment]
Thanks Allen! You should be able to update the wiki directly. If not let me know and I'll look into the settings ok GitHub.

**Comment by allenwlee** [comment]
oh no problem!  i can definitely do it.  just didn't want to overstep.  will do now.
