### ISSUE TITLE
Error on using :recursive and :on_duplicate_key_update parameters together 

### ISSUE THREAD

**Issue by yuri-karpovich** [zdennis/activerecord-import#249]
```
Product.import(products, recursive: true, :on_duplicate_key_update=>{ :constraint_name => 'products_pkey', :columns => [ :internal_number, :site_id] })

=> PG::UndefinedObject: ERROR:  constraint "products_pkey" for table "attributes" does not exist
: INSERT INTO "attributes" ("id","price","uom_price","promo_price","promo_uom_price","shipping_cost","level","stock","day_or_week","product_id") VALUES ...
```

The code is searching the constraint **products_pkey** in wrong table **attributes** when the constraint exists in **products** table. I think the straight-forward fix is to apply :on_duplicate_key_update parameter values only for parent model (for Products). 
Anyway it would be perfect it you can fix it for `child models` as well.

**Comment by jkowens** [comment]
@yuri-karpovich thanks for reporting this issue. I think supporting :on_duplicate_key_update for just parent models is the way to go for now. I'll put together a pull request and wait for @zdennis to comment :smile:
