### ISSUE TITLE
Release version 0.13.0

### ISSUE THREAD

**Issue by sferik** [zdennis/activerecord-import#260]
##### Potential blockers

- [x] https://github.com/zdennis/activerecord-import/pull/237
- [x] https://github.com/zdennis/activerecord-import/pull/245
- [x] https://github.com/zdennis/activerecord-import/pull/256
- [x] https://github.com/zdennis/activerecord-import/pull/259
- [x] https://github.com/zdennis/activerecord-import/pull/262

Any others?

cc: @zdennis @jkowens

**Comment by jkowens** [comment]
I would like to see #262 make it in!

**Comment by sferik** [comment]
@zdennis All of the issues that @jkowens and I flagged are now resolved. Is there anything else holding up this release?

**Comment by zdennis** [comment]
@sferik / @jkowens . Thank you both for your diligence and contributions! I've add a PR #263 for the 0.13.0 release. If that looks good to you I'll push out the gem.

**Comment by zdennis** [comment]
Done!
