### ISSUE TITLE
Use of alias_method_chain has been depreciated in Rails 5

### ISSUE THREAD

**Issue by thefliik** [zdennis/activerecord-import#270]
This is my first time using Github / commenting on a project, so forgive me if I've made a mistake, but while upgrading my Rails 4.2 app to Rails 5, I've encountered a depreciation warning related to activerecord-import's use of `alias_method_chain` found in lib > activerecord-import.rb.

As detailed here in [Riding on Rails](http://weblog.rubyonrails.org/2015/3/27/this-week-in-rails-goodbye-alias_method_chain-postgresql-typecasting-and-more/), and here in this Rails pull [request 19434](https://github.com/rails/rails/pull/19434), `alias_method_chain` has been depreciated in favor of Module.prepend. I've [looked into](http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/) offering up a fix using Module.prepend, but I'm afraid I'm just not knowledgeable enough in Ruby.

**Comment by zdennis** [comment]
Thanks for reporting this @thefliik. I've known about this for a while, but I've ignored it since `alias_method_chain` is so much more readable than trying to follow `Module#prepend`.
