### ISSUE TITLE
"No connection pool for ActiveRecord::Base" exception when using version 0.11.0 and higher

### ISSUE THREAD

**Issue by ilkon** [zdennis/activerecord-import#272]
Starting from version 0.11.0 the import method fails with exception ActiveRecord::ConnectionNotEstablished:
```
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:87:in `connection'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-import-0.11.0/lib/activerecord-import/adapters/postgresql_adapter.rb:16:in `insert_many'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb:420:in `import_without_validations_or_callbacks'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb:369:in `import_with_validations'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb:310:in `import_helper'
/srv/project/shared/bundle/ruby/2.2.0/gems/activerecord-import-0.11.0/lib/activerecord-import/import.rb:246:in `import'
```

Database is PostgreSQL 9.3 behind PG Pool, Ruby is 2.2.3, Rails is 4.2.6. I did some tests with the same gems environment but activerecord-import version. Results are stable: version 0.10.0 works perfectly, but 0.11.0, 0.12.0, 0.13.0 fails with exception above.

**Comment by jkowens** [comment]
The commit introduced in 0.11.0 that may be related is d5454373dc074d51498c57748790b12beb598f3f.

**Comment by zdennis** [comment]
@ilkon, can you push up a minimal rails app using the gems you mentioned that expose this issue?

**Comment by ilkon** [comment]
Honestly speaking, I'm not sure it will help because the same application works fine on my developer machine but fails on production. The only difference between development and production environment: on dev machine I have a local single PostgreSQL installation. On production we have PG Bouncer.

Anyway this is the code snippet:
```ruby
latest = []
history = []

stat = {
    keyword_id: 111,
    location_criteria_id: 222,
    date: Date.today,
    search_volume: nil,
    average_cpc: nil,
    competition: nil
}
latest << Models::KeywordLatestStatistics.new(stat)
history << Models::KeywordStatistics.new(stat)

result = nil
Models::Base.transaction do
  Models::KeywordStatistics.import(history)
  result = Models::KeywordLatestStatistics.import(latest)
end
```

**Comment by jkowens** [comment]
@ilkon sharing what gems you are using could help. Are there any other gems that override ActiveRecord's connection management? Is this an intermittent issue or does the connection always fail?   Does this get executed from a controller action/rake task/etc?

**Comment by ilkon** [comment]
@jkowens @zdennis Ok, here is the demo-application created from the real one:
https://github.com/ilkon/activerecord-import-fail-demo
Its prototype is a gem which used as a part of some system. Without system environment (some database tables provided by ginza-core gem) it's useless. But I think it's for code demonstration.

It has a rake task which do the job, so its typical usage is:
rake adwords:active_keywords:fetch_all[true,false]

**Comment by jkowens** [comment]
@ilkon can you try making the :fetch_all task dependent on the :environment task and see if there is any change?

**Comment by ilkon** [comment]
Nice advice! It worked. The exception has gone, all is fixed.

So what's the point? Connection to the db should be established before real work? No lazy connections?

**Comment by jkowens** [comment]
Cool, glad it worked! As of commit 881868beb23945654b30e1f68572e0165aef01dd activerecord-import doesn't establish a db connection when it is loaded. The reason is mentioned in PR #136, but basically it's so that app server startup and spec execution is not slowed down.

So in any code that runs outside of a framework that manages database connections, a connection will have to be explicitly established before calling import (at least that's what I've gathered).

**Comment by ilkon** [comment]
Got it. Thanks for the explanation!
