### ISSUE TITLE
Improve MySQL :on_duplicate_key_update option to allow custom input

### ISSUE THREAD

**Issue by gPrado** [zdennis/activerecord-import#275]
I didn't find any documentation on how to customize the `:on_duplicate_key_update` option to perform a sum over the conflict values. Currently it appears to support only the name of another column, but no operations on them.

This feature would allow basic increments:
```ruby
MyModel.import(my_array, on_duplicate_key_update: { count: 'count + 1' })
```

And more complex cases, such as merging existing values with new ones:
```ruby
MyModel.import(my_array, on_duplicate_key_update: { count: 'count + VALUES(count)' })
```

This would lead to a huge performance improvement as one wouldn't need to load all data beforehand to perform such operations in ruby.

Thanks!

**Comment by jkowens** [comment]
@gPrado the `:on_duplicate_key_update` option for MySQL actually allows a string of SQL as a value as well, but this option is undocumented. I think that would allow you to do what you are asking. I wrote about a situation I used this for:

http://www.jordanowens.me/rails-activerecord-import-conditionally-update-on-duplicate-key/

It would be nice if this option was documented in the wiki 😉

**Comment by gPrado** [comment]
@jkowens nice point, thanks! I tested some configurations but apparently I forgot the most obvious one which is a direct SQL string - my fault.
Anyway, it'd be nice to have it documented in the wiki and/or in the code.

**Comment by jkowens** [comment]
@gPrado I added an example for this to the [wiki](https://github.com/zdennis/activerecord-import/wiki/MySQL:-On-Duplicate-Key-Update-Support).

**Comment by zdennis** [comment]
@gPrado, that is a great question and @jkowens that is a great answer. Thank you for both!

@gPrado, can I close this issue?

**Comment by gPrado** [comment]
Sure, and this is a great gem! Thank you guys!
