### ISSUE TITLE
Polymorphic associations missing type column when imported via association

### ISSUE THREAD

**Issue by seanlinsley** [zdennis/activerecord-import#282]
Initial support for polymorphic associations was added in #248 / #252, but given this:
```ruby
Book.last.discounts.import [:value], [[1]]
```
the `_type` column will not be included in the SQL

**Comment by zdennis** [comment]
@seanlinsley, can you be more specific as to which column you're expecting to filled out that isn't? I think I know, but I'd rather not guess.

**Comment by seanlinsley** [comment]
Sure. With a regular belongs_to association, you have a foreign key column including the name of the other model. From the tests, a chapter has a `book_id` column.

But for polymorphic associations, both the model name and the ID must be stored. From the tests, a discount has a `discountable_id` and a `discountable_type`.

My PR updates the code to also store `discountable_type`.

**Comment by zdennis** [comment]
I'm sorry @seanlinsley I totally missed your PR when I typed my earlier comment. Thank you for being kind to me when I missed the obvious.

**Comment by seanlinsley** [comment]
No worries at all. I should've been more clear when writing the ticket 😄
