### ISSUE TITLE
Bulk Update

### ISSUE THREAD

**Issue by rjrobinson** [zdennis/activerecord-import#286]
I'm curious as to if the import updates the same way that it imports.

I have run several tests where i have an array of models

I run `Model.import models` Then, run against the same and different data, and it seems to only initially create the record. If it is updating, the timestamps are not updating correctly.

**Comment by seanlinsley** [comment]
It looks like [the tests](https://github.com/zdennis/activerecord-import/blob/8ba94f7c05b2259f6447aaf8b01ca5f4b0f5e0a2/test/support/postgresql/import_examples.rb#L96-L97) validate that `updated_at` is updated. Can you create a failing test for your scenario?

**Comment by rjrobinson** [comment]
I believe that `:on_duplicate_key_update` might be an issue. I was not using that. Im curious. 

Do I have to match up the existing keys? (ie pull in the keys and when i Model.new(id: 1) ?) because `:name` is not unique in my case.

**Comment by rjrobinson** [comment]
I guess what I am wondering is... 

if I have data, which are hosts. 

and I run `Host.import hosts`

This will almost always be an update call. 

```ruby
#<struct ActiveRecord::Import::Result
 failed_instances=
  [#<Host:0x007fe8bdac98a8
    id: 1,
    address: "127.0.0.1",
    checks_enabled: true,
    display_name: nil,
    contact_groups: nil,
    last_check: "1448915437",
    last_notification: "0",
    last_state: "0",
    last_state_change: "1384209316",
    last_time_down: "0",
    last_time_unreachable: "0",
    last_time_up: "1448915437",
    name: "RJs Home Server",
    next_check: "1448915737",
    notification_interval: 60,
    notifications_enabled: true,
    num_services: 1,
    num_services_crit: 0,
    num_services_hard_crit: 0,
    num_services_hard_ok: 1,
    num_services_hard_unknown: 0,
    num_services_hard_warn: 0,
    num_services_ok: 1,
    num_services_pending: 0,
    num_services_unknown: 0,
    num_services_warn: 0,
    should_be_scheduled: true,
    state: 0,
    state_type: 1,
    total_services: 1,
    created_at: Sat, 18 Jun 2016 17:31:51 EDT -04:00,
    updated_at: Sat, 18 Jun 2016 17:31:51 EDT -04:00,
    last_known_source: "op5.sys.comcast.net",
    snow_sys_id: nil,
    snow_successful: nil,
    snow_updated_at: nil>],
 num_inserts=0,
 ids=[]>
```

Thoughts?

**Comment by rjrobinson** [comment]
So I have tried it with a second model.  

I tried to import alert data, when I tried to import the same file more them once, all of the inserts failed.

**Comment by seanlinsley** [comment]
I think you have to do this:

```ruby
on_duplicate_key_update: {
  conflict_target: [], # list your unique columns here
  columns: 'updated_at = now()'
}

**Comment by seanlinsley** [comment]
@zdennis is there a simpler way to update `updated_at`?

**Comment by seanlinsley** [comment]
It appears that that is the only option, since `columns: [:updated_at]` creates this SQL:
```sql
DO UPDATE SET "updated_at"=EXCLUDED."updated_at"
```
Which relies on you passing a new value for `updated_at`.

**Comment by zdennis** [comment]
@rjrobinson,

Not all databases supporting updating existing records when batching inserting. MySQL has supported this for well over a decade with ON DUPLICATE KEY UPDATE and PostgreSQL recently got ON CONFLICT DO UPDATE.

activerecord-import does not assume that you want to update when there is a conflict. The library has no way of knowing your intentions so it does the safe thing by default: do nothing, fail if it must. So you will need to pass in an `on_duplicate_key_update` option that tells activerecord-import what you expect to happen with the data.

You can pass in an array of column names that you'd like to have updated or you can pass in a hash of column name to attribute mappings. An example is:

```ruby
# using an array of column names
BlogPost.import columns, values, on_duplicate_key_update: [ :date_modified, :content, :author ]

# using an array of column names
 BlogPost.import columns, attributes, on_duplicate_key_update: { title: :my_new_title }
```

The above API is supported for both MySQL and PostgreSQL, but PostgreSQL also provides an expanded version of `on_duplicate_key_update` in case you want to have it cause conflict on a specific key/constraint other than the default primary key. That usage looks like this:

```ruby
BlogPost.import columns, values, on_duplicate_key_update: { conflict_target: [:author_id, :slug], columns: [ :date_modified ] }
```

With regard to timestamps you will want to pass in `timestamps: true` as an option to `import`. This will tell activerecord-import that you want to automatically provide timestamps. It will only set `created_at` if the record is new and it will automatically ensure `updated_at` gets updated as long as you are providing `on_duplicate_key_update`.

I hope this helps and unblocks you!

**Comment by zdennis** [comment]
Also, for more options please see: https://github.com/zdennis/activerecord-import/blob/be8ce5132b08babfb70af4d277a5e61d3886c9ef/lib/activerecord-import/import.rb#L172-L190

I'm working on documentation right now so hopefully this will not be an issue to seek out this information in the next week or so. Sorry you had to stumble upon  your question before then.

**Comment by seanlinsley** [comment]
@zdennis earlier today I updated the wiki, which previously only had MySQL documentation, to now also document Postgres usage: https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update

There's still more to document like `on_duplicate_key_ignore`, but I wasn't sure if there was a MySQL equivalent.

**Comment by seanlinsley** [comment]
> The above API is supported for both MySQL and PostgreSQL, but PostgreSQL also provides an expanded version of `on_duplicate_key_update` in case you want to have it cause conflict on a specific key/constraint other than the default primary key. 

Postgres actually requires that you tell it which columns might conflict, so the shorter syntax is unusable in Postgres unless they decide to allow unspecified conflict resolution in a future release.

**Comment by zdennis** [comment]
@seanlinsley, does your table have a primary key? The reason the shorthand _should_ work is that it defaults to using the primary key as the conflict target. If it's not working correctly I'll open a bug so we can get it fixed.

**Comment by rjrobinson** [comment]
Firstly. Awesome follow up. Thanks for the support. Ive been digging into the source code, and Im getting a better understanding of everything now. 

I do have a question. say that i have a record. ComicBook.new(name: "Stargate", issue: 1)

**Comment by zdennis** [comment]
>     ComicBook.new(name: "Stargate", issue: 1, review: "Some awesome review" )
> and then do this 1 million times. 
> and then, the same set of data comes in. If i default to the primary key, :id, how does it know?

In this case it doesn't know. So your use-case is a little different than the use-case that works well with the primary key default. I can see know why you may be getting lots of duplicates.

> I guess the background behind this is that I am aggregating host and service data from several data centers.
>
> some of the service names are the same, but the host_id: is different. The other fields that are to be updated are :plugin_output and :state

It definitely sounds like you'll want to supply your own conflict targets. You know what will make the best sense for your data set, but it definitely sounds like it won't be the primary key.

If you run into any issues let us know. Sharing code will help us help you the most.

**Comment by seanlinsley** [comment]
>@seanlinsley, does your table have a primary key? The reason the shorthand *should* work is that it defaults to using the primary key as the conflict target. If it's not working correctly I'll open a bug so we can get it fixed.

Ah, I just assumed it was broken because the obvious places where upsert are useful in my application are in tables that are both very large, and store external data (or a stats table), where its uniqueness is determined by the data it holds.

In particular it seems broken in this case because without providing a confict target, a SQL syntax error is raised instead of the explanatory error that Postgres provides.

That's because the SQL that's generated is this:
```sql
ON CONFLICT () DO UPDATE SET foo = bar
```

If activerecord-import didn't add the empty `()`, the Postgres error would bubble up correctly.

**Comment by jkowens** [comment]
It would probably be good to raise an `ArgumentError` with an explanation if the shorthand is used and a table doesn't have a primary key. The same thing is true if someone where to pass a `conflict_target: []` or `constraint_name: ''`.

**Comment by rjrobinson** [comment]
So here is some code, I seem to still be failing on instances. 

first, i grab an array of all of the host names and host ids and create a hash table
```ruby
      host_id_array = Host.all.pluck(:name, :id)
      host_map = Hash[host_id_array.map {|key, value| [key, value]}]
```

then i filter out the incoming data points, 

```ruby
host = host.symbolize_keys
      params = ActionController::Parameters.new(host)
      new_host = Host.new(params.permit(
                            :address,
                            :checks_enabled,
                            :contact_groups,
                            :last_check,
                            :last_notification,
                            :last_state,
                            :last_state_change,
                            :last_time_down,
                            :last_time_unreachable,
                            :last_time_up,
                            :name,
                            :next_check,
                            :notification_interval,
                            :notifications_enabled,
                            :num_services,
                            :num_services_crit,
                            :num_services_hard_crit,
                            :num_services_hard_ok,
                            :num_services_hard_unknown,
                            :num_services_hard_warn,
                            :num_services_ok,
                            :num_services_pending,
                            :num_services_unknown,
                            :num_services_warn,
                            :should_be_scheduled,
                            :state,
                            :state_type,
                            :total_services
      ).merge(last_known_source: cname))
```

after this, I do a look up on the hash table, to see if an ID already exists

```ruby
if host_map.key?(new_host[:name])
        new_host.id = host_map[new_host[:name]]
        p 'loaded' # debug purposes
      end
```

I shove this host into an array
```ruby
hosts << new_host
```

then, i call the import
```ruby
 Host.import hosts, on_duplicate_key_update: {conflict_target: [:id], columns: [ :address, :checks_enabled, :contact_groups, :last_check, :last_notification, :last_state, :last_state_change, :last_time_down, :last_time_unreachable, :last_time_up, :next_check, :notification_interval, :notifications_enabled, :num_services, :num_services_crit, :num_services_hard_crit, :num_services_hard_ok, :num_services_hard_unknown, :num_services_hard_warn, :num_services_ok, :num_services_pending, :num_services_unknown, :num_services_warn, :should_be_scheduled, :state, :state_type, :total_services,  :last_known_source], timestamps: true}
```

I have also tried to set the `conflict_target: :id`, and still the import fails on the second try. 

I have tested with multiple sets of data. 

Am I doing something incorrectly?

**Comment by seanlinsley** [comment]
@rjrobinson I'm not sure why that isn't working, but that's probably because I haven't tried importing models, only raw data.

What about a host is unique? Is it name, or address? Whatever it is, I suggest you add a unique index:
```ruby
add_index :hosts, :address, unique: true
```
That way you can import and handle conflicts based on that:
```ruby
Host.import hosts, on_duplicate_key_update: {
  conflict_target: [:address],
  columns: [:address, :checks_enabled, :contact_groups, :last_check, :last_notification, :last_state, :last_state_change, :last_time_down, :last_time_unreachable, :last_time_up, :next_check, :notification_interval, :notifications_enabled, :num_services, :num_services_crit, :num_services_hard_crit, :num_services_hard_ok, :num_services_hard_unknown, :num_services_hard_warn, :num_services_ok, :num_services_pending, :num_services_unknown, :num_services_warn, :should_be_scheduled, :state, :state_type, :total_services, :last_known_source],
  timestamps: true
}

**Comment by jkowens** [comment]
@rjrobinson can this be closed now?

**Comment by rjrobinson** [comment]
Totally. i thought it was closed. a while ago. Thanks
