### ISSUE TITLE
"insert ignore into" vs "insert into"

### ISSUE THREAD

**Issue by gihnius** [zdennis/activerecord-import#292]
Is there a plan to support "insert ignore into"  with an optiom?

**Comment by zdennis** [comment]
Hi @gihnius ! If you're using MySQL you can pass in the `ignore: true` option to import and it will do just that. Let me know if that helps.

**Comment by gihnius** [comment]
@zdennis Thanks.

**Comment by bonafernando** [comment]
This is not working for me... I'm trying:

`Deposit.import batch, ignore: true`

And it doesn't add the INGONE clause into the insertion:

`Deposit Create Many Without Validations Or Callbacks (53.4ms)  INSERT INTO deposit `

Can anyone help me?

**Comment by bonafernando** [comment]
More info about my batch and setup:

`$ gem list activerecord-import

*** LOCAL GEMS ***

activerecord-import (0.21.0)`
`batch.class
 => Array`
`batch.first.class
 => Hash `

And I managed to debug the gem:

![image](https://user-images.githubusercontent.com/2565620/34908730-78cbe79e-f87b-11e7-9678-42838681cd7e.png)

**Comment by bonafernando** [comment]
Sorry, by bad. The problem is my implementation.

```
    batch,batch_size = [], 1_000
    data.each do |row|
        deposit_params = {
          vl_deposit: row["vl_deposit"]
        }
        batch << deposit_params
        if batch.size >= batch_size
          import batch, {:ignore => true}
          batch = []
        end
      end
    end
    import batch
```

I forgot to add the ignore: true at the end of the code also...
