### ISSUE TITLE
on_duplicate_key_update not working with postgres?

### ISSUE THREAD

**Issue by immortal03** [zdennis/activerecord-import#293]
I'm currently using the newest version of the activerecord-import gem for my project which involves importing hundreds of thousands of domain data. So, here's the flow, if the domain name is unique then it creates a new record in the database. If it's a duplicate, then it updates the other columns of the existing record. Here's a test code:

`domains_array = [['test.com', 12], ['test2.com', 23]]
      columns = [:name, :price]

      Domain.import columns, domains_array, on_duplicate_key_update: {conflict_target: [:name], columns: [:price]}`

The problem is I keep getting duplicate records in my database. And if I assign a uniqueness attribute for the 'name' field, I'll get a duplicate error instead of the record being updated.

`I, [2016-06-28T01:50:56.708744 #10915]  INFO -- : ERROR: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_domains_on_name"
DETAIL:  Key (name)=(test.com) already exists.
: INSERT INTO "domains" ("name","price","created_at","updated_at") VALUES ('test.com',12.0,'2016-06-27 17:50:56.703968','2016-06-27 17:50:56.703995'),('test2.com',23.0,'2016-06-27 17:50:56.703968','2016-06-27 17:50:56.703995')RETURNING id
`

Any thoughts on this? Or could it be I'm missing something.

**Comment by jkowens** [comment]
@immortal03 my guess is that you're on a version of PostgreSQL older than 9.5. Can you check and see what version you have installed?

**Comment by immortal03** [comment]
@jkowens I thought I had that covered. Turns out my client version of postgres was >9.5 while the server version was only 9.3. Thanks anyway.
