### ISSUE TITLE
I'm considering making an AR extension to implement `after_commit_batch`

### ISSUE THREAD

**Issue by Adamantish** [zdennis/activerecord-import#298]
First of all if anyone knows of a good gem to make a model callback which works with the batch of uncommitted objects in a transaction that'd be great. It should enable you to do something like

``` ruby
before_commit_batch :check_adds_up_to_one

def self.check_adds_up_to_one
  is_one = @save_batch.inject(0.00){ |sum, instance| sum + instance.percentage_field } == 1
  raise BadError unless is_one
end
```

Notice that unlike all other callbacks this would trigger a class method and use class level data so it's fundamentally different to other callbacks.
If such a gem doesn't exist I intend to make it. 

@zdennis I'm wondering if you'd mind or think it a good idea if it looks to see if activerecord-import is available and forces it to run these batch callbacks by default but provides the option to switch off if required.

I believe that the best argument against using the activerecord-import gem can be overcome this way. The hardest thing about it is the dangerous and laborious business of re-implementing business logic that is already handled by callbacks. If a class level batch callback were available many of the existing ones could be easily refactored to work with it rather than a per-object basis and that would make it practical to have them performantly run once at the end of an import.

I'd argue that a callback's work inevitably needs doing if it represents the hard and fast business rule that it should. The only reason you'd ever skip them would be the necessary evil of re-implementing them with better performance for batch insert. That is a good reason for you to have defaulted them to off but this would be different.

**Comment by jkowens** [comment]
@Adamantish I'm going to close this issue for now, but if you decide to make a gem feel free to open an issue to propose making activerecord-import compatible. 

I'm not sure I follow exactly what you are proposing, but if importing an array of model objects you can force the callbacks to run for each instance after import by doing something like this:

```
models.each { |m| m.run_callbacks(:commit) }
```
