### ISSUE TITLE
duplicate association records when using :recursive with has_one association

### ISSUE THREAD

**Issue by immortal03** [zdennis/activerecord-import#302]
Let's say I have 2 models Domain and DomainStat. Domain has_one DomainStat and DomainStat belongs_to Domain.

Here's what i'm trying to do:

```
domains_array = []
domain = Domain.new(name: name, source: source, listing_type: listing_type)
domain.build_domain_stat(traffic: 12.34, spam_rating: 23.35)

Domain.import domains_array, recursive: true, on_duplicate_key_update: {conflict_target: [:name]}
```

On the first import of 5000 records, both Domain and DomainStat has 5000 records. But when I tried importing the 2nd time with the same records, the Domain stays 5000 while the DomainStat has 10000 records now with duplicate two DomainStat record for each Domain which is equivalent to a has_many relationship.

Any thoughts on this?

**Comment by jkowens** [comment]
For the Domain model you must have a unique index on the database for the `name` column that is preventing duplicates from being inserted. Using `on_duplicate_key_update` is making sure that that the import completes without raising an error.

I would add a unique index on `domain_id` for the DomainStat model to prevent duplicates from being inserted. Currently there isn't a way to handle duplicate key errors for child models when doing a recursive import. So as a workaround I think something like this might work:

```
result = Domain.import domains_array, on_duplicate_key_update: {conflict_target: [:name]}

result.ids.each_with_index do |id, index|
  domain = domains_array[index]
  domain_stat = domain.domain_stat
  domain_stat.domain_id = id
  domain_stats_array << domain_stat
end

DomainStat.import domain_stats_array, on_duplicate_key_update: {conflict_target: [:domain_id]}
``

**Comment by immortal03** [comment]
@jkowens I'll give that method a try and update here soon :)
