### ISSUE TITLE
Add support for conflict target with index predicate

### ISSUE THREAD

**Issue by luislew** [zdennis/activerecord-import#303]
PostgreSQL 9.5 has support for conflicts on partial indexes (see `index_predicate` at https://www.postgresql.org/docs/9.5/static/sql-insert.html). In SQL, this looks like:

`ON CONFLICT (index_column_name) WHERE index_predicate`

This could be supported with an additional `on_duplicate_key_update` option (`conflict_predicate`?), or by extending the `conflict_target` to accept a hash with columns and predicate (e.g. `{conflict_target: {columns: [index_column_name], predicate: index_predicate}}`)

**Comment by zdennis** [comment]
@luislew, you should be able to pass an index expression in as the value for conflict_target, no?

**Comment by jkowens** [comment]
What do you think about naming the new parameter `index_predicate`? We matched the names of the Postgresql parameters so far (`conflict_target`, `constraint_name`), so I think it might be nice to stay with that.

**Comment by jkowens** [comment]
@zdennis looking at the documentation I see now that partial indexes can only be matched when a `WHERE` clause is specified, so just providing a `conflict_target` or `constraint_name` is insufficient.

**Comment by luislew** [comment]
I've got this just about ready to go as a PR, but I'm happy to change `conflict_predicate` to `index_predicate` (agreed on naming consistency). I've written the corresponding tests but don't have an easy way to set up local testing...

**Comment by luislew** [comment]
https://github.com/zdennis/activerecord-import/pull/305
