### ISSUE TITLE
Warn or raise error if "on_duplicate_key_update" is provided when DB adapter doesn't support it

### ISSUE THREAD

**Issue by nexhealth** [zdennis/activerecord-import#307]
IDK how common this problem is, but it happened to me - 100k record cleanup.  The gem just ignores the option and does a normal 'RETURNING ID" at the end sans any of the on_duplicate_key_update SQL.

**Comment by jkowens** [comment]
I think a warning sounds like a good idea since the import will succeed if there aren't any duplicates and will raise an error if there are.
