### ISSUE TITLE
Support non-integer primary keys

### ISSUE THREAD

**Issue by anthonator** [zdennis/activerecord-import#311]
I'm using UUID's are my primary key. Whenever I run an import my id's disappear. I believe this is because you are expecting the primary key to be an integer.

I believe this is the line that's causing the issue:

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L534

**Comment by mensfeld** [comment]
+1

**Comment by jkowens** [comment]
This is probably related to zdennis/activerecord-import/issues/138.

**Comment by jkowens** [comment]
@anthonator the code you pointed out is related to importing associations. It wouldn't work with models with UUID primary keys, so I think that's another issue besides what you have described.

**Comment by anthonator** [comment]
My specific use case is for updates. If I give `#import` an array of `Product` models then after import all the models in that array have an `id` of `nil`.

**Comment by jkowens** [comment]
Ok, the code you pointed out very well is the issue then. I really don't think explicitly calling #to_i is necessary. I assigned:

```
model.id = id
```

And the tests continue to pass. It would be interesting to see what happens when a test for models with UUID primary keys was added.

**Comment by jkowens** [comment]
I've sent up a PR to support uuid primary keys. @anthonator if you could review/test that would be appreciated!

**Comment by anthonator** [comment]
Awesome! I'll give it a go!

**Comment by jkowens** [comment]
This has been added in the 0.16.0 release.
