### ISSUE TITLE
JSONB support

### ISSUE THREAD

**Issue by mparodi** [zdennis/activerecord-import#313]
There's an error on [import.rb #360](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L360). It always returns an empty hash ({}) for JSONB columns, so no value is saved on the database!

```ruby
model.read_attribute_before_type_cast(name.to_s)
```

What is the problem of using _**model[name.to_s]**_ instead? It seems it works for me. I'm guessing for some other types it wouldn't.

Any workaround? Any plan to update the gem to support JSONB columns?

**Comment by anthonator** [comment]
I'm having a similar issue. I have a JSONB column that I'm using as an array. Whenever I do an update with `#import` the column gets saved as a string instead of JSONB.

**Comment by jkowens** [comment]
This suggested fix for `hstore` support in #151 would apply to `jsonb` as well.

**Comment by anthonator** [comment]
Got it! What needs to be done to merge that in?

**Comment by jkowens** [comment]
It would actually need a small tweak to check for column type of `jsonb` as well, but I'm thinking @zdennis will want a couple tests included.

**Comment by anthonator** [comment]
@jkowens do you have time for this or do you need some help?

**Comment by jkowens** [comment]
@anthonator I don't think I would be able to get time for this in the next couple weeks, so if someone else can tweak the commit and add tests that would be appreciated!

**Comment by jkowens** [comment]
This has been added in the 0.16.0 release.
