### ISSUE TITLE
Replica Pools gem support

### ISSUE THREAD

**Issue by indigoviolet** [zdennis/activerecord-import#317]
In our usage, I found that we weren't importing as efficiently as we could because `supports_import?` and `support_setting_primary_key_of_imported_objects?` were returning false. However, calling them explicitly does work. Is this something we can do inside the gem itself?

```

      # activerecord-import tests respond_to? on this method before doing a
      # multi-INSERT. however we return false, possibly because `connection` is
      # a ReplicaPools::ConnectionProxy. Calling the method causes it to start
      # returning `true` for `respond_to?`
      klass.connection.supports_import?

      # activerecord-import tests respond_to? on this method before setting
      # primary key on the stubs (set_ids_and_mark_clean); however we return
      # false, possibly because `connection` is a
      # ReplicaPools::ConnectionProxy. Calling the method causes it to start
      # returning `true` for `respond_to?`
      klass.connection.support_setting_primary_key_of_imported_objects?

```

**Comment by jkowens** [comment]
I did a quick scan of the Replica Pools docs and it looks like you might be able to configure a list of "safe methods" to proxy. See https://github.com/kickstarter/replica_pools#configuring.

Can you see if this works?

`config/initializers/replica_pools.rb`

```
ReplicaPools.config.safe_methods = ['supports_import?', 'support_setting_primary_key_of_imported_objects?']
```

**Comment by jkowens** [comment]
I'm closing _for now_ due to inactivity.
