### ISSUE TITLE
document import!

### ISSUE THREAD

**Issue by indigoviolet** [zdennis/activerecord-import#318]
Seems like a useful method, but isn't mentioned anywhere (at least I didn't find it)

**Comment by jkowens** [comment]
You're right, this should be added to the wiki!

**Comment by soundasleep** [comment]
I added a quick note to https://github.com/zdennis/activerecord-import/wiki with it :)

**Comment by oniofchaos** [comment]
It looks like this is pretty heavily documented in the code and in the RubyDoc code wiki. I'm not sure that anything more needs to be done here?

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb
https://www.rubydoc.info/gems/activerecord-import/ActiveRecord%2FBase.bulk_import

**Comment by oniofchaos** [comment]
Thoughts @jkowens ?
