### ISSUE TITLE
Add sqlite support with transactions

### ISSUE THREAD

**Issue by s01ipsist** [zdennis/activerecord-import#32]
http://www.sqlite.org/speed.html
shows that sqlite inserts are massively improved for speed by enclosing them in a transaction 

Could import support for sqlite be added by using the pre_sql_statements and post_sql_statements methods? 

Rails uses transactions internally so BEGIN..COMMIT may not work but sqlite can nest transactions using the SAVEPOINT and RELEASE commands. http://www.sqlite.org/lang_savepoint.html

Rails does this internally with
Model.connection.transaction(:requires_new => true) do  # CREATE SAVEPOINT active_record_1
  #operations
  # active_record_1 now automatically released
end  # RELEASE SAVEPOINT active_record_1
(from http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html )

Over an import of 108466 records in batches of 5000, wrapping my import statement in a transaction decreased processing time from 1584 seconds to 834 seconds. A saving of nearly 50%.

**Comment by jkowens** [comment]
Since activerecord-import 0.4.0 single insert imports have been possible for sqlite (requires v3.7.11 or greater). This improved performance significantly.
