### ISSUE TITLE
has_many associations for child record not working

### ISSUE THREAD

**Issue by lalitlogical** [zdennis/activerecord-import#336]
Hi,

I am building a Web app that contains a lot of data. So we need bulk insert in our tables to improve our web app performance. So I had tried this gem. It is working very well for Top level object and its association.

I have some model in my web app as below. Some are associated with each other through Polymorphic associations.

1) Event
```
has_many :related_event_categories, as: :event_categorisable, dependent: :delete_all
has_many :event_categories, -> { order(:name) }, through: :related_event_categories
```

2) FilteredEvent

```
belongs_to :parent, :class_name => "FilteredEvent", :foreign_key => "parent_id", counter_cache: :child_events_count, optional: true
has_many   :child_events, -> { order(:name) }, :class_name => "FilteredEvent", :foreign_key => "parent_id", dependent: :destroy

has_many :related_event_categories, as: :event_categorisable, dependent: :delete_all
has_many :event_categories, -> { order(:name) }, through: :related_event_categories
```

3) EventCategory

```
has_many :related_event_categories, class_name: 'RelatedEventCategory'
has_many :events, through: :related_event_categories, source: :event_categorisable, source_type: 'Event'
```

4) RelatedEventCategory 

```
belongs_to :event_category
belongs_to :event_categorisable, polymorphic: true, optional: true
```

I need to store Event model data in FilteredEvent data as Parent/Child relation. Means I have a calculation for grouping records of events table and inserting all grouped object with parent object in filtered_events. So I am assigning all events records grouped categories to parent record and event record category to its representative in filetered_events record like below.

```
fileterd_event = FIND OR NEW LOGIC
fileterd_event.event_category_ids = event.category_ids

## Building the child_event here .........
child_event = FIND OR NEW LOGIC
child_event.event_category_ids = event.category_ids
## ---Child Event End

fileterd_event.child_events.build(child_event.attributes)
fileterd_event # Returning and collecting to **new_filtered_events** Array
```
But when I collect all record in **new_filtered_events** and import it with this gem as below. Then it creates parent record, its associated categories and its child records. But child records categories are missing.

`FilteredEvent.import new_filtered_events, recursive: true, validation: false`

I am working with below configuration.
```
Rails 5.0.0.1
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
gem 'activerecord-import', '~> 0.16.1'
```

Can anyone guide me on above to resolve child association issue?

Thanks

**Comment by jkowens** [comment]
@lalitlogical I'm not entirely sure I follow your example, but I'm thinking that instead of assigning `event_category_ids` you need to assign `event_categories` an array of RelatedEventCategory objects that can be imported:

``` 
## Building the child_event here .........
child_event = FIND OR NEW LOGIC
#child_event.event_category_ids = event.category_ids
event.category_ids.each { |id| child_event.event_categories.build(event_category_id: id) }
## ---Child Event End
```

**Comment by lalitlogical** [comment]
@jkowens I had resolved the issue as below.

```
fileterd_event = FIND OR NEW LOGIC
fileterd_event.event_category_ids = event.category_ids

## Building the child_event here .........
child_event = FIND OR NEW LOGIC
child_event.event_category_ids = event.category_ids
## ---Child Event End
```

**```fileterd_event.child_events << child_event```**
```
fileterd_event # Returning and collecting to **new_filtered_events** Array
```

Thanks for reply :)
