### ISSUE TITLE
Import not respecting uuid primary keys

### ISSUE THREAD

**Issue by Dclusin-og** [zdennis/activerecord-import#341]
Greetings,

It looks like ActiveRecord::Import#import_helper was changed to remove columns from the array of columns to populate if it is a primary key and a uuid (https://github.com/zdennis/activerecord-import/blame/master/lib/activerecord-import/import.rb#L370).

Digging around it looks like this code was added as a result of https://github.com/zdennis/activerecord-import/issues/138

One side effect of this is that although it fixes the not-null exception in the mentioned issue, it now prevents callers from explicitly setting the primary key's value if it is a UUID.

So I'm wondering if we want to tighten this up somehow and accommodate both cases. If not, is there another way I can accomplish this?

**Comment by jkowens** [comment]
That is definitely a valid concern. I would like to update that to handle both as you have suggested. I'll have to give this some thought...if anyone has ideas let me know!

**Comment by jkowens** [comment]
@Dclusin-og out of curiousity, are you generating your own uuid values instead of using the postgres uuid_generate_v4() function?

**Comment by Dclusin-og** [comment]
The short answer is yes, we are :). These issues were exposed in the way we have constructed some of our FactoryGirl factories. But there are some places in our code where we need to be able to explicitly populate the uuid's on the models, because they are being generated outside of our rails app.

**Comment by jkowens** [comment]
@Dclusin-og I've created PR #342, can take a look? I think it's safe to assume if the first model doesn't have a primary key assigned, the ids need generated.
