### ISSUE TITLE
Will it supported with IBM DB2 ?

### ISSUE THREAD

**Issue by Hareramrai** [zdennis/activerecord-import#345]
Hi ,

I am planing to use  it. Is there any database dependency ?

Will it work with IBM DB2 ? 

Thanks,
Hare

**Comment by jkowens** [comment]
The databases supported are SQLite, MySQL, and PostgreSQL. However, additional adapters can be supported relatively easily. For example, see this PR to support SQLServer https://github.com/zdennis/activerecord-import/pull/201.

As was mentioned in that PR it would be great if support for other databases was added by someone creating new gems. The [README](https://github.com/zdennis/activerecord-import/blob/master/README.markdown#additional-adapters) for this project describes how to go about creating additional adapters as external gems.

Thanks for your interest in activerecord-import!
