### ISSUE TITLE
ActiveRecord::Import::Result should include rows_affected

### ISSUE THREAD

**Issue by rjosal** [zdennis/activerecord-import#346]
Without rows affected, the client can't react appropriately to imports like on_duplicate_key_ignore.

**Comment by jkowens** [comment]
If using MySQL you might be able to implement a way to get affected rows. See https://github.com/zdennis/activerecord-import/issues/200.

**Comment by jkowens** [comment]
Closing for the reasons mentioned in #200 which also contains a potential solution for MySQL.
