### ISSUE TITLE
How to skip few CSV columns while importing?

### ISSUE THREAD

**Issue by mahendhar9** [zdennis/activerecord-import#349]
Hello. Thanks for the great gem. Saved me tons of time.
But I want to know how to skip few CSV columns when importing.

For example, my xaa.csv has headers like name, author, author_id, rating
While importing, I want to skip the 'author_id' column values and import all the other columns.

```
books = CSV.read("/public/xaa.csv") //What more should I do here to skip the 3rd column
columns = [:name, :author, :rating]
Book.import columns, books, :validate => false
```
Thank you.

**Comment by jkowens** [comment]
The books array will need to be manipulated so that it only contains arrays with values for name, author and rating. I believe you might be able to make use of `CSV::foreach` instead of `CSV::read` to accomplish that.

**Comment by jkowens** [comment]
Awesome, looks like you got an answer on [StackOverflow](http://stackoverflow.com/questions/41288155/ruby-csv-how-to-skip-few-columns-while-reading-csv).

> books = []
> 
> CSV.foreach('/public/xaa.csv', headers: true) do |row|
>   books << [row['name'], row['author'], row['rating']]
> end
> 
> columns = [:name, :author, :rating]
> Book.import(columns, books, validate: false)
