### ISSUE TITLE
#import should dup column_names

### ISSUE THREAD

**Issue by jfirebaugh** [zdennis/activerecord-import#35]
`array_of_attributes` is dup'ed, but not `column_names`, leading to a couple cases where the array passed by the user could unexpectedly be mutated. For example, I was passing the same array for column names and the `:on_duplicate_key_update` option, which led to the `:updated_at` column name getting specified twice in the SQL statement.

**Comment by jkowens** [comment]
Fixed as of 33193afdee7a846da533f1dc57310e6017207594.
