### ISSUE TITLE
Wiki Benchmarking InnoDb Tables speedups

### ISSUE THREAD

**Issue by dmagro** [zdennis/activerecord-import#353]
Hello,

While reading your wiki I realized that the speedups for InnoDb Tables were incorrect, at least for the displayed times.

Here's a link to the repository that I've created with the corrections:
https://github.com/dmagro/activerecord-import-wiki

So that someone can review it and verify if it is eligible to be merged.

**Comment by jkowens** [comment]
Those benchmarks have definitely been needing to be updated 👍  

While you're at it, something I've been thinking should be added is more information about the system that ran the tests. Could include your CPU and amount of RAM along with the version of MySQL? Also the version of ActiveRecord would be good to know. Thanks!

**Comment by jkowens** [comment]
Could you update the MyISAM times as well?

**Comment by dmagro** [comment]
@jkowens I didn't run the benchmarks, just used the display time values to correctly calculate the speedups. The MyISAM Tables seem to be right.

But yes, I think I could run the benchmarks in order to add the new information you've mentioned.

**Comment by jkowens** [comment]
Oh I understand now, yeah if you could confirm that the benchmark tool output is correct that would be really helpful!

**Comment by jkowens** [comment]
I think you should be able to directly update the wiki for this project? If so feel free to correct those speedup values.

**Comment by dmagro** [comment]
I've just updated the Wiki. When I get a chance I will run the benchmarks to get new times and add more information about the machine used.

**Comment by jkowens** [comment]
Thanks! 👏🏻

**Comment by jkowens** [comment]
@dmagro I'm going to go ahead and close this issue since you've corrected the speedup values.
