### ISSUE TITLE
On duplicate key ignore not supported by database

### ISSUE THREAD

**Issue by dcosson** [zdennis/activerecord-import#354]
I'm running into this warning and am confused by [this line](https://github.com/zdennis/activerecord-import/blob/e419c8cc3fd0c053fdd2847173dbd95fb4524077/lib/activerecord-import/adapters/postgresql_adapter.rb#L40-L41).

It looks like we just checked if "on duplicate key update" was supported, but then if we're not trying to use that we log that on_duplicate_key_ignore is not supported. Is this a bug?

**Comment by jkowens** [comment]
With Postgres, on_duplicate_key_ignore and on_duplicate_key_update support are only available in version 9.5 or greater.

**Comment by jkowens** [comment]
I'm closing this issue, but if you are on Postgres 9.5 or newer and there is still a problem please feel free to reopen.
