### ISSUE TITLE
Jruby support?

### ISSUE THREAD

**Issue by sylverfyst** [zdennis/activerecord-import#355]
I'm using activerecord-jdbcsqlite3-adapter to handle my sqlite3 database to start and will move to Postgres shortly with activerecord-jdbcpostgresql-adapter is there support for them through activerecord-import? Thanks

**Comment by jkowens** [comment]
It looks like jdbcpostgresql is supported, but jdbcsqlite3 support does need to be added!

**Comment by sylverfyst** [comment]
Ah ok gotcha, well that just makes our switch to postgres more vital than
ever, thanks for the quick reply!

**Comment by jkowens** [comment]
I've just merged in jdbcsqlite3 support into the master branch. Can you give it a spin and see if it works? An updated gem release will be coming soon.

**Comment by sylverfyst** [comment]
Would there be any syntax to add those adapters in? 

Currently have 
    ''' def self.events_import(event_file)
          Event.transaction do 
            events = CSV.read(event_file.path, :encoding => 'windows-1251:utf-8')
            columns = [:name, :release_id, :event_type, :start_time, :end_time]
            Event.import(columns, events, validate: false)
        End
    End'''

**Comment by jkowens** [comment]
I'm not sure what you're asking? In your database.yml if you have your adapter set to `jdbcsqlite3` or `jdbcpostgresql` activerecord-import should do the rest.

**Comment by sylverfyst** [comment]
Never mind it was an issue with my cab formatting, sorry!

**Comment by sylverfyst** [comment]
*csv

**Comment by jkowens** [comment]
@sylverfyst v0.17.0 has been released which includes JDBC sqlite3 support.

**Comment by sylverfyst** [comment]
Appreciate it! we ended up switching to postgres across the board, but I'll give it a go just in case we need it in the future
