### ISSUE TITLE
Erroneous "on_duplicate_key_update because it is not supported by the database"

### ISSUE THREAD

**Issue by Adamantish** [zdennis/activerecord-import#358]
Nevermind. Just seen that UPSERT was introduced 9.5. Thought it was way earlier.

I can't be certain this is a true issue but I can't see why the following code with PostgreSQL 9.4.10 would produce 'Ignoring on_duplicate_key_update because it is not supported by the database.'

```ruby
 DownloadCount.import([:doi, :parent_doi, :period_start, :quantity],
                         data,
                         validate: false,
                         on_duplicate_key_update: { conflict_target: [:doi, :period_start], columns: [:parent_doi, :quantity] }
                        )
```

I've looked at the gem source as far as [here](https://github.com/zdennis/activerecord-import/blob/76b637fc25c02c6ef2f5874135df9ca6399b01f6/lib/activerecord-import/adapters/postgresql_adapter.rb#L162) but not sure where `postgresql_version` is coming from.

**Comment by zdennis** [comment]
Thanks for updating with what you found @Adamantish that will help the next person who may have a similar question!
