### ISSUE TITLE
MySQL Connection Adapter Doesn't Return :ids in Results

### ISSUE THREAD

**Issue by ranchodeluxe** [zdennis/activerecord-import#360]
I have a `Feature` model where `Feature.supports_import?` returns `true` but no `:ids` are returned in the results. I'm using MySQL. All my imports, regardless of size, return the following result

```ruby
<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=[]>
```
I see [activerecord-import tests](https://github.com/zdennis/activerecord-import/blob/master/test/import_test.rb#L248) that explicitly assert `import` results but none that explicitly assert for `:ids`.

Is the presence of `:ids` in results adapter specific? From what I can tell [by looking at the code](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L580) all adapters should return `:ids`

**Comment by jkowens** [comment]
Yeah, unfortunately only PostgreSQL is able to return ids. The other adapters always return an empty array. That's always bothered me a bit.

**Comment by ranchodeluxe** [comment]
@jkowens: thanks

**Comment by crokobit** [comment]
😢

**Comment by khiav223577** [comment]
😢
