### ISSUE TITLE
Keep track of how far the import is

### ISSUE THREAD

**Issue by dare05** [zdennis/activerecord-import#361]
I haven't been able to find a functionality for this, basically, I need to import 300 mil records, and want to be able to see how far the import has gone. With an ordinary insert, as I loop through the collection, I usually do "each_with_index" and upon each iteration do 'print "#{index}\r".

It would be nice if you could pass a block to the .import method to do the same.

**Comment by jkowens** [comment]
How are you loading the 300 mil records? By default activerecord-import tries to do a single insert, which I would not recommend for that size. There is also a `:batch_size` option, but even that would require passing in values/objects for 300 mil records and I would expect that to destroy your system's memory.

I would recommend incrementally reading the records in batches on your own and then calling `import` for each batch. That way you could also log progress. Is that doable?

**Comment by jkowens** [comment]
Closing for now, feel free to reopen if necessary.
