### ISSUE TITLE
Add Enumerator support

### ISSUE THREAD

**Issue by guigs** [zdennis/activerecord-import#365]
With large amount of data, it is a good idea to use Enumerator instead of Array, because it doesn't need to have all objects in memory at once.

So, records could be loaded in batches as needed.

For example, here is what I'm currently doing:

````ruby
contacts_enumerator.each_slice(BATCH_SIZE) do |contacts|
  Contact.import(contacts)
end
````

I would expect that would work the same:

````ruby
Contact.import(contacts_enumerator, batch_size: BATCH_SIZE)
````

But this is raising `ArgumentError: Invalid arguments!`

The alternative is to call `#to_a` on the enumerator, but it will unnecessary load all contacts into memory.

**Comment by jkowens** [comment]
Hey @guigs, yes your method of loading in batches is definitely the recommended way to do large imports. Besides the memory/performance considerations, it also allows you to do any necessary processing on the objects before importing, logging progress (as suggested in #361) etc.

As far as activerecord-import importing from an enumerator, I'm trying to figure out a use case for that. Wouldn't the records need some kind of processing (requiring them to be loaded) before being inserted right back into the database? I am a bit tired and I could be missing something 😴

**Comment by jkowens** [comment]
Closing for now, feel free to reopen with some details of a scenario where an enumerator could be used. Feedback is always welcome and appreciated 👍
