### ISSUE TITLE
Update GitHub repository description

### ISSUE THREAD

**Issue by jkowens** [zdennis/activerecord-import#367]
Hey @zdennis, this one has bothered me for a while 😄 

There is a typo in the repository description, the last letter in "beyond" is cut off. I was thinking it might be a good opportunity to update that description anyway. A simple one liner that describes the purpose of activerecord-import would be nice.

**Comment by zdennis** [comment]
I've updated it to:

> A library for bulk insertion of data into your database using ActiveRecord.

I'm happy to iterate on it if any particular wording comes to mind. At some point it the web-site will change to point to something useful. My mostly inactive personal blog doesn't seem like the best reference, but I will save that for another day. :)

**Comment by zdennis** [comment]
Or maybe I just remove the web-site for now to avoid confusion. WDYT?

**Comment by jkowens** [comment]
Looks good, how about this small tweak?

> A library for bulk inserting data into your database using ActiveRecord.

I do think the website could just be removed for now.
