### ISSUE TITLE
usage documentation?

### ISSUE THREAD

**Issue by BKSpurgeon** [zdennis/activerecord-import#368]
Hello

thank you very much for the time you've put into creating this gem.

i confess that I'm a noob when it comes to these things. I would like to know how to actually use it but I don't know where to start? 

rgds

Ben

**Comment by jkowens** [comment]
Hi Ben, have you had a chance to look at the wiki entries?

https://github.com/zdennis/activerecord-import/wiki
https://github.com/zdennis/activerecord-import/wiki/Examples

Those should help you get started. Let me know if you have a specific question or issue.

**Comment by BKSpurgeon** [comment]
Perfect, thank you. Someone how or other i missed it.

rgds

Ben
