### ISSUE TITLE
sinchronize problem

### ISSUE THREAD

**Issue by karnopulis** [zdennis/activerecord-import#373]
think to get db id's after save with this:
` NewOffer.import new_offers, :synchronize => new_offers, :synchronize_keys => [:scu]
`
ang got id's like:
`{"scu"=>"54.51.059", "id"=>1, "state"=>nil, ......`
that is not id from db....

**Comment by jkowens** [comment]
@karnopulis could you verify that the `scu` value is unique in the database? Also what version of ActiveRecord are you using and which database?

**Comment by karnopulis** [comment]
i am use mysql of course :( , or i would use :recursive 
 activerecord (5.0.1)
 * activerecord-import (0.16.2)
and you are rigth :scu unique only with another key :result

 fixed problem with code below:

NewOffer.import new_offers
  keys= new_offers.map(&:scu)
  no_ids = NewOffer.where(:result=>self,:scu=>keys).pluck(:scu,:id).to_h
  edit_offers.each { |n| n.new_offer_id= no_ids[n.scu] }
  EditOffer.import edit_offers 

class NewOffer < ApplicationRecord
    has_many :edit_offers, dependent: :destroy

**Comment by jkowens** [comment]
If `scu` and `result` are a unique combination, I think you might be able to do this:

`NewOffer.import new_offers, :synchronize => new_offers, :synchronize_keys => [:scu, :result]`
