### ISSUE TITLE
import store always 0 for enum field

### ISSUE THREAD

**Issue by mra-wtag** [zdennis/activerecord-import#378]
I am trying to save enum value in postgree database using import. Unfortunately its failing. I am not sure, is it a bug of the gem or am I missing something?

```
class User < ActiveRecord::Base
  enum status: { not_required: 0, standard: 1, advanced: 2 }
end
```
I am trying to do something like this:
```
RESULT_FIELDS =  %i(source account status).freeze
IMPORT_OPTIONS = { recursive: false, validate: false }.freeze
results = [['val_1', 'val_2', 'standard']]
User.import(RESULT_FIELDS.dup, results, IMPORT_OPTIONS).ids
```
So it always save 0 in status field. But it should import 1 for `standard`.

**Comment by jkowens** [comment]
@mra-wtag to import enum values, you would have to use models instead of arrays of values. The reason you are seeing 0 imported for 'standard' is because 'standard'.to_i returns 0.

**Comment by mra-wtag** [comment]
Oh yeah got it. Thank you for your reply.

**Comment by Danieliv** [comment]
Hi @jkowens 

Currently I have exactly the same mra-wtag problem, but I'm a little bit new in Rails. Could you explain me how use models instead arrays values?

Thanks.

**Comment by jkowens** [comment]
@Danieliv check out the example in the wiki:

https://github.com/zdennis/activerecord-import/wiki/Examples#import-using-activerecord-models
