### ISSUE TITLE
In supported databases, it should be possible insert only new rows

### ISSUE THREAD

**Issue by wycats** [zdennis/activerecord-import#39]
In some cases, it may be necessary to import a growing data set over time. It would be nice to be able to bulk insert rows only if they don't exist (using IF NOT EXISTS).

**Comment by mahemoff** [comment]
BTW `:on_duplicate_key_update => '1=1''` doesn't work if you want to update all columns when the record is present.

`:on_duplicate_key_update => Book.column_names` does work, although the resulting SQL is verbose as it will contain a=values(a), b=values(b) etc.

**Comment by jkowens** [comment]
Postgres 9.5 and up now supports upsert functionality and activerecord-import has added support for it. There is also the option to use :on_duplicate_key_ignore.

So currently Postgres, MySQL, and SQLite have options for ignoring duplicate keys. At some point it would be nice if they all shared the same option for adding that to the sql statement. That can have its own issue opened though 😜
