### ISSUE TITLE
No validation errors.

### ISSUE THREAD

**Issue by maxrosecollins** [zdennis/activerecord-import#390]
When a validation fails I can only see an array of the failed records `failed_instances`.
How can I view the error messages for these failed records?

**Comment by jkowens** [comment]
@maxrosecollins you call `#errors` on each of the failed instances and that should return the validation messages.

```
failed_instances.each do |model|
  model.errors.full_messages
end
```

**Comment by maxrosecollins** [comment]
Ah yes, thank you!
