### ISSUE TITLE
Bulk Insert didn't work in a transaction

### ISSUE THREAD

**Issue by pytong** [zdennis/activerecord-import#391]
The bulk insert seemed to be successful according to the log. However, when I checked the database, the data wasn't inserted. What might be the cause of this?

code (it is in a transaction):
`Book.import books`

result:
`#<struct ActiveRecord::Import::Result
 failed_instances=[],
 num_inserts=2,
 ids=
  [1,
   2]>`

**Comment by jkowens** [comment]
Hi @pytong, looks like you just solved your issue?

**Comment by pytong** [comment]
Yes, I did. Not sure what was causing the issue. I restarted the app and it started working. Thanks.

**Comment by jkowens** [comment]
Oh strange, well if it becomes a recurring issue please feel free to reopen!
