### ISSUE TITLE
Question: Way to update or delete existing transactions.

### ISSUE THREAD

**Issue by ACPK** [zdennis/activerecord-import#393]
We're currently using the import method to grab stock prices. If however a stock price  already exist on the day of the import (though the price is no longer valid as it could be from hours before), how would we delete the existing stock_price so a new one can be added or update the price?

**Comment by jkowens** [comment]
You can use the option `:on_duplicate_key_update` if you are using MySQL or Postgres 9.5 or greater. You will need to define a unique index on one of the database fields, probably the stock symbol.

See https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update

**Comment by ACPK** [comment]
@jkowens - Thank you!
