### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by jkowens** [zdennis/activerecord-import#397]
The readme could use a makeover 💅 

Adding details for the following issues will be a good start. Pulling in some key information from the wiki would be a good idea too.

- [x] #174 
- [x] #229 
- [x] #233 
- [ ] #318 
- [x] #396  
- [x] #430 
- [x] #442 
- [x] #474 
- [x] #505 
- [x] #507

**Comment by tibbon** [comment]
Hmm, I might take a swing at this when I get a chance.

**Comment by jkowens** [comment]
@tibbon that would be fantastic!!

**Comment by oniofchaos** [comment]
https://github.com/zdennis/activerecord-import/pull/556 checked off https://github.com/zdennis/activerecord-import/issues/474

**Comment by oniofchaos** [comment]
As these get updated, how do you feel about replacing the content of the wikis with links to the appropriate README sections?

**Comment by oniofchaos** [comment]
Also, for https://github.com/zdennis/activerecord-import/issues/396 the OC ended up closing out the issue because it went stale and he wasn't able to provide a demo since he doesn't work on that project anymore

**Comment by jkowens** [comment]
Regarding the the wiki, that sounds good. Add links to the readme and eventually we will probably just delete the entries.
