### ISSUE TITLE
hash instead of arrays for 'fastest' mode?

### ISSUE THREAD

**Issue by jrochkind** [zdennis/activerecord-import#41]
Already supported:

```
columns = [ :title, :author ]
values = [ ['Book1', 'FooManChu'], ['Book2', 'Bob Jones'] ]

# Importing without model validations
```

   Book.import columns, values, :validate => false

Would it make sense to support a basic array import too, which would presumably be nearly as fast (no AR models), but in some cases easier to read/write?

```
hashes = []
hashes << {:title => 'Book1', :author => 'FooManChu'}
hashes << {:title => 'Book2', :author => 'Bob Jones'}

Book.import hashes, :validate => false
```

?

Or I guess the danger there is that the different hashes in the array might have different keys, messing up the bulkness of the bulk import. 

Okay, so how about explicit columns, but it will still take an array of hashes, instead of an array of order-dependent arrays, as the second arg?

```
Book.import [:title, :author], hashes, :validate => false
```

**Comment by jkowens** [comment]
Importing using hashes will not be as fast as using arrays, but the difference should be rather small. Whether using model objects or hashes, they both resolve to arrays for import.

**Comment by jkowens** [comment]
@jrochkind v0.17.0 has been released that includes support for importing an array of hashes.
