### ISSUE TITLE
ids are set incorrectly with on_duplicate_key_ignore

### ISSUE THREAD

**Issue by afn** [zdennis/activerecord-import#411]
Calling `import` with an array of model instances, where some of them contain conflicting keys, causes the ids of the instances to be set incorrectly. Here's a failing spec (test/support/shared_examples/on_duplicate_key_ignore.rb):

```ruby
      it "should skip duplicates and continue import" do
        topics << Topic.new(title: "Book 2", author_name: "Jane Doe")
        assert_difference "Topic.count", +1 do
          Topic.import topics, on_duplicate_key_ignore: true, validate: false
        end
        existing_topic_id = Topic.find_by_title!("Book").id
        new_topic_id = Topic.find_by_title!("Book").id
        assert_equal [existing_topic_id, new_topic_id], topics.map(&:id)
      end
```

I'd expect `topics[0]` to be unchanged and `topics[1]` to be updated with the newly created id. Instead, `topics[0]` gets the id of the newly created record, and `topics[1]` is unmodified.

**Comment by afn** [comment]
This is with postgresql, by the way.

@jkowens Any thoughts on how to get around this? The underlying problem, I guess, is that postgres doesn't return *anything* for conflicting rows with `ON CONFLICT DO NOTHING`, so there's no way to infer which of the returned ids corresponds to which of the records that was attempted to be inserted. There are some potential solutions listed [in this SO post](http://stackoverflow.com/questions/34708509/how-to-use-returning-with-on-conflict-in-postgresql) but they all seem pretty hacky.

**Comment by jkowens** [comment]
Ugh, yeah that's an issue. I had thought of this for the "recursive" import, making the two options mutually exclusive. I didn't think though about the ids being set on the models.

Unfortunately it sounds like we might have to prevent IDs being set on the models when using `:on_duplicate_key_ignore` (or `:ignore`) and document somewhere that if the IDs are needed to use `:on_duplicate_key_update` and set a column like `updated_at`.

**Comment by jkowens** [comment]
@afn as of v0.18.2 IDs are not set for imports using :on_duplicate_key_update.

**Comment by afn** [comment]
Great! Thanks for the quick turnaround.
