### ISSUE TITLE
Question: is there any way to update different cols of multiple rows in a single query too?

### ISSUE THREAD

**Issue by shivabhusal** [zdennis/activerecord-import#414]
The solution below makes multiple SQL queries and is very much costly.
```ruby
people = { 1 => { "first_name" => "David" }, 2 => { "first_name" => "Jeremy" } }
Person.update(people.keys, people.values)
```

**Comment by jkowens** [comment]
If your database supports UPSERT functionality, you could possibly take advantage of the `:on_duplicate_key_update` option when importing.

See: https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update
