### ISSUE TITLE
soone question about D3 Draw trail 

### ISSUE THREAD

**Issue by mjwSilence** [zdennis/activerecord-import#419]
Hi,here is how things stand：
      I used canvas to draw trajectories in my program，It may be because of improper use, so when the point becomes more, the browser will crash，I saw your D3 code on the Internet, and I downloaded it and simulated it. If I replaced your code with my code, it would work very well。
      Of course, I was glad to try it. But because your code doesn't comment a little, or maybe it's because of my poor skills, whatever, I'm in trouble now.So now, I want to ask for your help, I need this, I need to take my little data to your D3 and then let it draw the path in my interface, because you are the code is rundom simulation data, so the problem here, I really need to the real data to it.Also, I might need to change your point and change it into a picture. And the best thing I can do is to display the store's data when the mouse moves to this point.
      Of course, I know you are very busy, and writing this issue is just impossible. If possible, I think, at least if you have an introduction to D3, could you give me a copy?
      Thanks very much。Here is my email : 1376500279@qq.com   OR    mjw19931125@lean-intelligence.com  .

**Comment by syguer** [comment]
```

　　　　　　　／￣￣￣￣＼
　　　　　　/;;::　　　　　　　::;ヽ
　　　　　　|;;:: ｨ●ｧ　　ｨ●ｧ::;;|
　　　　　　|;;::　　　　　　　　::;;|
　　　　　　|;;:: 　　c{　っ　　::;;|
　　　　　　 |;;::　　＿＿　　::;;;|
　　　　　　 ヽ;;::　　ー　　::;;／
　　　　　　　　＼;;::　　::;;／
　　　　　　　　　 |;;::　 ::;;|
　　　　　　　　　 |;;::　 ::;;|
　　　／￣￣￣　　　　 ￣￣￣＼
　　　|;;::　　　　　　　　　　　　　　::;;|
　　　|;;::　　　　　　　　　　　　　　::;;|
```
