### ISSUE TITLE
PG::NotNullViolation When Importing Records With Postgres Expressions As Default Values

### ISSUE THREAD

**Issue by Diasporism** [zdennis/activerecord-import#420]
Here's a simplified version of my schema.rb
```ruby
  create_table "libraries", force: :cascade do |t|
    t.string   "name",                                             null: false
    t.uuid     "key",        default: -> { "uuid_generate_v4()" }, null: false
  end
```
and the migration for it:
```ruby
  def change
    enable_extension 'uuid-ossp'
    create_table :libraries do |t|
      t.string :name, null: false
      t.uuid :key, null: false, default: 'uuid_generate_v4()'
    end
  end
```

Using ActiveRecord normally lets Postgres do it's thing:
```ruby
Library.create(name: "Library") # results in a new Library object with a key generated by Postgres
```

However, bulk importing gives me errors:
```ruby
libraries = [
  Library.new(name: "Library 1"),
  Library.new(name: "Library 2"),
  Library.new(name: "Library 3")
]

Library.import(libraries) # ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "key" violates not-null constraint
```

I've experimented with sending in hashes and arrays instead of the actual ruby objects, but this isn't a great solution for me because ideally I'd like to take advantage of recursive relations at a large scale. An arbitrary example being:
```ruby
libraries = []
5.times do |library_index|
  library = Library.new(name: "Library #{library_index}")
  10.times do |book_index|
    book = library.books.new(name: "Book #{book_index}")
  end
  libraries << library
end
Library.import(libraries, recursive: true)
```

 Edit: added `recursive: true` to my example code snippet because I forgot it.

**Comment by jkowens** [comment]
This is happening because when importing models, ar-import includes all columns in the generated insert sql by default. That means for your `key` field the value is going to be nil. A work around is to pass in an array of the attributes you want included in the insert:

```
libraries = [
  Library.new(name: "Library 1"),
  Library.new(name: "Library 2"),
  Library.new(name: "Library 3")
]

columns = [:name]

Library.import columns, libraries
```
See: https://github.com/zdennis/activerecord-import/wiki/Examples#import-using-activerecord-models-and-explicit-column-names

**Comment by Diasporism** [comment]
That does indeed solve my problem. However, I didn't mention that my Books model also has a default UUID field handled by the same Postgres function, so doing this
```ruby
libraries = []
5.times do |library_index|
  library = Library.new(name: "Library #{library_index}")
  10.times do |book_index|
    book = library.books.new(name: "Book #{book_index}")
  end
  libraries << library
end
Library.import([:name], libraries, recursive: true)
```
still results in a ActiveRecord::StatementInvalid: PG::NotNullViolation due to the key column on Books.

Modifying you example a bit I was able to work around it by doing:

```ruby
libraries = []
5.times do |library_index|
  library = Library.new(name: "Library #{library_index}")
  10.times do |book_index|
    book = library.books.new(name: "Book #{book_index}")
  end
  libraries << library
end
library_attributes = Library.column_names.reject { |column_name| column_name == 'key' }
Library.import(library_attributes, libraries)
book_attributes = Book.column_names.reject { |column_name| column_name == 'key' }
books = libraries.flat_map do |library|
  # update the foreign key on each book to the library_id that was just created
  library.books.each { |book| book.library_id = library.id }
  library.books
end
Book.import(book_attributes, books)
```
It's not super ideal, but it works and I still get a pretty substantial speed boost.

Thanks for the help and the work you guys put into this gem!

**Comment by jkowens** [comment]
Yeah unfortunately, there are limitations when using the "recursive" option.  Just out of curiosity, does ActiveRecord happen to set the foreign key on books or is explicitly doing it as you did necessary?

ie:

```
  # update the foreign key on each book to the library_id that was just created
  library.books.each { |book| book.library_id = library.id }
```

**Comment by Diasporism** [comment]
I inspected the book objects before saving them (but after the library itself was saved) and `library_id` was nil resulting in `PG::NotNullViolation: ERROR:  null value in column "library_id" violates not-null constraint`

That would be nice though ¯/\_(ツ)_/¯
