### ISSUE TITLE
Where condition in DO UPDATE SET?

### ISSUE THREAD

**Issue by Saidbek** [zdennis/activerecord-import#421]
Would be good to have **WHERE** condition in `up_duplicate_key_update` , for example: 

```
Project.import(
  columns,
  values,
  validate: false,
  up_duplicate_key_update: {
    conflict_target: [ :email ],
    columns: [ :first_name, ...],
    condition: "email <> 'foo@bar.com'"
  }
)
```

So far I couldn't find smth similar in source code. [postgresql doc ](https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT)

**Comment by jkowens** [comment]
There's the `index_predicate` attribute for `on_duplicate_key_update`.

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L338

**Comment by Saidbek** [comment]
@jkowens yes I also noticed that, but it's different, there's an option (at least in PostgreSQL) where you can condition in `DO UPDATE SET` command, [DOC](https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT)

> **condition**
> An expression that returns a value of type boolean. Only rows for which this expression returns true will be updated, although all rows will be locked when the ON CONFLICT DO UPDATE action is taken. Note that condition is evaluated last, after a conflict has been identified as a candidate to update.

**Comment by jkowens** [comment]
Oh I understand now. You're right, that isn't currently supported. That would be a nice feature to include and should be fairly simple to add. Are you able to work on a PR for this?

**Comment by Saidbek** [comment]
Yes, I already have something working, will push soon
