### ISSUE TITLE
Are mysql users out of luck when it comes to saving associations in bulk?

### ISSUE THREAD

**Issue by jgoodall628** [zdennis/activerecord-import#422]

**Comment by seanlinsley** [comment]
I'm not sure what you mean; this gem already has upsert support for MySQL (though I haven't used it myself).

**Comment by jkowens** [comment]
The options for MySQL are not great. After importing, you could possibly query based on a column like `updated_at` where the value is greater than a timestamp before insert. You could use the returned objects to build out the associations. I believe both queries would need to be within a transaction.

**Comment by jkowens** [comment]
I'm going to close this issue. My only other suggestion would be to try StackOverflow for ideas retrieving previously inserted IDs.

**Comment by jasonperrone** [comment]
Guessing the situation here hasn't changed? If a MySQL user wants to bulk import models along with their has_many association(s), they can't use this Gem, correct? Well I mean I can still use it, but I have to be willing to set the associations later after bulk importing the models, totally eliminating the benefit of the bulk import, right?

**Comment by jkowens** [comment]
As far as I know MySQL still doesn't offer a way to return all the IDs of the inserted rows. It's hard to say if that eliminates the benefit of bulk import for you or not. If you can possibly reduce the number of inserts executed, you will likely see some improved performance.

If you are using auto increment primary keys and the MySQL setting `innodb_autoinc_lock_mode` is set to 0 or 1, you can possibly get the `last_inserted_id` and calculate ids generated for the number of records inserted. More info here: https://github.com/zdennis/activerecord-import/pull/279
