### ISSUE TITLE
Rails 5.1.1 activerecord-import failed to properly load

### ISSUE THREAD

**Issue by thefliik** [zdennis/activerecord-import#427]
So I ran into a bizarre problem with a brand new rails 5.1.1 app using postgres in which `activerecord-import` didn't appear to load properly and calling `Model.import` resulted in an unknown method error. My understanding is that rails should autoload the gem at startup, but adding `puts ActiveRecord::Import` into a model (as a test) resulted in `uninitialized constant ActiveRecord::Import`. So I tried adding an initializer with
```
require 'activerecord-import/base'
puts ActiveRecord::Import
```
and it resulted in the same error.

(I'll call out the fact that `require 'activerecord-import/base'` wasn't generating an error-->indicating that Rails _was_ finding the file)

Then I decided to update my gemfile from `gem 'activerecord-import'` to `gem 'activerecord-import', github: 'zdennis/activerecord-import'` and that solved the problem. I then tried commenting out `, github: 'zdennis/activerecord-import'` (just to test it again) and the problem resurfaced. When using the non-master version of the gem, the version number is `0.18.3`. When using the master version of the gem the version number is `0.18.3 from https://github.com/zdennis/activerecord-import.git (at master@89b586a)`.

So I've no idea what was going on, and it seems _really likely_ that this was a problem with my environment / implementation, but I'm adding this issue up here in the off chance that it's a new bug and this info helps someone else.

Thanks! Awesome gem!

**Comment by jkowens** [comment]
Could you share the contents of your Gemfile?  Are you using the `composite_primary_keys` gem? It sounds like you possibly have a conflict with another library.

**Comment by jkowens** [comment]
The master version has just been released as v0.19.0.

**Comment by thefliik** [comment]
@jkowens I just updated the gem to the (non-master) `0.19.0` and the problem no longer occurs (yay). Thanks!

But here is my gemfile for interests sake :

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'therubyracer'
gem 'curb' # https://github.com/taf2/curb
gem 'rubyzip' # https://github.com/rubyzip/rubyzip
gem 'activerecord-import', github: "zdennis/activerecord-import" # https://github.com/zdennis/activerecord-import

gem 'graphql', '~> 1.6'
gem 'graphiql-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 0.4.1'

```

**Comment by jkowens** [comment]
Hey that's good to hear, but I have no idea why you would have been having a problem with the previous version!
