### ISSUE TITLE
NoMethodError:  undefined method `column_defaults' for NilClass:Class

### ISSUE THREAD

**Issue by mbbertino** [zdennis/activerecord-import#432]
Hey there I searched for this error and could find anything on it, so I wanted to bring up an issue. 

When importing some data, I'm receiving the above error. the line of code being referenced here: https://github.com/zdennis/activerecord-import/blob/61d8c11d3191ce4b4ccc3e8fec57a09802ffe012/lib/activerecord-import/import.rb#L438 doesn't seem to actually be a method anywhere else.

Any ideas on what could be causing this?

heres' the stack: 
```
NoMethodError: undefined method `column_defaults' for NilClass:Class

1 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 345 in block (2 levels) in import_helper
2 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 341 in map
3 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 341 in block in import_helper
4 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 338 in map
5 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 338 in import_helper
6 File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-import-0.12.0/lib/activerecord-import/import.rb" line 310 in import
7 File "/app/app/services/shopify_customers_importer.rb" line 27 in block in import
```

Forgot to add..

- I'm trying to import an array of models
- this is the call to import: `Customer.import(customers, on_duplicate_key_ignore: true)`

**Comment by mbbertino** [comment]
This was actually an issue on my end. When I was constructed the model array there was a conditional that was passing nil values into the mapped array. Solved by using select and map or the option I found was compacting after mapping. 

I'll close the issue now

**Comment by jkowens** [comment]
Glad you were able to resolve 👍

**Comment by mbbertino** [comment]
Me too 👍 thanks for you work on such a great tool 😄
