### ISSUE TITLE
import! forcing validations

### ISSUE THREAD

**Issue by mustela** [zdennis/activerecord-import#435]
I've checked the code and it seems that when you use `import!` it is forcing to run the validations `options[:validate] = true`, and that's something that isn't so useful. Specially when you want to skip validations but get an exception if something failed in the DB. 
 
Is there any reason about why forcing validation on that method?

**Comment by jkowens** [comment]
The `import!` method was specifically added to throw an exception if a validation failed. Use the `import` method instead, DB exceptions will be raised and it allows to you to disable validations.
