### ISSUE TITLE
TypeError (String into Integer), import successful

### ISSUE THREAD

**Issue by stuffandthings** [zdennis/activerecord-import#436]
Hey,

I'm running into this issue where I run an import and check `ActiveRecord` which shows that I did in fact import all the models successfully, but I get this error:
```
[6] pry(DatabasePopulator)> User.import users, on_duplicate_key_ignore: true, validate: true
TypeError: no implicit conversion of String into Integer
from /Users/omar/.rvm/gems/ruby-2.4.0/gems/activerecord-import-0.19.0/lib/activerecord-import/import.rb:659:in `-'
```
This appears to be the culprit: https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L659

I've been hitting my head against a wall, pretty sure I'm not doing anything out of the ordinary. Any clues?

I'm on Rails `5.1.2` and using version `0.19.0` of activerecord-import.

**Comment by jkowens** [comment]
Are you able to set a breakpoint and inspect the value of models before that line?

**Comment by stuffandthings** [comment]
Yep
users is an array with objects of this form:
`#<User:0x007f846188efe0 user_hash: "fc42d82c52f8be0c5701638453979c2c01547cc86a5d3c6d1bb47fe6630cbb3d", created_at: nil, updated_at: nil>`

If I just ignore the TypeError, I get:
```
[3] pry(DatabasePopulator)> User.first
=> #<User:0x007fa4672327e8 user_hash: "00080c5cafe93be80e81db9ce36ed95671d26bbccc796c168f182baf0c27b970", created_at: Tue, 04 Jul 2017 15:47:25 UTC +00:00, updated_at: Tue, 04 Jul 2017 15:47:25 UTC +00:00>
```
and `User.count` gives me the expected number of users, inspecting individual ones shows that everything is alright.

**Comment by jkowens** [comment]
Hm is `import_result.failed_instances` an array as well?

**Comment by jkowens** [comment]
The failure you are seeing occurs after the records have been imported. The method `set_attributes_and_mark_clean` attempts to set the IDs and timestamps from the database on the ActiveRecord models and mark the objects as clean.

**Comment by stuffandthings** [comment]
I'm not sure how to look for `import_result.failed_instances` or rather where to look for that.

Could this have something to do with me overriding the `primary_key` for my `User` model?

**Comment by jkowens** [comment]
Since you are using Pry, something you could do is open:
`/Users/omar/.rvm/gems/ruby-2.4.0/gems/activerecord-import-0.19.0/lib/activerecord-import/import.rb` and on line 658 add:

`binding.pry`

That will set a break point so you can inspect `models` and `import_result.failed_instances`. If they are both arrays, I would expect line 659 to work, but I'm not sure what the issue is at this point. I wouldn't expect overriding the primary key to be an issue, but I could be wrong.

**Comment by stuffandthings** [comment]
I'll dive into this a bit more later, it seems like just silencing the `TypeError` isn't causing me any other headaches. This isn't production code so I think I can get away with that for the sake of time.

I appreciate the help. I'll report back once I find time to investigate.

**Comment by jkowens** [comment]
Did you override the Object [`#hash`](https://ruby-doc.org/core-2.4.1/Object.html#method-i-hash) method? If so, that might be the issue. See also: https://ruby-doc.org/core-2.4.1/Array.html#method-i-2D

**Comment by stuffandthings** [comment]
I did actually, as a work-around to use objects as the keys of a hash (`{Object: "foo"}`)

**Comment by jkowens** [comment]
Ok so if your `User#hash` method doesn't return an `Integer` value, you will have problems with core Ruby `Array` methods like `#-` and `#uniq`.

**Comment by jkowens** [comment]
I believe we have tracked down the source of the issue, so I'm going to close for now. Please feel free to reopen if you determine otherwise.
