### ISSUE TITLE
Documentation does not reflect that :on_duplicate_key_update works on postresql

### ISSUE THREAD

**Issue by obromios** [zdennis/activerecord-import#445]
The [documentation](http://www.rubydoc.info/github/zdennis/activerecord-import/ActiveRecord%2FBase.import) states that the ```:on_duplicate_key_update```  only works for MySQL, but when I looked at the changelog it seems to imply that this works in 0.15.0.  I checked and found it did work. Very pleased with this, but thought others might appreciate knowing this.  Also, the documentation only mentions using this option with the column, values syntax, but it also worked for me with the array_of_models syntax.  

This gem save me literally a weeks wait for a batch file to complete, so thank you.

**Comment by jkowens** [comment]
Thanks for the heads up, the documentation just needed regenerated on the rdoc site. Always glad to hear about activerecord-import wins too 🙌
