### ISSUE TITLE
`.synchronize` needs to start with `.unscoped` to handle default scopes

### ISSUE THREAD

**Issue by indigoviolet** [zdennis/activerecord-import#454]
https://github.com/zdennis/activerecord-import/blob/9e80a09ec5a193f7905bf97505881e835d6de518/lib/activerecord-import/synchronize.rb#L34

We often have a `deleted_at` column to indicate soft-deletes and a default scope `where(deleted_at: nil)`, but we also want to synchronize deleted models to get their `deleted_at` timestamps in some cases. `synchronize` will currently ignore them because it does not use `.unscoped`.

**Comment by indigoviolet** [comment]
^ rudimentary pull request

**Comment by jkowens** [comment]
Does doing `Post.unscoped.synchronize posts` not work?

**Comment by indigoviolet** [comment]
That's a good suggestion, it does work. However, I think that having to use `unscoped` is a bit surprising -- if I pass in an instance into `synchronize`, I'd expect it to synchronize it; my mental model would be that its behavior would match `.find(instance.id)` or `instance.reload`, both of which will work regardless of default scope.

**Comment by jkowens** [comment]
That's a good point, after reviewing what synchronize is suppose to do I think you're right. Your suggested fix is good. Are you able to add a spec to cover that scenario?
