### ISSUE TITLE
Question: Skip over duplicates

### ISSUE THREAD

**Issue by ACPK** [zdennis/activerecord-import#456]
How would I skip over duplicates?

**Comment by jkowens** [comment]
You could potentially use the :on_duplicate_key_ignore or :on_duplicate_key_update options.

See:

https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Ignore

https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update

**Comment by jkowens** [comment]
I'm closing this for now, feel free to reopen if you need need more specifics for what you're trying to accomplish.
