### ISSUE TITLE
Presence of associated model not validated

### ISSUE THREAD

**Issue by rogerrohrbach** [zdennis/activerecord-import#457]
I've a model:

```
class Thing
  belongs_to :other
  validates_presence_of :other
  before_validation :initialize_other, unless: Proc.new { |thing| thing.other.present? }

  private

  def initialize_other
    build_other name: name, date: Date.today
  end
end
```

This has the effect that any `Thing` without an `other` automatically gets one before validation, and so will always be valid.

When I try to import a `Thing` (using an ActiveRecord model object):

- `initialize_other` is called, and the associated object is correctly instantiated
- `ActiveRecord::Import::Validator` correctly classifies the new instance as valid (`valid_model? == true`)

However, after import, the associated object has not been saved, as it would be in normal ActiveRecord use.  This is true whether or not I pass `recursive: true` (though I note the documentation for that does not mention `belongs_to`).

Is this a bug?  Is there a workaround?

**Comment by jkowens** [comment]
You're correct, belongs_to association imports are not supported by "recursive" imports. However, there is possibly a way to make this work if you're importing models (and you are using Postgres). You'll have to collect all "other" objects that you build and assign to "thing" objects into an array and import that array of objects first. They will have their generated ID set. Then do the import of the array of Thing objects. The foreign key ID will be set and the import should work. 

See: https://github.com/zdennis/activerecord-import/issues/402#issuecomment-328375171

**Comment by jkowens** [comment]
Not sure if this is an option, but can you build out your data tree starting with Other?

Then you could do:

`Other.import others, recursive: true`

Your other objects would be imported and then their associated things.

**Comment by rogerrohrbach** [comment]
I'm grateful for your quick response, Jordan.  I turned your advice into this solution:

```
things.each do |thing|
  thing.send :initialize_other
end

Other.import things.collect(&:other)

Thing.import things
```

which does the job, incurring little overhead.  Thanks 1000k!

**Comment by jkowens** [comment]
Excellent! Glad you got a working solution 👍
