### ISSUE TITLE
Question: using PG's table partitioning?

### ISSUE THREAD

**Issue by ilkon** [zdennis/activerecord-import#458]
Is it possible to use Postgres' table partitions for inserting data to? Basically all I need is to explicitly define table name for inserting.

For example, with master table 'books' and its partitions 'books_1', 'books_2', 'books_3', etc it would be great to have something like
```ruby
Book.import(books, table_name: 'books_2')
```
to insert data to table 'books_2'

**Comment by jkowens** [comment]
As far as I'm aware, ActiveRecord does not support PG table partitions. Are you using a gem to make that happen?

**Comment by ilkon** [comment]
Not yet, only considering some gems. Actually, I'm not sure I need any extra gem for that. I create partitions by raw SQL-queries, reading goes through the main model, so all I need is to insert data to right partition.

**Comment by jkowens** [comment]
This is not going to be possible without extensive changes. I would investigate how to dynamically generate AR models for your partitions. For example: https://stackoverflow.com/a/13156506

Then maybe you could do Book2.import?

**Comment by ilkon** [comment]
Interesting. Thanks, I will dig in that direction.

**Comment by jkowens** [comment]
Cool, sounds good. 

If you're open to using schemas instead of partitions, some have had success using the apartment gem for sharding. Might be another option.

**Comment by ilkon** [comment]
I use PG's schemas too, they are not enough for my needs :)

Thanks anyhow. Just tried your solution with dynamically generated AR model. Works like a charm.
