### ISSUE TITLE
Bulk update support

### ISSUE THREAD

**Issue by ohaddahan** [zdennis/activerecord-import#460]
Is there anyway to use / or enhance the Gem to perform bulk UPDATE and not only INSERT?

**Comment by jkowens** [comment]
The only way I can think of is by making use of the `:on_duplicate_key_update` option that uses INSERT to handle updates. 

See: https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update

**Comment by ohaddahan** [comment]
This worked great , thanks.

```
columns                = Model.new.attributes.keys.delete_if { |i| i == 'updated_at' }
Model.import model_update_array , recursive: true , batch_size: 1000 , on_duplicate_key_update:  { conflict_target: [:id] , columns: columns }
```

**Comment by mahemoff** [comment]
I think bulk updating, with no possibility of inserts, is an important use case for this library and should probably be documented in the README.

In case it helps anyone, here's a light wrapper to help with it and minimises the records and columns which are updated. it could be placed in a config file like config/initializers/active_record.rb.

```ruby
    class ActiveRecord

      def self.bulk_save(records, timestamps: false)
        changed_records = records.select(&:changed?)
        if changed_records.present?
          changed_attribs = changed_records.map{ |s| s.changed_attributes.keys }.flatten.uniq
          self.import [:id]+changed_attribs, changed_records, on_duplicate_key_update: changed_attribs, timestamps: timestamps
        end
      end

    end
```

Now you can change some records and bulk-save them in a single query. e.g.

```ruby
    posts = Post.limit(3)
    posts.first.title = 'new title'
    posts.second.body = 'new body'
    Post.bulk_save(posts) # will bulk-update title and body just for the posts that changed
```
