### ISSUE TITLE
A recursive import with a has_one association fails.

### ISSUE THREAD

**Issue by KurtRMueller** [zdennis/activerecord-import#462]
Hello all,

First, thank you for all your hard work and dedication. I imagine it's a lot of hard work developing and maintaining this popular gem.

In my postgresql-backed rails app, I have a model, `Question`, which `has_many` `QuestionItem`s and `has_one` `QuestionScale`. I am trying to import all questions, items, and scales - the questions and items will successfully import, the scales will not.

Note that I'm attempting to do this during a `db:reset`, so the tables in question are empty. I should also note that `QuestionScale`'s primary key is `question_id` which is unique and used for the `QuestionInfoScale#belongs_to Question` association.

Please let me know if you need any additional information. Thank you for your time and brainpower.

Kurt

**Comment by KurtRMueller** [comment]
I can confirm that adding an `id` column to `QuestionScale` and making that my primary key instead of `question_id` allows scales to be successfully imported. Is it support to work like this? Thanks for any and all info.

**Comment by jkowens** [comment]
Custom primary key fields should work just fine. Do both ActiveRecord and the database know that `question_id` is your primary key?

**Comment by KurtRMueller** [comment]
Ah, that's what it was. I specified that `QuestionScale#question_id` was the primary key in rails but not at a database level.

Thanks for checking in.
