### ISSUE TITLE
Error on Using Constraints with PostgreSQL

### ISSUE THREAD

**Issue by katmlee** [zdennis/activerecord-import#466]
Hello! 

I followed the steps for using [On Duplicate Key Update](https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update) with constraints in postgres. I ran the migration to add an additional column in my table as well as added the constraint per the example. I see that the migration generated an `add_index "table_name", ["some_id", "some_type"], name: "for_upsert", unique: true, using: :btree`

When I run `TableName.import arrayOfNewObjects, on_duplicate_key_update: {constraint_name: :for_upsert, columns: [:some_id, :some_type]}` I'm getting the following error from Active Record: 
PG::UndefinedObject: ERROR: constraint "for_upsert" for table "table_name" does not exist : INSERT INTO "table_name". Any suggestions for troubleshooting this? I see that the migration was successfully because the column was added to the table and because my schema shows the added index. Is there something I'm blindly missing?

**Comment by jkowens** [comment]
I can't think of anything other than making sure the migration ran for the correct environment you are testing against. Also it can't hurt to restart the app just to rule that out.

**Comment by katmlee** [comment]
Thanks @jkowens i dropped the database again and made sure that the two columns for my constraint were not null and then did another db:migrate. That worked in getting rid of the constraint does not exist error. 

One thing though, is the array of columns passed into on_duplicate_key_update with constraint supposed to be the columns that need updating or the columns that create the constraint? The documentation suggests passing the columns we don't want changed:
`Book.import [book], on_duplicate_key_update: {constraint_name: :for_upsert, columns: [:title, :author, :edition]}


book.reload.title  # => "Book1"          (stayed the same)
book.reload.author # => "FooManChu"      (stayed the same)
book.reload.edition # => 3               (stayed the same)
book.reload.published_at # => 2017-10-09 (changed)`

However, for me I needed to pass the columns I did want changed.
Can you please confirm for me? Thanks!

**Comment by jkowens** [comment]
Yes, the columns parameter specifies which attributes get updated. The example in the wiki entry needs to be corrected.

```
Book.import [book], on_duplicate_key_update: {constraint_name: :for_upsert, columns: [:published_at]}
```
