### ISSUE TITLE
Child Objects Loose Association Information, Causing Validation Failures

### ISSUE THREAD

**Issue by DarkArc** [zdennis/activerecord-import#468]
https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L527

The above line causes certain validations to fail. For instance, following a slightly modified version of the example on the wiki:
```
books = []
10.times do |i| 
  book = Book.new(:name => "book #{i}")
  book.reviews.build(:title => "Excellent")
  books << book
end
Book.import! books, recursive: true
```

If review validates the presence of book, when running validations this will fail. This is because the `dup` method provided for AR objects, does not copy associations, only attributes, so the in-memory association between the two is broken.

**Comment by DarkArc** [comment]
Actually upon further investigation, this only seems to be a problem for 2-deep associations.

```
books = []
10.times do |i| 
  book = Book.new(:name => "book #{i}")
  book.reviews.build(:title => "Excellent")
  book.reviews.each do |review|
    review.comments.build(:title => "Great review")
  end
  books << book
end
Book.import! books, recursive: true
```

The equivalent in our case of the book's review is validating fine, however, the review's comments, are not validating the presence of a review.

**Comment by jkowens** [comment]
Can you send a PR with a failing test? We have tests that import topics that have many books, that have many end notes.

https://github.com/zdennis/activerecord-import/blob/master/test/support/shared_examples/recursive_import.rb#L75

I tried adding the following validation to `EndNote` and the tests still passed:

```
class EndNote < ActiveRecord::Base
  belongs_to :book, inverse_of: :end_notes
  validates :book, presence: true
  validates :note, presence: true
end
```

Maybe I'm missing something. Let me know, thanks!

**Comment by DarkArc** [comment]
It seems my gem was significantly out of date. I sincerely apologize for any wasted time, everything seems to be working wonderfully now, my bad.

Thanks for your work on this gem!

**Comment by jkowens** [comment]
No worries, glad everything is good 👍
