### ISSUE TITLE
Increment lock_version on duplicate key update

### ISSUE THREAD

**Issue by simonrussell** [zdennis/activerecord-import#472]
It would be useful to automatically be able to increment the lock_version on duplicate key update.

**Comment by jkowens** [comment]
This does sound like a useful feature. If anyone would like to attempt adding this functionality, a PR would be welcomed. In the mean time, a custom string of SQL can be passed for the columns value, so that might be a way to handle this situation if necessary.

**Comment by simonrussell** [comment]
Indeed, I did the custom string option.  This is what I'm using:

```ruby
update_columns.map { |c| "#{c}=VALUES(#{c})" }.join(',') + ',updated_at=VALUES(updated_at),lock_version=lock_version+1'   # manually increment the lock_version and update updated_at
```

(it's ugly but it's until there's something better)

I don't have a lot of time at the moment, but I can look at making a pull request if people are interested.
