### ISSUE TITLE
Large database ID's

### ISSUE THREAD

**Issue by Juko** [zdennis/activerecord-import#473]
Hey there,

Thanks for making such an amazing importer!
I've been using the gem across a staging and production site and it's really allowed me to solve a huge problem.

On production, I am still running `0.17.2`
But on staging, I have upgraded to `0.20.1`

This is occurring on both versions, I generate an array of new Customer objects (which are very simple and just have a name and code) from a CSV file. I then import this array as:
`Customer.import @customers, on_duplicate_key_ignore: true`

A majority of the time, these customers will already exist in the database. But I noticed that the ID's of these objects were starting to get scarily big. I only have `5039` Customers in my database, but the latest ID has returned `274992079`. I run my importer every 5 minutes, and it takes around 20 seconds to complete.

This same thing occurs on all objects that I import (some are more complex and have relations to other objects getting imported, but if it's resolved on the simple object, we can work to make a solution for the more complex).

A kind of secondary error that could possibly be related... The imported objects are being referenced from Sidekiq jobs. To create these jobs I just pass the id of the objects through, and `find` the object whilst in my worker. On production (using `0.17.2`) this works fine, and nothing seems to be going astray, but on staging (using `0.20.1`) I am getting continuous errors from nearly every worker complaining that it can't find the object. This is the only difference between the two servers currently (and the only thing stopping me from upgrading). I have investigated, and can't see any reason behind why this would be the case.

Thanks for the help! Hopefully we can work together to resolve this!

**Comment by jkowens** [comment]
If you are using MySQL this article might explain why you are seeing big jumps in IDs:

https://www.percona.com/blog/2011/11/29/avoiding-auto-increment-holes-on-innodb-with-insert-ignore

I don't think I can help you with the other issue without more information.

**Comment by jkowens** [comment]
Turns out Postgres behaves the same way when using `ON CONFLICT DO NOTHING` or upsert functionality. This is just the way the databases are designed to work, they increment the sequence.

https://www.postgresql.org/message-id/CA%2BbJJbz7Gydp%2BDRRe_sgV1d9hP_6PtqxzLBwxCAb8DyZxYmcrQ%40mail.gmail.com

**Comment by jkowens** [comment]
I'm going to close this issue. If you can find more information to go on for the second issue mentioned, please feel free to open a new issue for that.

**Comment by Juko** [comment]
Thanks for the help @jkowens. That makes perfectly logical sense for the first issue. I was worried about overflowing the max id of rails as I run the importer every few minutes with thousands of records.

But it seems like I could get away with it by converting the id column to BigInt from here: http://gordondiggs.tumblr.com/post/73986416458/rails-edge-case-id-overflow

Or alternatively just convert the entire db to use UUID's instead from here: https://labria.github.io/2013/04/28/rails-4-postgres-uuid-pk-guide/

As for the second issue, I still haven't come any closer to finding a reason, it's not a pressing issue for us as we can use the old version.

**Comment by jkowens** [comment]
Yup sounds like you have viable options there. Like I said I’ll try to help with the other issue if you can provide more to go on. Maybe code snippets, stack traces, etc. Can you confirm if the correct IDs are being passed to sidekick?

**Comment by Juko** [comment]
Ok, I've just spent a bit of time on it today and the answer was completely separate to this gem. It was the high IDs that had me stumped as they both seemed to be roughly around the same value in both production and staging. I was doing some debugging and got access to the servers configuration and found that both were using the same Redis store, hence some jobs were being picked up and ran in sidekiq on the production server, and some on the staging. So the times it found the wrong ones was when the ID had been sent from staging, and picked up by sidekiq in production and vice versa.

So bar that silliness, thanks for all the help with the main issue!

**Comment by jkowens** [comment]
Hey glad that’s worked out. Thanks for the update 👍🏻
