### ISSUE TITLE
How to require activerecord-import?

### ISSUE THREAD

**Issue by gerrywastaken** [zdennis/activerecord-import#474]
When I set `require: false` in my Gemfile and instead do the following in a script

```ruby
require 'active_record'
require 'activerecord-import'
require 'activerecord-import/base'
require 'activerecord-import/import'
```

activerecord-import instead tries to do every insert as a single insert. What am I doing wrong here?

I can see that supports_import? is somehow being set to false and this is why it doesn't work, but I'm not sure why that would be the case.

**Comment by gerrywastaken** [comment]
Ok I think I worked it out. I should be doing this instead:

```ruby
require 'active_record'
require 'activerecord-import'
require 'active_support'
```

This is because things are only setup when active_support is loaded: https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import.rb#L3

Correct?

Should activerecord-import attempt this itself?

**Comment by gerrywastaken** [comment]
Ok so I have to load activerecord-import before active_record is loaded: https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import.rb#L3

I'm wondering if that should be added to the readme? There is discussion of how adapters need to be loaded, but not activerecord-import itself.

**Comment by gerrywastaken** [comment]
I wonder if a lot of people require activerecord-import after active record and then just assume it made no difference to their imports or that it's broken. Perhaps there should be some warning when activerecord_import thinks that the connection doesn't "support_import".

**Comment by jkowens** [comment]
@gerrywastaken I'd have to do some reading on ActiveSupport's lazy loading to better understand what is going on.

@amatsuda are you able to provide any insight and/or suggestions?

**Comment by jkowens** [comment]
@gerrywastaken in your script if you just do:

```
require 'active_record'
require 'activerecord-import'
```
Does that work?

**Comment by jkowens** [comment]
There is a wiki entry on how to require activerecord-import. I just want to make sure that it is accurate.

https://github.com/zdennis/activerecord-import/wiki/Requiring

**Comment by gerrywastaken** [comment]
> Does that work?

Nope, because the onload of active_record would have already been triggered and so this is this never run:
https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import.rb#L3

@jkowens

**Comment by gerrywastaken** [comment]
it would be better if there was just a call we could make to initialize activerecord-import at any time no matter the load order.

**Comment by jkowens** [comment]
So I did some testing and the following at the beginning of your script should do the trick:

```
require 'activerecord-import'
require 'activerecord-import/base'
ActiveRecord::Import.load_from_connection_pool(ActiveRecord::Base.connection_pool)
```
I updated the wiki, but I'll see about adding a method to simplify that initialization.

**Comment by gerrywastaken** [comment]
That's pretty helpful, thanks @jkowens jkowens!

**Comment by jkowens** [comment]
I committed some code to `master` that should let you just do:

```
require 'activerecord-import/base'
```
If you are able to test it out that would be great.

**Comment by jkowens** [comment]
Argh nm, it's not working how I expected...back to the drawing board 😕
