### ISSUE TITLE
import doesn't work when a model is single table inherited one

### ISSUE THREAD

**Issue by kazuki-st** [zdennis/activerecord-import#477]
I'm using Rails4.0.13 and activerecord-import-0.20.1.

When I try to bulk insert with Model.import method, it doesn't work.

import_without_validation_or_callbacks method in import.rb
`unless scope_columns.blank?`
`scope_columns.zip(scope_values).each do |name, value|`
     `  name_as_sym = name.to_sym`
     `next if column_names.include?(name_as_sym)`
    ` is_sti = (name_as_sym == inheritance_column.to_sym && self < base_class)`
   `  value = value.first if is_sti`
     `column_names << name_as_sym`
     `array_of_attributes.each { |attrs| attrs << value }`
` end`
`end`

In this code,  name is a column name and value is literally a value.

when the value is a name of model and type is a String.So value.first gets the first character of the model name. 
example: "MyModel".first => "M"

That 's why this method doesn't work for my environment.
Any solution available?

**Comment by jkowens** [comment]
@kazuki-st can you share what the scope is defined as that this is failing on?

**Comment by jkowens** [comment]
I think I have a fix, I'm just not sure why there are possibly array and string values.

**Comment by kazuki-st** [comment]
@jkowens 
I don't get what the scope means on this context.

I have just confirmed it. Thanks.

**Comment by jkowens** [comment]
@kazuki-st yeah nevermind that comment. I realized later that AR must provide the inheritance column (usually type) as a scope attribute by default for STI models.

**Comment by jkowens** [comment]
This fix has been released in v0.21.0 🎉
