### ISSUE TITLE
Error in mysql_adapter.rb, line 23 - summing bytes in string returns concatenated string

### ISSUE THREAD

**Issue by sandymacpherson** [zdennis/activerecord-import#484]
I've been using this gem for a while now without a problem, but suddenly today it is failing.

The problem is line 23, where it attempts to do this:
`values_in_bytes = values.sum(&:bytesize)`

`values` is an array of strings, and the expression `values.sum(&:bytesize)` simply returns one big concatenated string, rather than the total number of bytes. I've tested this in Ruby 2.3 and 2.3.5.

This fails a bit later when this "number" is added to others, giving a "Coercing string to FixNum" exception.

**Comment by jkowens** [comment]
Are you saying you upgraded to a newer version of activerecord-import and it started failing? As far as I can tell that code dates back about 5 years to v0.4.0.

**Comment by sandymacpherson** [comment]
No - I noticed that as well so I'm almost certain it isn't this gem causing the issue. But it's very strange - I opened a rails console with `rails c` and tried some test code doing the same thing and got the same concatenated string output. Is there a particular dependency in this gem which I've perhaps not got right locally? 

From the Rails docs on `sum`, they say that `payments.sum(&:price)` is shorthand for `payments.inject(0) { |sum, p| sum + p.price }` but these two statements give me different results when applied to a string array. For example:

`x = ["One", "Two"]
x.sum(&:size) # = "OneTwo"
x.inject(0) { |sum, p| sum + p.size } # = 6
`

I'm baffled.

**Comment by jkowens** [comment]
Hmm that is very strange. I have to think that `Array#sum` is getting monkey patched in your app by some other code or gem.

**Comment by sandymacpherson** [comment]
Perhaps so. I'll investigate it as this is certainly not your fault! Thanks nevertheless.

**Comment by sandymacpherson** [comment]
You were right - it's the 'statsample' gem that is monkey patching it. Sadly, I cannot do without this gem... might have to fork it and fix it. Urgh.
