### ISSUE TITLE
How to add extra SQL to the import method?

### ISSUE THREAD

**Issue by thiagofm** [zdennis/activerecord-import#485]
I want to experiment to add 'SET LOCAL synchronous_commit = off' so my imports runs faster as we don't care about losing it as they are a process that we can run on demand.

Is there an easy way to do it?

**Comment by zdennis** [comment]
Can you do this thru ActiveRecord's connection before you run the import? E.g.

```ruby
ActiveRecord::Base.connection.execute "SET LOCAL synchronous_commit = off"
YourModel.import(...)
ActiveRecord::Base.connection.execute "SET LOCAL synchronous_commit = on"
```

**Comment by jkowens** [comment]
I think `SET LOCAL` only applies to the current transaction, so this may work:

```
YourModel.transaction do
  ActiveRecord::Base.connection.execute "SET LOCAL synchronous_commit TO OFF"
  YourModel.import(...)
end
```

**Comment by jkowens** [comment]
Closing for now. Feel free to follow up if these don't work.
