### ISSUE TITLE
NoMethodError: undefined method `=' for && NoMethodError: undefined method `type_cast' for nil:NilClass 

### ISSUE THREAD

**Issue by meetme2meat** [zdennis/activerecord-import#49]
I dont know I how to put this forward when I started build the application the code was working fine but some how now it seem to drop me with the following 2 error
1. NoMethodError: undefined method `=' 
2. NoMethodError: undefined method `type_cast' for nil:NilClass (is used with validate => false)

Here the code 

<p><code>PartPriceRecord.import(a1,b1)</code></p>

here is a1 and b1 value 

>  a1 = ["supplier_id", "part_number", "part_description", "core_indicator", "part_price", "core_price", "fleet_price", "distributor_price", :basic_file_id]
> 
> b1 = [["Supplier0", "PartNumber0", "LoremIpsums", "Y", "1300", "1400", "12", "10", 7], ["Supplier1", "PartNumber1", "Loremipsum", nil, "10", "1300", "1400", "12", "10", 7], ["Supplier2", "PartNumber2", "Loremipsum", nil, "11", "1300", "1400", "12", "10", 7], ["Supplier3", "PartNumber3", "Loremipsum", nil, "12", "1300", "1400", "12", "10", 7], ["Supplier4", "PartNumber4", "Loremipsum", nil, "13", "1300", "1400", "12", "10", 7], ["Supplier5", "PartNumber5", "Loremipsum", "Y", "14", "1300", "1400", "12", "10", 7]]
>  => [["Supplier0", "PartNumber0", "LoremIpsums", "Y", "1300", "1400", "12", "10", 7], ["Supplier1", "PartNumber1", "Loremipsum", nil, "10", "1300", "1400", "12", "10", 7], ["Supplier2", "PartNumber2", "Loremipsum", nil, "11", "1300", "1400", "12", "10", 7], ["Supplier3", "PartNumber3", "Loremipsum", nil, "12", "1300", "1400", "12", "10", 7], ["Supplier4", "PartNumber4", "Loremipsum", nil, "13", "1300", "1400", "12", "10", 7], ["Supplier5", "PartNumber5", "Loremipsum", "Y", "14", "1300", "1400", "12", "10", 7]] 

Here are **PartPriceRecord Attributes**

> ```
>  t.string :supplier_id
> t.string :part_number
> t.text :part_description
> t.string :core_indicator
>  t.float :part_price
> t.float :core_price
>  t.float :fleet_price
>  t.float :distributor_price
>  t.integer :basic_file_id
>  t.timestamps(update_at,created_at)
> ```

There **isn't an Active Validation for now**

Also when I decide to run the below code like **ruby console** something like this

<p><code>PartPriceRecord.import(a1,[b1[0]])</code></p>

mport was successful and a **single** record dumped in database

but soon after that I did this

<p><code>PartPriceRecord.import(a1,b1)</code></p>

I see the getting inserted in the database i.e **6** which is the **total count in b1** 

I can attach the screenshot if your interested

**Comment by christoandrew** [comment]
Also try checking the permitted parameters in the controller.
