### ISSUE TITLE
Import validations

### ISSUE THREAD

**Issue by acrogenesis** [zdennis/activerecord-import#491]
It's not entirely clear to me if validations are run when using `import` the wiki says
```
ActiveRecord callbacks related to creating, updating, or destroying records will NOT be called when calling the import method. This is because it is mass importing rows of data and doesn't necessarily have access to in-memory ActiveRecord objects.
```
If the data are ActiveRecord objects do they run? Or I need to use
```
run_callbacks(:save) { false }
run_callbacks(:create) { false }
```

And if I run the callbacks manually will only the objects that validate be created or will all fail the be created if one object doesn't pass the validation.

**Comment by jkowens** [comment]
Validations run by default on import and all valid objects are inserted into the database. The wiki is referring to other callbacks listed in the linked docs. Although, I do think `before_validation` and `after_validation` callbacks are run.
