### ISSUE TITLE
Update Timestamps Only If Record Changes?

### ISSUE THREAD

**Issue by MattMencel** [zdennis/activerecord-import#493]
I'm importing CSV data that may not have actually changed since the last import.  When I run the import, it sets the updated_at timestamp field regardless of whether there was actually a change to the record.  Is it possible to only update the timestamp if the attributes in the record actually changed?

This is my code that does the import...
`Person.import p_cols, p_vals, on_duplicate_key_update: p_cols`

**Comment by MattMencel** [comment]
I may have to make a change to the `updated_at` column in the DB to this?

`updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW()`

And then NOT set it during the ActiveRecord import using `:timestamps => false`. 

Then ActiveRecord won't update that timestamp during the import, but if a record changes in the database during the import, mysql will update that timestamp for me.

At least I think that's how it should work.  If anyone has any other thoughts about this let me know.

**Comment by MattMencel** [comment]
Yes....so I believe this is working the way I anticipated.  I updated my columns like so....

```
ALTER TABLE people MODIFY `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

> describe people;
+-------------+--------------+------+-----+---------------------+-------------------------------+
| Field       | Type         | Null | Key | Default             | Extra                         |
+-------------+--------------+------+-----+---------------------+-------------------------------+
...
| created_at  | datetime     | NO   |     | current_timestamp() |                               |
| updated_at  | datetime     | NO   |     | current_timestamp() | on update current_timestamp() |
+-------------+--------------+------+-----+---------------------+-------------------------------+
```

Then in my import...
`Person.import p_cols, p_vals, on_duplicate_key_update: p_cols, timestamps: false`

If the AR import doesn't update any attributes in a row, updated_at remains what it was.  If an attribute changes during the import, MySQL triggers the updated_at column.

Unless someone thinks there is a better way I'm going to go with that solution.

**Comment by jkowens** [comment]
This definitely seems like your best option with a MySQL database.

**Comment by falak** [comment]
If you are importing an array of records then before calling import on collection check for each record if its new or changed.
`records.select {|x| x if x.new_record? || x.changed?}`
