### ISSUE TITLE
Regression with v0.22 when importing associations in recursive mode in Rails 5.0 or 5.1

### ISSUE THREAD

**Issue by EtienneDepaulis** [zdennis/activerecord-import#495]
Hello guys,

when trying to update activerecord-import from `0.21` to `0.22` we noticed an error with our recursive imports on polymorphic associations.

I checked the specs you have on this topic (https://github.com/zdennis/activerecord-import/blob/master/test/support/shared_examples/recursive_import.rb#L36) and clearly everything seems fine. I also checked #489 

We tried different syntaxes but we still get the same error. Here is a simplified version of our code : 

```ruby
class Identifier < ApplicationRecord
  belongs_to :parentable, polymorphic: true
end

class Practitioner < ApplicationRecord
  has_many :identifiers, as: :parentable
end

class Importer
  def call
    practitioners = []

    practitioner = Practitioner.new # with valid attributes
    practitioner.identifiers.build # with valid attributes

    result = Practitioner.import([practitioner], recursive: true)

    result.failed_instances.each do |instance|
      instance.identifiers.each do |identifier|
        ap identifier.errors # => @messages={:parentable=>["required"]}
      end
     end
  end
end
```

The errors are located in the children (identifiers) and they always tell us that their "parent" is missing.

We also tried the following syntaxe to match the spec syntaxe but without any improvements: 
```ruby
practitioner = Practitioner.new # with valid attributes
identifier = Indentifier.new # with valid attributes

practitioner.identifiers << [identifier]

result = Practitioner.import([practitioner], recursive: true)
```
We would be happy to help with this issue
Any ideas of what we could be doing wrong ?
Thanks for your help
cc @jkowens

PS : if we set `validate: false` option on the `import` method, everything works perfectly : both parent and children are imported and valid

**Comment by jkowens** [comment]
Do you happen to be using ActiveRecord 5? I believe it now validates `belongs_to` relationships by default. Combining that with the tweak we made to validations for recursive imports is probably why you are seeing that issue. See https://github.com/rails/rails/issues/29781. From what I've read it looks like this is a known bug in Rails.

For now try adding `optional: true` to the relationship:

```
class Identifier < ApplicationRecord
  belongs_to :parentable, polymorphic: true, optional: true
end
```

**Comment by jkowens** [comment]
It looks like Rails 5.2 will possibly fix this issue: https://github.com/rails/rails/pull/28808. That PR also seems to suggest that instead of adding `optional: true` you can manually specify `inverse_of` to resolve the issue as well.

**Comment by jkowens** [comment]
After reviewing the specs you mentioned, I'm not sure why they pass and your examples fail. Very strange. Keep me posted if you find anything more!

**Comment by mtparet** [comment]
Ok I found some answers, with Rails 5 `belongs_to` relation are required by default. But this setting is done through configuration in Railties https://github.com/rails/rails/blob/71a392c465e58113d35121f0fec300599624cc6b/railties/lib/rails/application/configuration.rb#L74 so using directly active_record will not set this option to `belongs_to` relation.

The specs of `activerecord-import` works well for `active_record` but does not for Rails as the setting `belongs_to_required_by_default` is not set to true as it is in Rails. (I tried but lot of tests are failing )

**Comment by mtparet** [comment]
Following Rails issue template, see the following gist which shows that validation of children association does not work with polymorphic relation https://gist.github.com/mtparet/2873e82403678286c394dbba0aac60fe

ps: I work in the same firm as @EtienneDepaulis

**Comment by jkowens** [comment]
@mtparet wow thanks for the excellent detective work! The test script you put together was really helpful as well. Using your script I was able to confirm that explicitly setting `inverse_of` fixes the issue.

```
class Post < ActiveRecord::Base
  has_many :comments, as: :attachable, inverse_of: :attachable
end

class Comment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true, inverse_of: :comments
end
```

If I understand correctly, doing so won't be necessary for polymorphic associations with the Rails 5.2 release. I think we can close this issue here since what happened is a fix to validations in #489 has really just exposed a Rails issue.

**Comment by jkowens** [comment]
@EtienneDepaulis @mtparet have you been able to get the import working by adding the `inverse_of` argument?

Apparently it really only needs to be added to the `Post` model for the test to pass:

```
class Post < ActiveRecord::Base
  has_many :comments, as: :attachable, inverse_of: :attachable
end
```

**Comment by jkowens** [comment]
I added a note to the changelog for v0.22 about this requirement, so I'm going to close this issue. Let me know if anything more needs to be done. Thanks again for the help diagnosing this issue. 👏
