### ISSUE TITLE
on_duplicate_key_update all fields

### ISSUE THREAD

**Issue by itay-grudev** [zdennis/activerecord-import#496]
Is there a way to update all fields in case of duplicates? Something like:

```ruby
Book.import books, on_duplicate_key_update: :all
```

**Comment by itay-grudev** [comment]
Even better would be all fields except a given list. I don't know if there is native support for this, but it can be easily accomplished as we have the database schema.

**Comment by jkowens** [comment]
This is an interesting idea. There currently isn't an option for this, but it's not a hard thing to calculate before import:

```
columns = Book.column_names - ["id"]
Book.import books, on_duplicate_key_update: columns
```
Figuring out a syntax for these options might be the tricky part. We're trying to keep it similar between MySQL and Postgres for basic scenarios. That being the case adding an `:all` option might be the simplest path, but I'm open to discussion.

**Comment by aadityataparia** [comment]
+1
