### ISSUE TITLE
How to disable timestamps just for some specific model in associations tree if recursive option enabled?

### ISSUE THREAD

**Issue by pilgunboris** [zdennis/activerecord-import#499]
Hello!
I'm working on importing events, which already have some created_at/updated_at fields in csv file which I must use. So for `Event` model I need to set `timestamps: false`. 
However, `Event` model has_many & has_one some other associations and all of them must be imported with correct automatical timestamps. 

So I'm looking for options like this: 
```Ruby
# to set auto-timestamps just to Events & Permissions but ignore for all the others associations in the tree:
Event.import @events, recursive: true, validate: false, timestamps: { only: [Event, Permission] } 

# to set auto-timestamps to all associations in the tree excluding Events & Permissions:
Event.import @events, recursive: true, validate: false, timestamps: { except: [Event, Permission] } 
```

Is there some workaround to achieve this?

**Comment by jkowens** [comment]
Not sure about this, but if you set `timestamps: false` and then manually set created_at/updated_at fields with either a value from csv or `Time.now` on every object I think that might work.

**Comment by pilgunboris** [comment]
Ok, here is my solution in case if someone has a similar issue.

My Event model has a lot of complex associations and some of them shared with other resources so it is not useful to set timestamps everywhere manually. 
Instead, I collected all timestamps before importing Events and then after importing Events with associations just set original timestamps to `@events` collection and updated them:
```Ruby
Event.import @events, 
      validate: false,
      recursive: false,
      timestamps: false,
      on_duplicate_key_update: { conflict_target: [:id], columns: [:updated_at, :created_at] }
```

Although this is an extra step it works fine for me.

**Comment by jkowens** [comment]
Thanks for following up with your workaround. I believe only `:updated_at` would need to be updated on duplicate key. Even with `timestamps` enabled, `created_at` is only populated if the field is `nil`.

**Comment by pilgunboris** [comment]
@jkowens thanks for your last comment, it helped me a lot. I needed to set the only created_at actually (updated_at I did in addition), but I just didn't expect mentioned behavior even to try it. 
IMO it would be good to mention this somewhere on wiki pages as well since it might be useful for someone else in cases like described here.

**Comment by jkowens** [comment]
If you can update the timestamps page in the wiki, that would be awesome. I hope one day most of the wiki info is moved into a comprehensive README.

**Comment by pilgunboris** [comment]
@jkowens sure, I've just updated it - https://github.com/zdennis/activerecord-import/wiki/Note:-ActiveRecord-Timestamps 
However, since I'm not English native speaker could you please check if everything is clear there :smiley:
