### ISSUE TITLE
Attributes set in before_validation ignored

### ISSUE THREAD

**Issue by SirRawlins** [zdennis/activerecord-import#510]
Morning Folks,

I am using activerecord-import to import a bunch of AR models. One of my models uses the `before_validation` hook to set an attribute on the model.

```ruby
before_validation :persist_timeline_state

private

    def persist_timeline_state
        write_attribute(:timeline_state, determine_timeline_state)
    end
```

Ordinarily when calling `save!` on the model this works as expected, however active-record-import doesn't appear to spot the new attribute value, and raises a NullConstraint error when trying to run the insert.

If I invoke the `persist_timeline_state` method manually while building each instance before running the `import!` method everything works fine.

Debugging shows that the `persist_timeline_state` is being run by `import!`, but it just seems that the newly updated attribute isn't used when running the insert.

**Comment by jkowens** [comment]
This is an interesting issue. AR-Import builds out arrays of keys and values before it runs validations, so that is why you see this problem. This might be a tricky one to resolve, so if you need a work around, you could probably do something like this:

```
books.each do |book|
  book.run_callbacks(:validate) { false }
end
Book.import(books)
```

**Comment by zdennis** [comment]
I don't know the context behind why you're writing attributes during validations so it may all be very well and good. In case it helps us think of possible options for you or changes for activerecord-import I'd like to ask: Why are you writing attributes during the validation process?

**Comment by SirRawlins** [comment]
Thanks for the input folks.

@jkowens that workaround is essentially what I'm doing right now, it works just fine.

@zdennis the attribute in question used to be "virtual", it's never set by the user, but calculated from other attributes/associations on the model. However, it's helpful to query against so I use the hook to persist the value to the DB. Doing this pre-validation to sanity-check the data before it goes in made sense to me.

I now understand the reason behind this behaviour, however, it felt slightly unexpected, as I could see the before_validation hooks were running, but the data then being submitted to the database was stale.

Is there any reason the serialization to the array of keys happens before validation, rather than after?

**Comment by jkowens** [comment]
Since we also support importing arrays of arrays and arrays of hashes, the data gets normalized internally so we can send it down the same path for generating insert statements.

**Comment by jkowens** [comment]
@SirRawlins I've merged an update into master that should resolve this issue. If you can, it would be awesome if you could test out the latest code before I cut a release.

**Comment by jkowens** [comment]
I should mention that this only applies to importing AR models. Attributes set in before_validation will still be ignored when importing arrays of arrays or arrays of hashes.
