### ISSUE TITLE
i set validate: true，but not execute the validates

### ISSUE THREAD

**Issue by 85636682** [zdennis/activerecord-import#519]
i set validate: true，but not execute the validates
```
def create
    showcards = []
    start_number = params[:start].to_i
    end_number = params[:end].to_i
    (start_number..end_number).each do |i|
      showcards << Showcard.new(:sn => i)
    end
    if Showcard.import showcards, validate: true
      redirect_to admin_showcards_path, notice: "生成成功！"
    else
      redirect_to admin_showcards_path, notice: "生成失败！"
    end
  end
```
```
class Showcard < ApplicationRecord
  validates :sn, presence: true
  validates :sn, uniqueness: true

  belongs_to :user, optional: true
end
```

**Comment by jkowens** [comment]
Uniqueness validations are skipped for performance, and other reasons. Is presence being validated?

**Comment by jkowens** [comment]
See: https://github.com/zdennis/activerecord-import/issues/430

**Comment by 85636682** [comment]
it's not work after i remove validates :sn, presence: true
i seen #430 but i can found the reason

**Comment by jkowens** [comment]
@85636682 presence is the only validation in that example that would be executed. Are you sure presence is not being validated?

**Comment by jkowens** [comment]
I'm closing for now, if you can provide more details we can reopen. This might be a good issue for StackOverflow.
