### ISSUE TITLE
Model callbacks not being called

### ISSUE THREAD

**Issue by sreid99** [zdennis/activerecord-import#52]
I've had some problem trying to get this gem to work with my app. Eventually I figured my models callbacks were not being called. Then I noticed in the source that import.rb that "It does not utilize the ActiveRecord::Callbacks during creation/modification while performing the import."

I think this should be mentioned in the wiki documentation.

Is there some way round this - other than not using activerecord-import, or modifying my model ? Could it be made optional, like validation ?

**Comment by adamkuipers** [comment]
"It works with validations because to run validations ahead of time doesn't depend on the result of the import."

Why not support the callbacks initiated before creation (`before_*`), which don't depend on the result of the insertion?
