### ISSUE TITLE
Bulk import array value

### ISSUE THREAD

**Issue by meddario** [zdennis/activerecord-import#520]
Hi,
when I try to import values to a PostgreSQL array column (`numeric[] default '{}'::numeric[]`), i get the error `can't quote Array`. I am using the `Model.import column_names, array_of_values, options` form.

Example data: `['col1', 'col2', [1.2, 2.3]]`

Is there a way to force activerecord-import to quote the array? (e.g. for Postgres the correct form is `'{1.2,2.3}'`)

Thanks in advance!

**Comment by jkowens** [comment]
Just out of curiosity, have you tried importing the data like this:

Example data: `['col1', 'col2', '{1.2, 2.3}']`

**Comment by meddario** [comment]
I found out that the column in the test database wasn't correctly migrated
for unrelated reasons, fixing the type to array solved the problem!

Il mar 5 giu 2018, 21:33 Jordan Owens <notifications@github.com> ha scritto:

**Comment by jkowens** [comment]
Cool, glad to hear it's working!
