### ISSUE TITLE
import should not try to import virtual/generated columns

### ISSUE THREAD

**Issue by dbourguignon** [zdennis/activerecord-import#521]
When trying to import into a model which contains a virtual column, the import try to import using all columns, including the virtual ones (generated), generating an error:

The column are created like
```ruby
t.virtual :payment_id, 
  as: "source_data->>'$.metadata.payment_id'", 
  type: :integer, 
  null: true, 
  stored: true
```
They are managed by the database (mysql in my case)

The error looks like:
`activerecord Mysql2::Error: The value specified for generated column in table`

The importer, when trying to import, should try to ignore the virtual columns.
Something like:
```ruby
MyModel.columns.reject(&:virtual?).map(&:name)
```
if the adapter support the virtual columns (there is a `supports_virtual_columns?`method)

As a workaround, I passed the list of column to update in my import.

WDYT?

**Comment by zdennis** [comment]
Thanks for the write-up @dbourguignon. This sounds like a missing feature of activerecord-import to ignore virtual columns. You just taught me something new. I have not used virtual columns in MySQL or MariaDb.

Would you like to contribute a PR for this functionality?

**Comment by zdennis** [comment]
@jkowens, WDYT?

**Comment by dbourguignon** [comment]
Thank you for your quick answer. I'll try to take some time to look if it's not too hard to do for me :)

**Comment by jkowens** [comment]
A PR would be fantastic!

**Comment by jkowens** [comment]
@dbourguignon are you able to test out my branch for PR #530? Hopefully it resolves this issue.

**Comment by dbourguignon** [comment]
@jkowens Hi thanks for this :)

I tested and got:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
from …/.rvm/gems/ruby-2.4.4@drivy-rails/bundler/gems/activerecord-import-ce45a901bf83/lib/activerecord-import/import.rb:519:in `reject'
```

I added some comment to the PR
