### ISSUE TITLE
Using recursive with hash objects

### ISSUE THREAD

**Issue by brianp** [zdennis/activerecord-import#522]
Hey Team!

I'm trying to use a little less memory when building objects because heroku is complaining about usage. Previously I was doing something like below (complexity removed), and utilizing recursive builds with AR objects:
```ruby
identifiers = [Identifier.new(foo: :bar), ...] #about 3000 records
identifiers.map { |i| i.sightings.build(cat: :dog) }
Identifier.import identifiers, recursive: true
```

Is there a special syntax to signify a field here isn't a real column, but expected recursive build? 
```ruby
identifiers = [ { foo: :bar, sightings: [{ cat: :dog }] }, ...]
Identifier.import identifiers
```

**Comment by jkowens** [comment]
Sorry, recursive import is currently only possible with AR objects.

**Comment by brianp** [comment]
Thanks for the reply!

Closing issue.
