### ISSUE TITLE
Support for makara_postgis adapter

### ISSUE THREAD

**Issue by chadwilken** [zdennis/activerecord-import#526]
I see you have support for postgres makara and postgis, but not makara_postgis. Would that be as simple as adding to [base.rb](https://github.com/zdennis/activerecord-import/blob/d80417ff97d7b536705a8f6a2adfcda40666b59c/lib/activerecord-import/base.rb#L13)?

**Comment by jkowens** [comment]
PR welcome btw 😃

**Comment by chadwilken** [comment]
I should be able to whip one up. I hit some issues with Makara so I took a
break on this endeavor for now. Still happy to contribute though.
-- 
*Chad Wilken*
1125 Aberdeen Avenue
Lincoln, NE 68512
(402) 405-7300
