### ISSUE TITLE
Upgraded from 0.22.0 to 0.24.0 : PG::OutOfMemory: ERROR: out of memory

### ISSUE THREAD

**Issue by ohaddahan** [zdennis/activerecord-import#532]
I started having many PG::OutOfMemory issues after the update.
I'm using `Model.import ... batch_size: 1000` in both versions.
No change in the code calling `import` or the size of data being stored.

**Comment by jkowens** [comment]
Thanks for the report! We’ll have to investigate.

**Comment by jkowens** [comment]
I reviewed the changes in v0.23.0 and v0.24.0 and I'm not seeing anything that would really affect memory usage. Any chance the size of your imports have just substantially grown recently?

**Comment by ohaddahan** [comment]
I reverted back, no `PG::OutOfMemory` since.
So I'm pretty sure. I tried looking into the two versions code too and didn't see anything suspicious.

**Comment by jkowens** [comment]
Can you test v0.23.0 to try to narrow it down to which of the two versions introduced the problem? Are you importing AR models, doing "recursive" import, etc?

**Comment by ohaddahan** [comment]
False alarm, I started getting these again with 0.22.0.
Now I need to figure out what happened, since the batch size didn't change.
