### ISSUE TITLE
has_many association with existing records

### ISSUE THREAD

**Issue by theodorosidmar** [zdennis/activerecord-import#535]
Hello there!

I have a model called `Pack` and a model called `Cromo`. I'm trying to import multiple packs and associate them with existing cromos (they have `pack_id: nil`). Is it possible?

```ruby
# pack.rb
class Pack < ActiveRecord::Base
  has_many :cromos, inverse_of: :pack
end
```

```ruby
# cromo.rb
class Cromo < ActiveRecord::Base
  belongs_to :pack, inverse_of: :packs
end
```

```ruby
# build_packs.rake
packs = []
while my_condition
  pack = Pack.new(column_one: 1, column_two: 2 created_at: Time.now, updated_at: Time.now)
  pack.cromos << cromos # cromos is an array of ids searched previously. Just like I do in other parts
  # decrement my_condition
end
Pack.import([:column_one, :column_two, :created_at, :updated_at], packs, recursive: true) if packs.length > 0
```

I have also tried with `cromos` not being an array and being an `ActiveRecord` but it didn't work out either. Is there anyway I could do this? Am i doing something wrong?

Thank you.

**Comment by jkowens** [comment]
Hi! So the recursive option only works with postgresql databases, can you confirm that is what you are using?

**Comment by theodorosidmar** [comment]
Oh, sorry for that. Yes, I am using postgresql.

**Comment by jkowens** [comment]
I just realized you said you are trying to import existing cromo records. To do this you'd have to make use of the `on_duplicate_key_update` option because my guess is that you are getting an error right now on import.

Something like this might work:

```
# build_packs.rake
packs = []
while my_condition
  pack = Pack.new(column_one: 1, column_two: 2 created_at: Time.now, updated_at: Time.now)
  pack.cromos << cromos # cromos is an array of ids searched previously. Just like I do in other parts
  # decrement my_condition
end

if packs.length > 0
  Pack.import(packs)
  Cromo.import(packs.map(&:cromos).flatten, on_duplicate_key_update: [:pack_id])
end
```

**Comment by theodorosidmar** [comment]
Thank you for your help, @jkowens!

I've just got:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "cromos_pkey"
DETAIL:  Key (id)=(1675440) already exists.
: INSERT INTO "cromos" (*all_columns_including_pack_id) VALUES (*values_not_including_pack_id) RETURNING "id"

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "cromos_pkey"
DETAIL:  Key (id)=(1675440) already exists.
```

I could import `packs` normally. But they didn't have `cromos`. It seems it is trying to `INSERT` cromos, when I would only like to update their `pack_id`. Just like when I do `pack.cromos << Cromo.find(1)` in other parts.

Anyway, I did this:
```ruby
if packs.length > 0
  Pack.import([:column_one, :column_two, :created_at, :updated_at], packs)
  Cromo.import(packs.map(&:cromos).flatten, on_duplicate_key_update: [:pack_id])
end
```

My loop stayed the same. `pack = Pack.new(column_one: 1, column_two: 2 created_at: Time.now, updated_at: Time.now)`, `pack.cromos << cromos` (array of ids) and `packs.push(pack)`.

**Comment by jkowens** [comment]
Are you using postgresql 9.5 or later? That is required to have `on_duplicate_key_update` support.

**Comment by theodorosidmar** [comment]
```bash
$ psql --version
psql (PostgreSQL) 9.5.13
```

```sql
SELECT version();
PostgreSQL 9.6.6
```

**Comment by jkowens** [comment]
Ok so `on_duplicate_key_update` should work. Can you provide the logged insert statement that is generated for inserting into `cromos` as well as the full error message? Using a small sample would be helpful (preferably one or two records).

**Comment by theodorosidmar** [comment]
```ruby
# build_packs.rake
cromos_to_be_packed = Cromo.unpacked.select(:id, :code).shuffle
# scope :unpacked, -> { where(pack_id: nil) }
packs = []

while some_stuffs
  cromos = cromos_to_be_packed.uniq { |c| c.code }.take(5)
  pack = Pack.new(cromo_type: 1, public_id: SecureRandom.uuid, created_at: Time.now, updated_at: Time.now)
  pack.cromos << cromos
  packs.push(pack) 
  # then remove cromos from cromos_to_be_packed
  # decrement some_stuffs
end

if packs.length > 0
  Pack.import([:cromo_type, :public_id, :created_at, :updated_at], packs)
  Cromo.import(packs.map(&:cromos).flatten, on_duplicate_key_update: [:pack_id])
end
```

```ruby
# pack.rb
class Pack < ActiveRecord::Base
  has_many :cromos, inverse_of: :pack
end
```

```ruby
# cromo.rb
class Cromo < ActiveRecord::Base
  belongs_to :pack, inverse_of: :packs
end
```

Error:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "cromos_pkey"
DETAIL:  Key (id)=(1729292) already exists.
: INSERT INTO "cromos" ("id","user_id","public_id","pack_id","cromo_type","code","image","created_at","updated_at","cromable_id","cromable_type","sticked") VALUES (1729292,NULL,NULL,NULL,NULL,'D157',NULL,'2018-07-19 16:19:48.795679','2018-07-19 16:19:48.795679',NULL,NULL,NULL) RETURNING "id"
/Users/theodoro/Workspace/server/lib/tasks/build_packs.rake:39:in `block (2 levels) in <top (required)>'
/Users/theodoro/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/Users/theodoro/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "cromos_pkey"
DETAIL:  Key (id)=(1729292) already exists.
/Users/theodoro/Workspace/server/lib/tasks/build_packs.rake:39:in `block (2 levels) in <top (required)>'
/Users/theodoro/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/Users/theodoro/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => packs:build_for_digital
(See full trace by running task with --trace)
```

Am I missing anything?

**Comment by jkowens** [comment]
For some reason the `on_duplicate_key_update` option is not being used. At the end of the insert statement you should see an `ON CONFLICT DO UPDATE` clause.

I would fire up a rails console and try this:

```
Cromo.connection.supports_on_duplicate_key_update?
```
That should return true.

**Comment by jkowens** [comment]
If that returns false, run this and report the output:

```
Cromo.connection.send(:postgresql_version)
```

**Comment by theodorosidmar** [comment]
```bash
$ Cromo.connection.supports_on_duplicate_key_update?
NoMethodError (undefined method `supports_on_duplicate_key_update?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007ff7779f0260>)
Did you mean?  supports_pgcrypto_uuid?

$ Cromo.connection.send(:postgresql_version)
=> 90606
```

**Comment by jkowens** [comment]
Do you have an old version of `activerecord-import` installed? It has be be newer than v0.11.0. I would recommend the latest version of course.

**Comment by theodorosidmar** [comment]
Only `v.0.25.0` 😕

**Comment by jkowens** [comment]
Strange, the connection adapter should definitely respond to `supports_on_duplicate_key_update?` then.

**Comment by jkowens** [comment]
Can you share your Gemfile?

**Comment by theodorosidmar** [comment]
```ruby
source 'https://rubygems.org'

gem 'json', '2.1.0'
gem 'sinatra', '2.0.1'
gem 'httparty', '0.16.2'
gem 'activerecord', '5.2.0'
gem 'pg', '1.0.0'
gem 'sinatra-activerecord', '2.0.13' # https://github.com/janko-m/sinatra-activerecord
gem 'puma', '3.11.4'
gem 'rake', '12.3.1'
gem 'awesome_nested_set', '3.1.4'
gem 'rbnacl-libsodium'
gem 'jwt', '2.1.0'
gem 'nokogiri', '1.8.2'
gem 'sinatra-config-file', '1.0'
gem 'tilt-jbuilder', '0.7.1', :require => 'sinatra/jbuilder'
gem 'pony', '1.12'
gem 'savon', '2.12.0'
gem 'delayed_job_active_record', '4.1.3'
gem 'daemons', '1.2.6'
gem 'shortener', '0.5.5'
gem 'bulk_insert', '1.6.0'
gem 'activerecord-import', '0.25.0'
gem 'awesome_print'
```

**Comment by jkowens** [comment]
I guess I shouldn't have assumed you were using Rails 😄 

I'm wondering if you need to add this to the beginning of your rake file:

```
require 'activerecord-import/base'
require 'activerecord-import/active_record/adapters/postgresql_adapter'
```

**Comment by theodorosidmar** [comment]
Well, the error stopped occurring what is good news. Although, cromos didn't get updated. I imported two packs to test (tested 3x) and checked `Pack.last.cromos` and it returned `[]`. `Pack.last` returned a `pack` record correctly. I also tried removing `inverse_of:` from both models, but nothing changed.

**Comment by jkowens** [comment]
Can you provide the latest insert statement sql for inserting into `cromos`? Are `pack_id` values are being provided for each cromo? If not you might want to inspect the cromos objects before import:

- do they have a pack object?
- is `pack_id` being populated?

**Comment by theodorosidmar** [comment]
I do not believe `cromos` are having their `pack_id` provided. In an insert statement I provided previously, the value `NULL` was going to `pack_id` column.

But, the question is:
When I want to update `cromo.pack_id` I can do:
```ruby
pack = Pack.create(...)
pack.cromos << Cromo.find(1)
pack.save!
```
Or, if I want to give cromos to a user:
```ruby
user = User.find(1)
user.cromos << Cromo.limit(5)
```
Or packs:
```ruby
user = User.find(1)
user.packs << Pack.limit(5)
```

So, in this case, I'm associating `cromos` to `packs` in my loop. After `pack = Pack.new(...)`, I do `pack.cromos << cromos`. Then, I import `packs` e `cromos` like you suggested.
```ruby
Pack.import([:cromo_type, :public_id, :created_at, :updated_at], packs)
Cromo.import(packs.map(&:cromos).flatten, on_duplicate_key_update: [:pack_id])
```

The fact now, I believe, is I do not know how to pass `pack_id` for these `cromos`.

**Comment by theodorosidmar** [comment]
I believe I do not have this id value set. In one of my attempts, I was using:
```ruby
Pack.import packs
```
I got error with the id column. It was something like "cannot set packs_id.nextval", "cannot insert id null", something like that. Then I started using columns I wanted to set value
```ruby
Pack.import([:column_one, :column_two, :created_at, :update_at], packs)
```
The error stopped and I can import packs perfectly now.

I am going to try your suggestion soon (tomorrow morning) and report the result. And also thank you for your time and support. I do really appreciate it.

**Comment by theodorosidmar** [comment]
Well, there's no more error going on. But `cromos` still are not getting updated. I also believe `cromo.pack_id` is not having its value set since I create and import `packs` without its `id`.
```ruby
Pack.new(cromo_type: Cromo.cromo_types[:digital], public_id: SecureRandom.uuid, created_at: Time.now, updated_at: Time.now)
```

Does it make any sense? How am I supposed to assign `pack_id` to `cromo`?

**Comment by jkowens** [comment]
After you import packs, AR-Import should take the returned ids and assigns an id to each pack model (for postgresql anyway). Can you inspect the pack objects after import to see if that is happening?

**Comment by theodorosidmar** [comment]
Hello again!

I just inspected `packs` array after `Pack.import()`. Here is the result:
```
"Packs inspect: [#<Pack id: 3, user_id: nil, public_id: \"a503d770-6e58-4520-9295-5ca99a029063\", cromo_type: \"digital\", created_at: \"2018-07-23 13:58:37\", updated_at: \"2018-07-23 13:58:37\", order_id: nil>, #<Pack id: 4, user_id: nil, public_id: \"4dd22499-267e-45e5-99bf-bf3b8a9b5d1d\", cromo_type: \"digital\", created_at: \"2018-07-23 13:58:37\", updated_at: \"2018-07-23 13:58:37\", order_id: nil>]"
 ```

It looks like `packs` model are just right. Although:
```bash
$ ap Pack.last.cromos
D, [2018-07-23T10:59:46.209790 #1434] DEBUG -- :   Pack Load (1.1ms)  SELECT  "packs".* FROM "packs" ORDER BY "packs"."id" DESC LIMIT $1  [["LIMIT", 1]]
D, [2018-07-23T10:59:46.228650 #1434] DEBUG -- :   Cromo Exists (1.1ms)  SELECT  1 AS one FROM "cromos" WHERE "cromos"."pack_id" = $1 LIMIT $2  [["pack_id", 4], ["LIMIT", 1]]
[]
=> nil
```

**Comment by theodorosidmar** [comment]
I found what was happening. When selecting `cromos`, I was not selecting `pack_id`. I just added `:pack_id` to `select` method. Anyway, it would not work out without your solution.
```ruby
Cromo.import(packs.map(&:cromos).flatten, on_duplicate_key_update: [:pack_id])
```

I do really appreciate it, @jkowens. Thank you very very much for your time and help. Saved my life.

**Comment by jkowens** [comment]
Glad to hear things worked out! 👍
