### ISSUE TITLE
mysql version 8.0.11 and Symfony 4 error “MySQL server has gone away”

### ISSUE THREAD

**Issue by Alexandremp** [zdennis/activerecord-import#539]
I' m using Symfony 4 and Mysql version is 8.0.11 and using a user instead of a root login and when i try to use the command `php bin/console make:migration` i get this error:

    In AbstractMySQLDriver.php line 126:                                                                                 
    An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away                                                                                

    In PDOConnection.php line 50:                                           
    SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     
    In PDOConnection.php line 46:                                                
    SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     
    In PDOConnection.php line 46: 
    PDO::__construct(): Unexpected server respose while doing caching_sha2 auth: 109  

Then i tried to search online and i found out that something went wrong with the MySQL variables `wait_timeout` and `max_allowed_packet` and had to change those variables on the file `/etc/mysql/my.cnf`, the problem is when i go edit that file i only find this: 

    # Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
    #
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is also distributed with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have included with MySQL.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html
    # * IMPORTANT: Additional settings that can override those from this file!
    #   The files must end with '.cnf', otherwise they'll be ignored.
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/

so then i tried to see a thread called "[Why is /etc/mysql/my.cnf EMPTY?](https://askubuntu.com/questions/699903/why-is-etc-mysql-my-cnf-empty)" and a user said to use one of these paths:

    /etc/mysql/conf.d/
    /etc/mysql/mysql.conf.d/
    /etc/mysql/mysql.conf.d/mysqld.cnf

and so i tried...
`/etc/mysql/conf.d/`:

    ## Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is also distributed with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have included with MySQL.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Client configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysql]

in the file `/etc/mysql/mysql.conf.d/`:

    # Copyright (c) 2014, 2017, Oracle and/or its affiliates. All rights reserved.
    #
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is also distributed with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have included with MySQL.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    log-error       = /var/log/mysql/error.log

and in the file `/etc/mysql/mysql.conf.d/mysqld.cnf`:

    # Copyright (c) 2014, 2017, Oracle and/or its affiliates. All rights reserved.
    #
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is also distributed with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have included with MySQL.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    log-error       = /var/log/mysql/error.log

and in any of these files i failed to find the MySQL variables `wait_timeout` and `max_allowed_packet`, so thanks in advance if someone could help me with this problem. :)

P.S:(i already runned this command `php bin/console make:migration` several times before this error and also created databases and went fine so its seems to not be an installation problem).

**Update:** it seems successfully changed the two variables `wait_timeout` and `max_allowed_packet` globally by adding to the three files the following 

    max_allowed_packet=1024M 
    wait_timeout=3000000

and then using this command `sudo service mysql restart`  
giving me this: 

    mysql> SHOW global VARIABLES LIKE "wait_timeout";
    +---------------+---------+
    | Variable_name | Value   |
    +---------------+---------+
    | wait_timeout  | 3000000 |
    +---------------+---------+
    1 row in set (0,00 sec)

    mysql> SHOW VARIABLES like 'max_allowed_packet';
    +--------------------+------------+
    | Variable_name      | Value      |
    +--------------------+------------+
    | max_allowed_packet | 1073741824 |
    +--------------------+------------+
    1 row in set (0,00 sec)

but still when i tried using this command `php bin/console make:migration` it gave me the same error has mentioned above this post, also tried to change the `wait_timeout` variable to 300 by the same method and it gave me the same result. :(

using this command `sudo vim /var/log/mysql/error.log` i get this:   

    2018-07-29T18:55:18.382164Z 0 [Warning] [MY-010909] [Server] /usr/sbin/mysqld: Forcing close of thread 8  user: 'alexandre'.
    2018-07-29T18:55:20.288756Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
    2018-07-29T18:55:20.642118Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 31833
    2018-07-29T18:55:21.704556Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
    2018-07-29T18:55:21.720385Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.11'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.

**Comment by jkowens** [comment]
This is a Ruby library. I think you might have the wrong project?

**Comment by zdennis** [comment]
@alexagranov, this is a MySQL specific connection issue. It is most likely a timeout issue where your program has not communicated with the server over a specified timeout period and MySQL has killed the connection.

For more information see the below MySQL link:

      https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

**Comment by alexagranov** [comment]
also wrong Alex :-) pinging @Alexandremp

**Comment by zdennis** [comment]
Sorry @alexagranov !

**Comment by zdennis** [comment]
@Alexandremp, it appears there is a workaround for this already documented for Symfony. Check this out: https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/299

**Comment by Alexandremp** [comment]
I' m sorry for posting in the wrong project, and thank you for your help :+1:
