### ISSUE TITLE
Support REPLACE and INSERT IGNORE

### ISSUE THREAD

**Issue by avit** [zdennis/activerecord-import#54]
The `:on_duplicate_key_update` option is fine when only parts of existing records need to change. It would be helpful to also support the native `REPLACE` syntax directly when the whole record needs to be replaced, and `INSERT IGNORE` when existing records should remain untouched.

Ideas for syntax?

`:on_duplicate_key => :ignore`

`:on_duplicate_key => :replace`

**Comment by octavpo** [comment]
I just found about the :ignore option, which is nice, but it still has an issue: when set to true the code still inserts an 'ON DUPLICATE KEY UPDATE' clause for the 'updated_at' field. I think it's clear it shouldn't. Not even sure which one takes precedence.

I see also that there's another option :on_duplicate_key_ignore for Postgres. I don't know Postgres, but isn't that the same behavior as the :ignore key for MySQL? If so it would be good if they used the same key.

Thanks.

**Comment by jkowens** [comment]
REPLACE is potentially dangerous and with ON DUPLICATE KEY support, I don't think there is a reason to introduce that functionality.

@octavpo :ignore does not apply to Postgres, it is MySQL only. For Postgres use `:on_duplicate_key_ignore`. Ideally `:on_duplicate_key_ignore` will one day be an alias for `:ignore` for MySQL.

**Comment by jkowens** [comment]
@octavpo the issue you mentioned with 'ON DUPLICATE KEY UPDATE' being included when :ignore option is used for MySQL will be fixed in the next release. It will also allow :ignore or :on_duplicate_key_ignore to be used interchangeably for MySQL, Postgres, and SQLite.
