### ISSUE TITLE
Update on duplicate except in special circumstance

### ISSUE THREAD

**Issue by brandoncc** [zdennis/activerecord-import#541]
I need to import 30k records, updating duplicates. That part is simple thanks to your documentation. The tricky thing is that when a specific column value is `"B"`, I need to only touch the timestamp but not update any of the columns. Is that possible?

**Comment by jkowens** [comment]
It might be, what database are you using? I’ll see what I can dig up.

**Comment by jkowens** [comment]
You can provide custom sql to the `on_duplicate_key_update` parameter. Check out the example in the wiki: https://github.com/zdennis/activerecord-import/wiki/On-Duplicate-Key-Update#using-custom-sql

I believe you could possibly put conditionals around all the values except timestamp so that they only get updated if the specific column value is not "B". For example, if the database is MySQL the following might work:

```
dup_clause = "subject = IF (VALUES(type) = 'B', subject, VALUES(subject)), \
              body = IF (VALUES(type) = 'B', body, VALUES(body)), \
              updated_at = VALUES(updated_at)"

Post.import posts, validate: false, on_duplicate_key_update: dup_clause
```

**Comment by brandoncc** [comment]
Sorry for the delayed answer. I am using postgres. I saw that I could use custom SQL but this is definitely helpful in me understanding how. Thanks for taking the time to look into it. If I find that it works for me I will respond here with whatever code I end up using.

**Comment by jkowens** [comment]
Sounds good 👍 

I know Postgres doesn't have an `IF` function, but maybe you could incorporate `CASE` statements.

**Comment by brandoncc** [comment]
It turns out you had built the perfect solution into the gem:

```
Diamond.import(
  cols,
  vals,
  validate: false,
  on_duplicate_key_update: {
    conflict_target: [:rapnet_diamond_id],
    condition: "diamonds.do_not_display != 'B'",
    columns: Diamond.column_names.reject { |name| %w[id created_at updated_at].include?(name) }
  }
)
```

This worked great. I would have liked to touch the other rows as well, but I ended up gathering their ids and using `update_all` on the collection in order to handle that in its own call too. This will take me from 30k+ db hits over the wire to under 10....so it is a massive improvement. Thanks for your awesome gem!

**Comment by jkowens** [comment]
Postgres FTW! Glad to hear you found a good solution, I totally forgot about the condition option.

**Comment by brandoncc** [comment]
I suppose I should have read the source before opening an issue and bothering you... 👎  Thanks again for getting me headed in the correct direction!

**Comment by jkowens** [comment]
Haha well hopefully one day we'll have comprehensive documentation for this gem. It's on our todo list 😄

**Comment by brandoncc** [comment]
Well, I'm back to square one as I just figured out that the solution I found actually makes the update not happen at all :-/

**Comment by brandoncc** [comment]
Looks like `CASE` is not allowed in the `SET` clause.

**Comment by brandoncc** [comment]
Okay, your original answer was the perfect solution. Thank you!

**Comment by jkowens** [comment]
Any thoughts as to why the `condition` expression isn't working?

**Comment by jkowens** [comment]
Ah thanks for the update, I would have missed that one as well!
