### ISSUE TITLE
MySql :on_duplicate_key_update enabled by default with timestamp columns

### ISSUE THREAD

**Issue by jimthrive** [zdennis/activerecord-import#548]
### Background

In the `MysqlAdapter` when `:timestamps` is set to `true` (which is default), and `:ignore` is set to `false` (also default) `options[:on_duplicate_key_update]` is set to `[updated_at]` (or whatever the updated_at timestamp column is called in your environment). This doesn't seem to be the case for Postgres.

### Effects
The main issue is that this allows duplicates in your import, even when you don't have options set for ignoring or updating on duplicates. 

### Steps to Reproduce
Using mysql, import something with duplicate keys (either via primary key, or unique index). You'll notice the `created_at` and `updated_at` have different timestamps for rows with the duplicate keys, and that the import succeeds. 

### Relevant Code

In `Import.add_special_rails_stamps()`:

```
if supports_on_duplicate_key_update? && action == :update
  connection.add_column_for_on_duplicate_key_update(column, options)
end
```

In `MysqlAdapter.add_column_for_on_duplicate_key_update()`:

```
def add_column_for_on_duplicate_key_update( column, options = {} ) # :nodoc:
  if options.include?(:on_duplicate_key_update)
    columns = options[:on_duplicate_key_update]
    case columns
    when Array then columns << column.to_sym unless columns.include?(column.to_sym)
    when Hash then columns[column.to_sym] = column.to_sym
    end
  elsif !options[:ignore] && !options[:on_duplicate_key_ignore]
    options[:on_duplicate_key_update] = [column.to_sym]
  end
end
```

### Suggested Fix
I'll submit a PR for this in a bit...

Change `MysqlAdapter.add_column_for_on_duplicate_key_update()` to only add columns if `options.include?(:on_duplicate_key_update) && !options[:ignore] && !options[:on_duplicate_key_ignore]`. 

It might be also be worth adding this check to `PostgreSQLAdapter` and cleaning up some of the mutex options, similar to what's been done in `PostgreSQLAdapter.post_sql_statements()`.

**Comment by jkowens** [comment]
@jimthrive I agree this is bizarre default behavior, but I think why we never removed it was because this could break applications that now depend on it to work this way. When `on_duplicate_key_update` support was added for Postgres and SQLite, this default behavior was not included.

To work around this there is the option to do `on_duplicate_key_update: false`. See: https://github.com/zdennis/activerecord-import/pull/137

I'm curious to get @zdennis's opinion on this PR. Would adding a note in the changelog about a breaking change be an acceptable way to communicate this update to default behavior for MySQL?

**Comment by zdennis** [comment]
Happy Friday @jkowens and @jimthrive,

I did a quick read of the above, but I'm not confident in my understanding so I wanted to communicate back to you: Are you saying when importing thru MySQL the `updated_at` column is being updated whenever `on_duplicate_key_update` is used regardless of if that column was specified by the caller OR that the `updated_at` column is being updated even when you don't specify `on_duplicate_key_update`? 

It sounds like you're expecting an error to be raised by trying to important a record with a duplicate primary/unique key but that somehow that's not happening. I want to make sure I understand what's happening.

If it helps, feel free to explain this to me like I'm five. I won't take offense. I've been hanging out with my six month old a bunch and I am aware my level of cognition has more recently been at the level of Word Party on Netflix.

**Comment by saiqulhaq** [comment]
so if I use MySQL, I don't have to make any changes to my code, right?

this is my code

``` Inventory.import(@inventories, on_duplicate_key_update: [:quantity_available])```

**Comment by jkowens** [comment]
@saiqulhaq yes that will continue to work.
