### ISSUE TITLE
Bulk insert is very slow

### ISSUE THREAD

**Issue by ruslan-ryzhkov** [zdennis/activerecord-import#557]
I have been working on bulk inserting a bunch of records using this gem and I noticed that my bulk SQL INSERT statements are taking an unusually long time to complete. Consider the following example:

 I have a `Category` model with a `name` field that is required to be unique. In the table, I have `name`, `created_at` and `updated_at` columns with a unique index on the `name` field. I also have a uniqueness validation inside the `Category` model for the `name` field. The categories are structured as an array of 7 hashes like this:
   ```ruby
   categories = [ { name: 'Category 1' }, { name: 'Category 2' }, { name: 'Category 3' }, { name: 'Category 4' }, { name: 'Category 5' }, { name: 'Category 6' }, { name: 'Category 7' } ]
   ```

I am then running the following line of code to insert these categories:
```ruby
Category.import categories, on_duplicate_key_ignore: true, validate: false
```

The bulk SQL INSERT statement logs this at around 435 milliseconds, which is really high to me. Other bulk SQL INSERT statements I have in the application that I'm working on take around 100 milliseconds, which is also high.

Here are my system specs:
OS: Windows 10
Rails version : 5.2
MySQL version: 8.0
activerecord-import version: 0.27.0

I am also running this application inside a Docker container (using Docker for Windows) if that makes any difference. Finally, I have confirmed that removing the unique DB index on the `name` field and the corresponding model validation made little to no difference in the bulk SQL INSERT statement time. Is there any indication of what may be causing the slowdown?

**Comment by jkowens** [comment]
Just to clarify, are you saying it takes 435ms to import 7 category records? That does seem rather slow. It sounds like it is just the the sql insert to MySQL that is taking that long and not the entire `import` call. Is that correct?

**Comment by ruslan-ryzhkov** [comment]
Yes, I was running my program in the rails console and the sql insert log showed that it was taking 435ms to import the 7 records yesterday. I ran it again today and here is what I see:
```
Category Create Many Without Validations Or Callbacks (183.9ms)  INSERT IGNORE INTO `categories` (`name`,`created_at`,`updated_at`) VALUES ('Category 1','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 2','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 3','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 4','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 5','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 6','2018-10-14 16:30:03','2018-10-14 16:30:03'),('Category 7','2018-10-14 16:30:03','2018-10-14 16:30:03')
``` 

For some unknown reason, the time has decreased down to 183.9ms. One more thing to mention is that the select queries I'm executing in the program using just plain ActiveRecord are very fast at around 0.5ms each. Only the bulk sql insert statements are being slow.

**Comment by jkowens** [comment]
How long does a single insert take?

**Comment by jkowens** [comment]
Found this:

https://stackoverflow.com/questions/12316122/mysql-very-slow-update-insert-delete-queries-hanging-on-query-end-step

Not sure if there’s anything there that might help.

**Comment by ruslan-ryzhkov** [comment]
Thank you. Setting `innodb_flush_log_at_trx_commit` to either 0 or 2 did improve overall performance but most of the bulk inserts still take around 50ms on average. I'll look into other potential improvements.

**Comment by jkowens** [comment]
I'm going to close this since this seems to be a hardware/server configuration issue. Please feel free to post updates here that might help others track down similar issues. Thanks!
