### ISSUE TITLE
catch error save activerecord-import

### ISSUE THREAD

**Issue by jjab2020** [zdennis/activerecord-import#558]
Hello,

Thank you for this great Rails Gem, but i have a question about how to catch errors of save .

Have a nive day

**Comment by jkowens** [comment]
Errors will be raised by the database adapter so it would look something like this

```
begin
  Book.import books
rescue => e
  # handle exception
end
```

**Comment by jkowens** [comment]
If you're asking how to check for records that fail validation you would do something like this:

```
result = Book.import books

# failed instances are activerecord models
# see: https://guides.rubyonrails.org/active_record_validations.html#working-with-validation-errors
result.failed_instances.each do |failure|
  # handle failure.errors
end
```

**Comment by jjab2020** [comment]
Hello,
Thank you very much  for this useful help I will try it 

😊

Have a nice day

**Comment by jkowens** [comment]
You're welcome, glad to help 😄
