### ISSUE TITLE
Calls for import is being made one by one in mysql

### ISSUE THREAD

**Issue by vaidhyanathan93** [zdennis/activerecord-import#561]
I used the Model.import with an array of model object. Rather than calling as bulk insert it is being called one by one. Allowed packet size is 4194304. 

For more details please have a look into the Attachment.

![bug](https://user-images.githubusercontent.com/3818495/47364799-c7abee80-d6f7-11e8-9f05-620bdee4e74a.png)

**Comment by jkowens** [comment]
Can you include the versions of ActiveRecord, ActiveRecord-Import, and MySQL that you are using?

**Comment by jkowens** [comment]
For some reason your connection adapter must be returning `false` for the method `supports_import?`.  Can you investigate to see if some other code is overriding that method?

See: https://github.com/zdennis/activerecord-import/blob/a63144b27ed7d945da26ce04a46f53ded518a23f/lib/activerecord-import/import.rb#L228

**Comment by vaidhyanathan93** [comment]
Thanks, @jkowens .

As mentioned, Some of our custom implementations are overriding this functionality and caused confusion. Resolved the same. 

Hence Closing this ticket.
