### ISSUE TITLE
on_duplicate_key_update

### ISSUE THREAD

**Issue by jjab2020** [zdennis/activerecord-import#562]
Hello friend,

Does on_duplicate_key_update  was compatible with oracle database if no any solution any help for updating many records   in one query

For example the exemple below  work in postgres database and rails what is the similar to make it work with oracle and rails

update test as t set
    column_a = c.column_a,
    column_c = c.column_c
from (values
    ('123', 1, '---'),
    ('345', 2, '+++')  
) as c(column_b, column_a, column_c) 
where c.column_b = t.column_b;

Many thanks 

Have a nice day

**Comment by jkowens** [comment]
Hi, I'm not sure I understand entirely. The oracle database is not supported by default. There is a gem that adds basic support for it, but it does not have `on_duplicate_key_update` functionality.

See: https://github.com/keeguon/activerecord-import-oracle_enhanced

**Comment by jkowens** [comment]
I would take a look at StackOverflow for ways to update on duplicate key (UPSERT) when using Oracle.

For example, see: https://stackoverflow.com/questions/237327/oracle-how-to-upsert-update-or-insert-into-a-table?noredirect=1&lq=1

or

**Comment by jjab2020** [comment]
Hi thank you very much for the help.

I will try and let you know. 

Have a nice day.
