### ISSUE TITLE
Why is columns option required to update in on_duplicate_key_update?

### ISSUE THREAD

**Issue by abinoda** [zdennis/activerecord-import#567]
Hello, thank you for this fantastic library. I wanted to report an issue with my developer experience. Please let me know if I'm doing something wrong!

Here's my table:

```ruby
create_table "github_repos", force: :cascade do |t|
  t.bigint "github_id"
  t.string "name"
  t.string "description"
  t.index ["github_id"], name: "unique_repos", unique: true
end
```

Here's the code I use to upsert:

```ruby
arr = [
  {github_id: 1, name: 'foo', description: 'hello'},
  {github_id: 1, name: 'bar', description: 'bye'}
]

# This does not update name and description ON CONFLICT
GithubRepo.import(arr, on_duplicate_key_update: { conflict_target: [:github_id] )

# This DOES update name and description ON CONFLICT
GithubRepo.import(arr, on_duplicate_key_update: {
  conflict_target: [:github_id], columns: [
    :name,
    :description
  ]
})
```

Why is the `columns` option necessary in order for `name` and `description` to get updated ON CONFLICT? It would be nice if the default behavior was to update all columns provided in the passed-in hashes/objects except for columns specified in`confict_target` of course. This seems like the most common use case and it is difficult to keep the `columns` array up-to-date and based on the array or objects being passed to `#import`.

Is there a reason this default behavior is not implemented? Or is it already? Let me know if I'm missing something.

**Comment by jkowens** [comment]
There is an option to update all columns:

```
GithubRepo.import(arr, on_duplicate_key_update: {
  conflict_target: [:github_id], columns: :all
})
```
When it comes to overwriting data, I think it's generally a better idea to be conservative by default and make sure it is explicitly decided upon.

**Comment by abinoda** [comment]
@jkowens Wow, how'd I miss that option! Thanks for the help. Agree that being conservative by default makes sense. Didn't know that option existed, I'm guessing that'll solve my issue.

**Comment by jkowens** [comment]
No worries, glad to hear that will work 👍
