### ISSUE TITLE
on_duplicate_key_update {columns: :all} updates conflicted columns

### ISSUE THREAD

**Issue by abinoda** [zdennis/activerecord-import#568]
Related to https://github.com/zdennis/activerecord-import/issues/567. I'm seeing that using the `{columns: :all}` option for `on_duplicate_key_update` results in the conflict target column(s) included in the `DO UPDATE` columns. In my case, the target columns have a composite index with a constraint so it does not make sense for either of those target columns to be updated ON CONFLICT. Is there a reason why this library attempts to update those columns? Should this behavior be removed? Or would it be useful if there were an option like `columns: :not_target` that updated all columns but excluded te ones specified in `conflict_target`?

The steps to reproduce are below:

```ruby
create_table "github_repos", force: :cascade do |t|
  t.bigint "org_id"
  t.bigint "github_id"
  t.string "name"
  t.string "description"
  t.index ["org_id", "github_id"], name: "unique_repos", unique: true
end

arr = [
  {org_id: 1, github_id: 1, name: 'foo', description: 'hello'}
]

GithubRepo.import(arr, on_duplicate_key_update: {
  conflict_target: [:org_id, :github_id],
  columns:         :all 
})
```

This results in the following query:
```sql
INSERT INTO "github_repos" ("org_id","github_id","name","description") VALUES (1,1,'foo','hello')
ON CONFLICT (org_id, github_id)
DO UPDATE SET "org_id"=EXCLUDED."org_id","github_id"=EXCLUDED."github_id","name"=EXCLUDED."name","description"=EXCLUDED."description"
RETURNING "id"
```

**Comment by abinoda** [comment]
I updated my write-up so please read it here on GitHub and not the email notification.

**Comment by zdennis** [comment]
@abinoda, is the problem here a potential performance one rather than data being incorrect?  E.g. writing a value to a column (or columns) that already have said value?

And can we confirm that PostgreSQL is indeed being writing values that are exactly the same as what are already stored? 

Or... am I missing something?

**Comment by abinoda** [comment]
@zdennis As far as I can tell the values are being written. Whether there is or is not any performance impact, or any other potential side effects, is not clear. Regardless I think it'd be nice to be able to exclude the target conflicts from the update, either as the default behavior or an additional option. What do you think?

**Comment by jkowens** [comment]
Part of the issue is that for MySQL we have no idea what columns are the conflicting column(s) (unless it is the designated primary key). This would need to be code specific to each database adapter.

For now a workaround you might use:

```
GithubRepo.import(arr, on_duplicate_key_update: {
  conflict_target: [:org_id, :github_id],
  columns: GithubRepo.column_names.map(&:to_sym) - [:id, :org_id, :github_id] 
})
```

**Comment by zdennis** [comment]
Good call @jkowens! and the workaround you've provided seems succinct and clear.

@abinoda, does what @jkowens posted work for you? 

With respect to including this... I'll defer to @jkowens for the call since he's been a much more active maintainer than myself. My 2 cents would be that we make sure the feature is warranted by verifying the assumption that it negatively affects performance and weigh that with the cost of complexity/maintenance over-time across different database adapters.  

Hope this helps.

**Comment by abinoda** [comment]
@zdennis @jkowens Yep, the suggestion by @jkowens works. I'll probably create a method in my base model like below. `upsert_keys` is a class method I use via https://github.com/jesjos/active_record_upsert.

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.bulk_upsert(arr)
    import(arr, on_duplicate_key_update: {
      conflict_target: upsert_keys,
      columns: column_names.map(&:to_sym) - primary_key.to_sym - upsert_keys
    })
  end
end
```

**Comment by abinoda** [comment]
> My 2 cents would be that we make sure the feature is warranted by verifying the assumption that it negatively affects performance

@zdennis @jkowens I am very interested in getting to the bottom of whether is any negative performance impact, or any other possible side effects of updating the ON CONFLICT keys in the DO UPDATE SET. Because if there isn't, I would just use the `{columns: :all}` option as-is.

**Comment by jkowens** [comment]
Thanks @abinoda, please report back with what you find. I'm very interested in learning the answer to those questions as well.

**Comment by abinoda** [comment]
@jkowens Working on it!

**Comment by jkowens** [comment]
Awesome thanks!

**Comment by abinoda** [comment]
https://github.com/abinoda/activerecord-import/blob/master/lib/activerecord-import/import.rb#L578-L588

**Comment by abinoda** [comment]
Based on this, an updated workaround might look like:

```ruby
arr = [
  {org_id: 1, github_id: 1, name: 'foo'}
]

conflict_target = [:org_id, :github_id]

GithubRepo.import(arr, on_duplicate_key_update: {
  conflict_target: conflict_target,
  columns:         arr.first.keys - conflict_target
})
```

**Comment by abinoda** [comment]
Did some research on the Postgres side. With Postgres's MVCC architecture, UPDATES to rows are implemented as new insertion and deletion of the old row. Based on this, it shouldn't matter whether the target columns are updated or not because a new row and index will be inserted either way.

There is an additional scenario I've looked into which is Postgres's HOT (Heap-only tuples) feature. Per the links below, this feature will `create a new physical heap tuple when inserting, and not a new index tuple, if and only if the update did not affect indexed columns`. I'm pretty sure that Postgres doesn't count the indexed columns as changed if the values are the same as before, but I'm verifying this to make sure that including the indexed columns in the update is still of no consequence.

https://wiki.postgresql.org/wiki/Index-only_scans#Interaction_with_HOT
https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/access/heap/README.HOT;hb=HEAD

**Comment by abinoda** [comment]
Oh, and I just saw that my StackExchange post received a great response that's far more comprehensive than my previous comment and answers the final piece: 
https://dba.stackexchange.com/questions/223231/performance-impact-of-updating-target-columns-with-same-values-on-conflict

Looks like `columns: all` is the winner!

**Comment by abinoda** [comment]
**_Here's the full response from StackExchange so it's logged here forever:_**

It seems to have no difference from performance perspective , assuming you have no triggers that runs only if certain columns are updated. 

The whole row is updated , or to be more Postgres specific (Postgres doesn't have in-place updates), the new tuple will be inserted, and the old one will be marked as dead .  From that regard it doesn't matter if actual change happens for only one column, or all of them , or neither .  You can check values of n_tup_upd, n_dead_tup  columns in `pg_stat_all_tables` - they both increase after each update . `n_dead_tup` will eventually get reset after performing `vacuum`. 

The only thing that might be negatively affected is HOT updates (no new index tuple if indexed column doesn't change value). HOT updates are explained in many places, the best one in my opinion is http://www.interdb.jp/pg/pgsql07.html . 

Testing HOT updates (done with Postgres 9.6, 10.4 and 10.5)


    --- setup
    -- useful extension for checking data and index pages
    create extension pageinspect; 
    -- dummy table  (varchar is used instead of text just to avoid any complication related to TOAST )
    create table test_update(test_update_id int not null , some_data varchar(50),constraint test_update_pkey primary key (test_update_id) );
    
    -- insert  2 rows
    insert into test_update (test_update_id, some_data) values (1, 'test1');
    insert into test_update (test_update_id, some_data) values (2, 'test2');
    
    --check table stats : 
    select relname ,n_tup_upd, n_dead_tup , n_tup_hot_upd  from pg_stat_all_tables where relname ='test_update';
     --(all zeroes) 
    -- check #rows in index :
    select * from bt_page_items('test_update_pkey',1) ;
    -- 2 rows
    
    ----------------------------------------------
    -- Test 1 . perform dummy update : 
    update  test_update set test_update_id = test_update_id , some_data = some_data;
    
    -- check tables stats again, 
    --n_tup_upd = n_dead_tup = n_tup_hot_upd  = 2 
    -- check index page again, results are the same - 2 rows
    
    -- Test 2 . real update non-key column , and dummy update of key column  :
    update  test_update set test_update_id = test_update_id , some_data = some_data||'_new';
    
    -- check tables stats again, 
    --n_tup_upd = n_dead_tup = n_tup_hot_upd  = 4 
    -- check index page again, results are the same - 2 rows
    
    -- Test 3 . real update non-key column , key column is not in the statement:
    update  test_update set some_data = some_data||'_new_2';
    
    -- check tables stats again, 
    --n_tup_upd = n_dead_tup = n_tup_hot_upd  = 6 
    -- check index page again, results are the same - 2 rows
    
    -- Test 4. Now do real update of key column :
    
    update  test_update set test_update_id = test_update_id+2;
    -- check tables stats again, 
    --n_tup_upd = n_dead_tup = 8, n_tup_hot_upd  = 6  (no HOT update this time)
    -- check index page again, now we see 4 rows



It appears that Postgres is smart enough to identify cases where indexed columns are not changed , and perform HOT updates; thus , there is no difference between having or not having key columns in update statement from performance point of view.  The only thing that matters it whether actual value changed. Surely, this behaviour is limited to B-Tree indexes.

**Comment by abinoda** [comment]
Based on all of this, it appears that `columns: :all` works fine and has no known consequences.

**Comment by jkowens** [comment]
Awesome. Great write up, thanks! 💯
