### ISSUE TITLE
Presence validation not causing import to fail

### ISSUE THREAD

**Issue by Rob117** [zdennis/activerecord-import#571]
Relevant code:

```
results = Flashcard.import cards_for_import, timestamps: false, on_duplicate_key_update: {
      conflict_target: %i[client_id user_id], columns: %i[created_at updated_at keyword_text
                                                          keyword_meaning example_usage keyword_locale
                                                          front_note back_note]
}
```

The model has a keyword_text cannot be blank presence validation:
`validates :user, :keyword_text, :client_id, :keyword_locale, :keyword_meaning, presence: true`

So, I have an array of objects to import that looks like this (some fields omitted, important part is that `keyword_text` is blank):

```
p cards_for_import
[#<Flashcard id: 1, user_id: 1,  keyword_text: "", keyword_meaning: "tabgo tego qui tepesco autem", 
example_usage: "Magnam qui magni. Debitis ut distinctio. Aut dolor...", created_at: "2018-11-26 02:21:58", 
updated_at: "2018-11-26 02:21:58", deleted_at: nil, client_id: 1543199098550>]
```

Problem is, calling `cards_for_import.first.valid?` returns false, but if I import the record **as is**, results returns:

`#<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=[1], results=[]>`

The card is then added to the database even though it actually violates a model's presence constraint, confirmed with `valid?` being false. I manually tried turning `validate: true on`, but no luck.

Is this intentional behavior?

My understanding is that it should be stored in failed_instances, not added regardless.

**Comment by Rob117** [comment]
@jkowens  Are those tests running with on_duplicate_key_update?

**Comment by jkowens** [comment]
Good question, I'll check into that.

**Comment by jkowens** [comment]
Yes, it worked as well. If you can help narrow down which options are at play here that would be helpful.

**Comment by Rob117** [comment]
Is there anything that could override those validations that could be set elsewhere that you can think of? It's odd to see object.valid? return false, but the import succeed.

**Comment by jkowens** [comment]
What's the result of:

```
cards_for_import.first.errors.inspect
```

**Comment by Rob117** [comment]
@jkowens 
```
"#<ActiveModel::Errors:0x00007fcd05a15cc8 @base=#<Flashcard id: 1, user_id: 1, 
deck_id: 1543483055895, keyword_text: \"\", 
keyword_meaning: \"tubineus voluptas et facere caput\",
example_usage: \"Sit tempore sed. Rerum praesentium optio. Laborios...\", 
keyword_locale: \"bqei0lyoah\", front_note: \"Aut maiores itaque expedita.\", 
back_note: \"Beatae tempore vitae in.\", created_at: \"2018-11-29 09:16:35\", 
updated_at: \"2018-11-29 09:16:35\", deleted_at: nil, client_id: 1543483115912>, @messages={:keyword_text=>[\"can't be blank\"]}, @details={:keyword_text=>[{:error=>:blank}]}>"
```

**Comment by jkowens** [comment]
Well it looks like it’s validating exactly as expected. I’m really not sure what would be happening on import.

**Comment by jkowens** [comment]
Maybe try adding all the gems in your projects Gemfile to the demo app to see if you can get it to reproduce your issue. That might help narrow down the source of the issue.

**Comment by Rob117** [comment]
Excellent idea! I'll try it and get back to you.

**Comment by timfsw** [comment]
I encountered the same problem. Import validation fails for association object.

``` ruby
class User < ActiveRecord::Base
  has_many :comments, class_name: 'UserComment', dependent: :destroy
end

class UserComment < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :comment, presence: true
end

user_comments = [
  UserComment.new(user_id: 1, comment: 'Test'),
  UserComment.new(user_id: nil, comment: 'Test')
]

import = UserComment.import user_comments, validate: true
```

If i add `validates :user_id, presence: true` the import works like expected and validates correct. With the version above i get no errors when i'm using `import`.

**Comment by jkowens** [comment]
@timfsw that is a different issue I believe. See: https://github.com/zdennis/activerecord-import/issues/518

We purposely prevented validating belongs_to associations because it was executing a sql query for every record imported to make sure the association exists in the database. This came about because Rails 5 validates presence of belongs_to associations by default now. I'm not exactly sure how to proceed with that one, I'll need to think on it. Any input from others is appreciated.

**Comment by Rob117** [comment]
@jkowens Sorry I've been away moving and whatnot. I'll try to look into this over the weekend.

**Comment by jkowens** [comment]
@Rob117  I think this might be related to the fix for #518 after all.

Try changing your code to this:

```
validates :user, presence: true
validates :keyword_text, :client_id, :keyword_locale, :keyword_meaning, presence: true
```

**Comment by jkowens** [comment]
@Rob117 if that works, I'll work on submitting a fix.

**Comment by jkowens** [comment]
Went ahead and released v0.28.0 with this fix included.

**Comment by Rob117** [comment]
Sorry, I was out of country and things really got away from me. I put this in my system as next-to-try, I'll see if my tests pass with this in.

**Comment by Rob117** [comment]
@jkowens 
Hey, I just tested this, and everything appears to be working! I'm going to look into it some more in a bit, but this seems to be what I need. As a matter of face, I didn't even have to move the user validation to a separate line in the model - I just reran the tests and removed my workaround code and it's failing in the way that I expect.

**Comment by bsimpson** [comment]
> @timfsw that is a different issue I believe. See: #518
> 
> We purposely prevented validating belongs_to associations because it was executing a sql query for every record imported to make sure the association exists in the database. This came about because Rails 5 validates presence of belongs_to associations by default now. I'm not exactly sure how to proceed with that one, I'll need to think on it. Any input from others is appreciated.

In my opinion, this should be an importer validation option with a disclaimer about slower performance. Having the behavior of ActiveRecord validations with `presence: true` differ from activerecord-import's `validate` behavior is surprising.

**Comment by i7an** [comment]
Not the prettiest solution but it works:
```
class User < ApplicationRecord
  has_one :profile
  validates_presence_of :profile
  validate :validate_associations, on: :import

  private

  def validate_associations
    errors.add(: profile, :blank) if profile.blank?
  end
end

users = [...]

ActiveRecord::Associations::Preloader.new.preload users, [:profile]

User.import users, validate_with_context: :import
```
