### ISSUE TITLE
Broken error keys after import

### ISSUE THREAD

**Issue by vitalinfo** [zdennis/activerecord-import#577]
Ruby 2.6.0
Rails 5.2.0

f.e. we have a class
```
class User < ApplicationRecord
  belongs_to :profile

  validates :profile, presence: true
end
```
with version `0.27.0` all works fine and in case 
```
  User.import ..., on_duplicate_key_update: {conflict_target: ..., columns: ...}
  user = User.new
  user.valid?
```
`user.errors.keys` will include `:profile` key
but for version `0.28.0` `user.errors.keys` will include `:profile_id` key

**Comment by jkowens** [comment]
This was changed in part to prevent N+1 queries trying to validate existence of associated records when bulk importing. See #518.

To work around that, when bulk importing we just check that a foreign key is populated for the association. Is there a particular problem created for you because of this change?

**Comment by vitalinfo** [comment]
@jkowens the problem that `import` changes AR behavior and as for me this's totally wrong
back to my example
```
  user = User.new
  user.valid?
  user.errors.keys.include?(:profile) # is TRUE
  User.import ..., on_duplicate_key_update: {conflict_target: ..., columns: ...}
  user = User.new
  user.valid?
  user.errors.keys.include?(:profile) # is FALSE
```
this's not about work around, this's that ActiveRecord instances changed behaviour at all and only after `#import` execution

**Comment by jkowens** [comment]
Oh I see what you mean now. I’ll look into fixing that thanks 👍🏻

**Comment by jkowens** [comment]
@vitalinfo v0.28.1 has been released. Please let me know if any issue persists, thanks!

**Comment by vitalinfo** [comment]
@jkowens seems it' working now, Thanks 👍

**Comment by jkowens** [comment]
Awesome 🎉
