### ISSUE TITLE
Error while building from source

### ISSUE THREAD

**Issue by utkarsh2102** [zdennis/activerecord-import#582]
Hi,

There seems to be an error while building from source.
Is there something wrong with the tests?

Could you please verify?

**Comment by jkowens** [comment]
Do you need to run `gem install bundler`?

**Comment by utkarsh2102** [comment]
Yes.
So I am trying to package `activerecord-import` in Debian and hence need the same.

What could be the possible workaround?

**Comment by jkowens** [comment]
I'm not familiar with creating packages for Debian. You might want to try posting on StackOverflow where you'll get a bigger audience.

**Comment by utkarsh2102** [comment]
As far as I understand, the error has occurred because it couldn't build from source.

**Comment by jkowens** [comment]
It looks like your script is trying to run the tests. You need to have Bundler installed to do that. That is why you need to run `gem install bundler`.
