### ISSUE TITLE
RSpec tests with time zone set cause incorrect timestamps

### ISSUE THREAD

**Issue by dekaikiwi** [zdennis/activerecord-import#583]
I have only been able to replicate this faithfully in an rspec test on my side. But I have noticed the following issues between 0.27.0 and 0.28.1.

We have the Timezone for our project set to Tokyo (UTC +9)

Our tests looks something like this

```
data = [['2018-08-15 02:00', 10], ['2018-08-16 12:00', 20]].map do |created_at, foo|
            build(:some_model, created_at: created_at, foo: foo);
end

SomeModel.import(data)

```

On 0.27.0

The SomeModel records imported would have the correct timestamps

```
{ ... "created_at":"2018-08-15T02:00:00.000+09:00" ... }
{ ... "created_at":"2018-08-16T12:00:00.000+09:00" ... }
```

On 0.28.1

The timestamps appear to be in the +9:00 Timezone. But the times have also had 9 hours added to them.

```
{ ... "created_at":"2018-08-15T11:00:00.000+09:00" ... }
{ ... "created_at":"2018-08-16T21:00:00.000+09:00" ... }
```

Any idea what might be causing this at all?

**Comment by jkowens** [comment]
This commit https://github.com/zdennis/activerecord-import/commit/cb40b8068bceb5b0a1df0288dc1cc3b614f5d0ae changed some behavior related to timestamps. I don't really know why it would cause the issue you are seeing though. If you can track down the issue please let me know!

**Comment by dekaikiwi** [comment]
Will do. Need to spend a bit of time digging over the next few days

**Comment by jkowens** [comment]
I wonder if it is a difference between calling ` model.read_attribute` and `model.read_attribute_before_type_cast` when fetching the timestamp.

**Comment by jkowens** [comment]
Just as a note, prior to the commit mentioned, `model.read_attribute` was being called for all attributes on the model due to some erroneous logic around default values.

**Comment by jkowens** [comment]
Something I'm curious about is what happens if you pass data to import as an array of columns and values instead of model objects. ie:

```
columns = [:created_at, :foo]
values = [['2018-08-15 02:00', 10], ['2018-08-16 12:00', 20]]

SomeModel.import columns, values
```

Can you test and see if that handles the timestamps correctly or not?

**Comment by jkowens** [comment]
Are your dates still stored as UTC in the database?

For your tests I think this might be better:

data = [['2018-08-15 02:00', 10], ['2018-08-16 12:00', 20]].map do |created_at, foo|
            build(:some_model, created_at: created_at.in_time_zone, foo: foo);
end

SomeModel.import(data)

**Comment by dekaikiwi** [comment]
Just trying to find the time to have a good dive into this! Will try get there in the next week or so.

**Comment by jkowens** [comment]
@dekaikiwi can you check and see if the fix I merged to `master` resolves your issue?

**Comment by dekaikiwi** [comment]
@jkowens Just checked now! Specs on our side are passing across the board! Looking forward to the next release :)

**Comment by jkowens** [comment]
v1.0.1 has been released!
