### ISSUE TITLE
Document index_predicate in README

### ISSUE THREAD

**Issue by JeffKandel** [zdennis/activerecord-import#587]
Thanks for the awesome library. It took me a while to find the index_predicate option for on_duplicate_key_update.  Could you add an example to the README?

**Comment by andresespinosapc** [comment]
Thanks for creating this issue! I also needed this feature and found it thanks to you

**Comment by nhh** [comment]
Would be awesome to post your findings here until the docs are updated. I am currently searching for this feature 😄
