### ISSUE TITLE
Raise/warn when `no_returning: true` is used with `recursive: true`

### ISSUE THREAD

**Issue by dgollahon** [zdennis/activerecord-import#596]
Hi,

I was playing with my `activerecord-import` configuration and thought to turn enable `no_returning: true` since I don't ever use the results of any imports and didn't care to see the ids or consume whatever memory/time it required. What I did not consider, however, is that this silently stopped `#bulk_import` from importing my models recursively as I desired. I understand why the recursive behavior would need the ids, but I think it should raise an error or, at minimum, print a warning if the recursive import internally depends on the ids.

Thanks!

**Comment by jkowens** [comment]
Good catch. I think what we'll do is just ignore `:no_returning` when `recursive: true`.

**Comment by dgollahon** [comment]
Thanks!

**Comment by jkowens** [comment]
Released in v1.0.1
