### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by arcreative** [zdennis/activerecord-import#600]
Perhaps this is impossible, but was wondering if there's a way to stream records instead of expecting them all to be in-memory.  I have streaming enabled on the incoming side, would be nice to tie these two interfaces together :-)

**Comment by oniofchaos** [comment]
Interesting problem. Can you share some pseudocode of what your incoming side looks like?

**Comment by arcreative** [comment]
Here's my incoming side, output is rows in hash-based format.

```
class HydraImporter < AbstractImporter

  def connection
    @_connection ||= WarehouseRecord.connection.raw_connection
  end

  def each_result(&block)
    raise 'Please provide a block to handle each result' unless block_given?
    connection.send_query dataset_query
    connection.set_single_row_mode
    connection.get_result.stream_each &block
    connection.get_result
  end
end
```
And currently an importer looks like this:
```
class CvUploads < CitImporter

  def dataset_query
    %Q{
      SELECT
        user_id,
        ...
      FROM curriculum_vitae cv
      INNER JOIN users ON users.id = cv.user_id AND users.active
    }
  end

  def import
    ActiveRecord::Base.transaction do
      CvUpload.delete_all

      records = []
      each_result do |external|
        records.push(external)
      end

      # Import batch
      CvUpload.import(records)
    end
  end
end
```
Would be great to do something like this:
```
...
def import
  ActiveRecord::Base.transaction do
    CvUpload.delete_all
    CvUpload.batch_import do |import|
      each_result do |external|
        import.row external
      end
    end
  end
end
...
```
The [Upsert Gem](https://github.com/seamusabshere/upsert) that we're moving away from has an interface like this, but I prefer activerecord-import for most scenarios.  Maybe they can get away with it because it creates a stored procedure for the "pseudo-upsert"?  Not entirely sure, haven't had time to look into it.

**Comment by oniofchaos** [comment]
If I'm understanding the use case, would something like this work?

```ruby
    ActiveRecord::Base.transaction do
      CvUpload.delete_all

      records = []
      each_result do |external|
        records.push(external)

        if records.size == BATCH_SIZE # 1000, for example
          CvUpload.import(records)
          records = []
        end
      end
    end
```

**Comment by arcreative** [comment]
@oniofchaos I suppose so, but then you have to handle the tail-end scenario as well to import the remaining batch.  It just feels cleaner and simpler to stream it directly to the database if possible.  Guess it's not much of an issue, just anticipating the data is going to come in and out in about the same rate, so it seems like it would save a decent amount of time to stream one directly to the other.  I can live without it if need be :-)

**Comment by oniofchaos** [comment]
What's the interface on the upsert gem? I'd like to take a look and see what they're doing.

**Comment by arcreative** [comment]
I'm using Postgres, if that's what you mean?

**Comment by oniofchaos** [comment]
> The [Upsert Gem](https://github.com/seamusabshere/upsert) that we're moving away from has an interface like this

I wanted to see what code from Upsert you were using, so I could look at the source.

**Comment by arcreative** [comment]
Gotcha, looks like this:

```ruby
Upsert.batch(User.connection, User.table_name) do |upsert|
  users.each do |id, attrs|
    upsert.row({ id: id }, attrs)
  end
end
```

**Comment by oniofchaos** [comment]
I think outside of the lingering last insert call that there isn't much difference between what they're doing and what my `activerecord-import` pseudocode does. In the end, they're doing a bunch of raw SQL insert calls.  

[Upsert.batch](https://github.com/seamusabshere/upsert/blob/master/lib/upsert.rb#L71) => [Upsert.new.row](https://github.com/seamusabshere/upsert/blob/master/lib/upsert.rb#L220) => [Postgres merge function](https://github.com/seamusabshere/upsert/blob/master/lib/upsert/merge_function/postgresql.rb)

**Comment by arcreative** [comment]
But it's able to do so before 100% of my data is done importing, but I guess you're right that it's just a limit as batch size approaches 1.  Will do some benchmarks for fun, there are some scenarios where upsert is much faster, perhaps I can get them on-par.  Thanks for the help!

**Comment by arcreative** [comment]
And FWIW, true streaming would be much faster via something like Postgres' COPY command, but I'm not sure if that works with on conflict update.  Will have to check that out too.

**Comment by zdennis** [comment]
I don't believe [COPY](https://www.postgresql.org/docs/11/sql-copy.html) supports ON CONFLICT. I think the appropriate way to do that is a two step approach: 

Step 1: Use COPY to load data into a temporary table
Step 2: Use [INSERT FROM SELECT .. ON CONFLICT DO UPDATE](https://www.postgresql.org/docs/11/sql-insert.html) to import the data into the final destination table. 

activerecord-import does not currently support copy data from one table to another.

**Comment by zdennis** [comment]
@arcreative wrote:

> But it's able to do so before 100% of my data is done importing, but I guess you're right that it's just a limit as batch size approaches 1. Will do some benchmarks for fun, there are some scenarios where upsert is much faster, perhaps I can get them on-par. 

If the code ends up doing a single SQL statement per record being streamed then I would not imagine you're getting any performance wins. 

Depending on how fast your data comes in you could batch the data and run an import every N seconds. I don't know if this is acceptable in your scenario, but would more gracefully (and efficiently) handle bursts of incoming data.

**Comment by arcreative** [comment]
Sounds good, and was why I prefaced with "Perhaps this is impossible".  My apologies for not digging into the code a bit more before opening!
