### ISSUE TITLE
Wrong generation of SQL

### ISSUE THREAD

**Issue by dwahyudi** [zdennis/activerecord-import#603]
So what I did is 

Gemfile
`gem 'activerecord-import', require: false # latest version`

at the top of the file
```
require 'activerecord-import/base'
# load the appropriate database adapter (postgresql, mysql2, sqlite3, etc)
require 'activerecord-import/active_record/adapters/mysql2_adapter'
```

then do import
`MyModel.import(data)`

Data is an array of MyModel instance built with new.

I got this error:

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '),1,2,2,10000.0,(),(),(),(),'2019-03-15 10:15:57','2019-03-15 10:15:57',(),10000' at line 1: INSERT INTO `my_models` 

.....
 VALUES ((),1,2,2,10000.0,(),(),(),(),'2019-03-15 10:15:57','2019-03-15 10:15:57',(),10000.0,'2018-01-01',(),(),2.0,(),11,2,'TransactionLine',(),(),()) ON DUPLICATE KEY UPDATE `my_models`.`updated_at`=VALUES(`updated_at`)
```

Why does it generate '()' as value ?

When I use version 0.20.0 it correctly saves the data.

**Comment by jkowens** [comment]
What version do you currently have installed?

**Comment by dwahyudi** [comment]
> What version do you currently have installed?

The latest one, 1.0.1.

**Comment by jkowens** [comment]
Gotcha. I think the reason you're seeing "()" is because the attributes you're setting respond to `#to_sql`. Is that the case?

**Comment by jkowens** [comment]
See https://github.com/zdennis/activerecord-import/pull/471

**Comment by dwahyudi** [comment]
> Gotcha. I think the reason you're seeing "()" is because the attributes you're setting respond to `#to_sql`. Is that the case?

Not really, no. The attributes are just integers and strings.

**Comment by jkowens** [comment]
Are you able to create a sample project that demonstrates this issue? If can that would be very helpful.

**Comment by dwahyudi** [comment]
> Are you able to create a sample project that demonstrates this issue? If can that would be very helpful.

I couldn't reproduce the issue with new rails project (with the same gemfile).

But, if the case is from attributes that respond to `.to_sql`, would that be expected?

**Comment by jkowens** [comment]
It's something that I'm sure needs added to the readme. I think the reason for it is legitimate as described in #471. I don't know if maybe we should consider checking if the object is a `ActiveRecord::Relation` or if checking that it responds to `.to_sql` is the best option. 

I would not have expected basic values for the database to respond to `.to_sql`. Have you been able to track down the reason why they do in your application?

**Comment by dwahyudi** [comment]
I cannot seem to reproduce it, I'm moving on to new Rails version.
