### ISSUE TITLE
Upcoming Rails support for mass inserts

### ISSUE THREAD

**Issue by dillonwelch** [zdennis/activerecord-import#604]
https://github.com/rails/rails/pull/35077

Looks like Rails is FINALLY adding support for this (though not nearly as comprehensive as this gem). Thoughts about starting to:
1) Deprecate the gem?
2) Add additional methods that match up to the Rails API so that it's easy for people to migrate off the gem when they want to?

**Comment by jkowens** [comment]
Finally! That's good to see. I'll leave it up to @zdennis to make those decisions.

**Comment by simi** [comment]
It is not capable of doing all supported behaviour of `activerecord-import` still.

**Comment by oniofchaos** [comment]
Not at all. Certain common use cases (mainly Postgres) could certainly migrate over to Rails though now. Might be worth adding a deprecation method if we detect someone is on Rails 6+, using Postgres, and is using a method that is now built into Rails.

Separately, a good project would be to assist in adding more features into Rails so that more people can migrate off the gem.

**Comment by sluceno** [comment]
After migrating to Rails6 upsert_all we are missing some of the functionality of `activerecord-import` like working with models, pass validations, etc.

We are thinking about to migrate back to use `activerecord-import` but we are afraid about the direction will take the gem. Any news about it? Will it be deprecated sooner than later?

Thanks guys

**Comment by jkowens** [comment]
@sluceno `activerecord-import` has probably matured to a point where there won't be much development activity, new features, etc. However for the foreseeable  future we'll try to make sure it continues to work with new releases of Rails.

**Comment by simi** [comment]
:thinking: I think we can start with building list of unsupported Rails features and try to contribute them one by one. I can help with contribution part. Personally I do miss only https://github.com/zdennis/activerecord-import#duplicate-key-update.

**Comment by jkowens** [comment]
@simi personally I don't think would try to move all features of ar-import to rails core. I think this gem started to try to do too much, but I do think upsert is a really great feature of this gem.
