### ISSUE TITLE
ActiveRecord Import with Ancestry

### ISSUE THREAD

**Issue by Brotakuu** [zdennis/activerecord-import#606]
I'm using [active import](https://github.com/zdennis/activerecord-import) to import comments and [Ancestry](https://github.com/stefankroes/ancestry) to build the comment trees. Is there any way to create the ancestry tree during the import (when the primary key `id` is not created yet)?

Currently, I'm importing all the comments, then looping through each comment to add the parent, and it is very slow even with indexes:

```
comments_to_import = []
import_data.each do |comment|
    comments_to_import << Comment.new(is_parent: comment.parent_uuid.nil?, uuid: comment.uuid, parent_uuid: comment.parent_uuid, body: comment.body)
end
Comment.import comments_to_import

# build comment tree
Comment.where(is_parent: false, ancestry: nil).all.each do |c|
    parent = Comment.find_by(uuid: c.parent_uuid)
    c.update(parent: parent)
end
```

**Comment by jkowens** [comment]
What field is set you when you do `c.update(parent: parent)`? Does that set a `parent_id` field on the comment?

**Comment by Brotakuu** [comment]
Yes, it's built in [function](https://github.com/stefankroes/ancestry#organising-records-into-a-tree) to the ancestry gem. But the `comment` model does not have `parent_id`.

**Comment by jkowens** [comment]
So what is actually being inserted/updated in the database when you call `c.update(parent: parent)`?

**Comment by Brotakuu** [comment]
Ancestry has a separate column called `ancestry` that sets the parent ids like this:

```
{
  #<TreeNode id: 100018, name: "Stinky", ancestry: nil> => {
    #<TreeNode id: 100019, name: "Crunchy", ancestry: "100018"> => {
      #<TreeNode id: 100020, name: "Squeeky", ancestry: "100018/100019"> => {}
    },
    #<TreeNode id: 100021, name: "Squishy", ancestry: "100018"> => {}
  }
}
```

I was just wondering if its possible to build the tree during the import process, instead of looping through each comment and rebuilding it after the import.

**Comment by Brotakuu** [comment]
this is the sql output when I loop through each comment and call `c.update(parent: parent)`

```
   (27.6ms)  COMMIT
  Comment Load (23.7ms)  SELECT  "comments".* FROM "comments" WHERE "comments"."uuid" = $1 LIMIT 1  [["uuid", "dzsdafva0fdsafnafpafdsafasfsafk"]]
   (22.6ms)  BEGIN
  Comment Load (38.8ms)  SELECT "comments".* FROM "comments" WHERE ("comments"."ancestry" ILIKE '126246/%' OR "comments"."ancestry" = '126246')
  SQL (29.0ms)  UPDATE "comments" SET "ancestry" = $1, "updated_at" = $2 WHERE "comments"."id" = $3  [["ancestry", "126184/126192"], ["updated_at", "2019-03-19 16:27:00.565389"], ["id", 126246]]

```

**Comment by jkowens** [comment]
If the comments are all being inserted at the same time including ancestors and children I don't think there is much else you can do. I'm wondering if you can build out the relations before importing, once you do import the primary keys should be set on the objects (if using postgresql). Then you might be able to run a second import passing an array of the objects that are not parents.
