### ISSUE TITLE
Active Record - import w/ Geocoder

### ISSUE THREAD

**Issue by joshm1204** [zdennis/activerecord-import#607]
Used ActiveRecord-import to import a batch of records to a model that has the geocoder gem.  I noticed that the records had Latitude and longitude values, which means the on change call back was working. Can you please explain this, as I thought call backs were disabled?  Is this a bug or am I missing something?

My code looks similar to this.. 
https://stackoverflow.com/questions/55327220/csv-foreach-memory-usage-keeps-increasing

With multiple models and inserting model objects.  Is there a faster way to insert my records and not have call backs?

**Comment by jkowens** [comment]
Only validation callback runs when validation is enabled. If you don’t need validation add option validate: false when importing.

**Comment by joshm1204** [comment]
Then why did my on change callbacks run?

**Comment by jkowens** [comment]
Which callback do you mean when you say "change"? Are you saying `before_save`, `after_save`, etc?

**Comment by joshm1204** [comment]
geocoded_by :full_address_for_geocoder
  after_validation :geocode, :if => :full_address_for_geocoder_changed?

**Comment by jkowens** [comment]
That's an `after_validation` callback so as mentioned, if validations are enabled, the callbacks associated with validation do run (`before_validation`, `after_validation`).

Disable validations by adding `validate: false` to your `import` call.
