### ISSUE TITLE
Uniq case insensitive index is not used as a constraint.

### ISSUE THREAD

**Issue by RomanKapitonov** [zdennis/activerecord-import#608]
I've never been able to figure out a solution for the following case neither in the readme nor in the code. Consider the following unique index (as an example):
```sql
CREATE UNIQUE INDEX index_user_on_lower_name
ON users USING btree (LOWER(name));
```

Importing the records with the following code fails:
```ruby
Users.import(
  users,
  on_duplicate_key_update: {
    conflict_target: [:name],
    columns: [:email, :address, :phone_number]
  }
)
# PG::InvalidColumnReference: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
```

Unfortunately, Posgres doesn't allow creating unique constraints with modifiers, i.e you can not do the following:
```sql
ALTER TABLE users
ADD CONSTRAINT for_upsert UNIQUE(lower(name));
```

Is there a workaround for this? If not this may potentially be a good candidate for adding to the library. Thank you!

**Comment by jkowens** [comment]
Have you tried something like this:

```
Users.import(
  users,
  on_duplicate_key_update: {
    constraint_name: :index_user_on_lower_name,
    columns: [:email, :address, :phone_number]
  }
)
```

See: https://github.com/zdennis/activerecord-import/blob/d946a0f2bf806563599935f8e8fb3537481e760b/lib/activerecord-import/import.rb#L471

**Comment by RomanKapitonov** [comment]
@jkowens I've tried this, however this index doesn't seem to be a constraint.

Here are the indexes:
```
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "index_users_on_lower_name" UNIQUE, btree (lower(name::text))
```

**Comment by RomanKapitonov** [comment]
Figured out this works in case target_name is specified as:

```ruby
target_name: 'unique(lower(name::text))',
```
