### ISSUE TITLE
NoMethodError (undefined method `each' for nil:NilClass)

### ISSUE THREAD

**Issue by jonnynux** [zdennis/activerecord-import#609]
I'm trying to use this gem, but I receive this message when I call import on my Model:

```ruby
s = []
10.times { |i| s << Source.new(:name => "name #{i}") }
Source.import s

Traceback (most recent call last):
        1: from (irb):18
NoMethodError (undefined method `each' for nil:NilClass)
```
My model Source has the following columns:
```ruby
  create_table "sources", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "name", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "reliability", default: 0, null: false
  end
```

I'm currently using Rails 5.2.2.1 and activerecord-import 1.0.1

**Comment by jkowens** [comment]
@jonnynux There isn't much to go on here. Can you post a more in depth stack trace?

**Comment by jonnynux** [comment]
I found the problem. In the same project we included also the elasticsearch gem which uses the same method import used by activerecord-import. What to do in this case?

**Comment by jkowens** [comment]
Try the alias `bulk_import`:

```
Source.bulk_import s
```

See: https://github.com/zdennis/activerecord-import#conflicts-with-other-gems

**Comment by jonnynux** [comment]
Thanks @jkowens
