### ISSUE TITLE
Bulk validation / Dry run

### ISSUE THREAD

**Issue by phoet** [zdennis/activerecord-import#610]
is it possible to do a dry-run or bulk-validate records in some kind of way?

i would like to present a user with ie. duplicate email adresses before the data is actually inserted into the database.

i hope this is the right place to ask, i could not find a answer to my question in the readme or the issues.

thanks

**Comment by jkowens** [comment]
Import validates records by default, but look at the docs for the `:validate` and `:validate_uniqueness` options. Records that fail validation will be returned while the others will be included in the insert.

See also: https://github.com/zdennis/activerecord-import#return-info

**Comment by phoet** [comment]
So it is no possible to do dry run / validation only?

**Comment by zdennis** [comment]
Hi @phoet, you can ask any questions here. :)

To build on what @jkowens shared, activerecord-import currently does not currently provide any functionality to help with bulk uniqueness validations. For normal model validation, ActiveRecord itself will run a single SELECT statement for every model/record that has a uniqueness validation. We have talked about providing functionality to streamline this, but it's not something that has been implemented.

You can validate the models before you attempt an import and then import (and with validations turned off the import is quicker). If you want something more performant than the default ActiveRecord behavior you may need to implement something that works for your app/data-set. E.g. load data in memory and do a soft-uniqueness check in memory, run SQL uniqueness queries in batches, locking tables during checks, checking the data-set to be imported against DB values, and/or checking the. data-set to be imported against itself, etc.

**Comment by phoet** [comment]
@zdennis thx for the broader explanation, we are basically doing the later with running validate on a bunch of models which is not super awesome fast and has the drawback of missing unique errors within the set.

So using the bulk library would speed up our import process but it would not help with the validation issue.
