### ISSUE TITLE
on_duplicate_key_update SUM existing value

### ISSUE THREAD

**Issue by nick453** [zdennis/activerecord-import#614]
Hello guys. How is possible to SUM the value of  array to my existing row field during on_duplicate_key_update?

For example:
Model.import array, on_duplicate_key_update: [ :column_value + array_value]

Thank you.

**Comment by deepakmahakale** [comment]
As mentioned in the [README](https://github.com/zdennis/activerecord-import/#duplicate-key-update)

This works on MySQL
```ruby
Book.import [book], on_duplicate_key_update: "quantity = quantity + VALUES(quantity)"
```
Change the format accordingly for PostgreSQL
```ruby
Book.import [book], on_duplicate_key_update: {
  conflict_target: [:id], columns: "quantity = books.quantity + excluded.quantity"
}
```

**Comment by jkowens** [comment]
@nick453 the response provided by @deepakmahakale should do the trick. Please let us know if there is anything more we can answer. I'm going to close this issue for now.

**Comment by nick453** [comment]
@deepakmahakale Thank you very much for your help!
