### ISSUE TITLE
Error after upgrading ActiveRecord and Import Gem with Sequence

### ISSUE THREAD

**Issue by Ahbrown41** [zdennis/activerecord-import#615]
After upgrading but the Gem and Active Record I keep getting these errors from this Gem, it appears it is trying to incorrectly access the sequence in a non PostGres way.  The same is working for a normal create but not for this Gem.  I have no idea why I am seeing this behavior, any ideas?

```
    activerecord (4.2.11.1)
      activemodel (= 4.2.11.1)
      activesupport (= 4.2.11.1)
      arel (~> 6.0)
    activerecord-import (1.0.1)
      activerecord (>= 3.2)
```

```
     ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "vehicles_id_seq"
       LINE 1: ...) VALUES (vehicle_fe...
                                                                    ^
       : INSERT INTO "vehicles" ("id",.........) VALUES (vehicles_id_seq.nextval,'N','........) RETURNING "id"
```

**Comment by jkowens** [comment]
Can you try running the following sql to make sure the sequence is still owned by the correct table:

```
alter sequence vehicles_id_seq owned by vehicles.id;
select pg_get_serial_sequence('vehicles', 'id');
```
Afterward try running the import again.

**Comment by Ahbrown41** [comment]
Hey!  Ok I did the following:
```
alter sequence vehicle_feeds_id_seq owned by vehicle_feeds.id;
select pg_get_serial_sequence('vehicle_feeds', 'id');
Returns: _public.vehicle_feeds_id_seq_
```
It appears the issue is it is doing this:
```
VALUES
(public.vehicle_feeds_id_seq.nextval,
```
Instead of this (Which works):
```
VALUES
(nextval('vehicle_feeds_id_seq'),
```

**Comment by jkowens** [comment]
Ah, so I have a feeling you're manually loading your dependencies? If that is the case I think you'll need to require the following:

```
require 'activerecord-import/base'
require 'activerecord-import/active_record/adapters/postgresql_adapter'
```

See https://github.com/zdennis/activerecord-import#requiring

**Comment by Ahbrown41** [comment]
Oh man, yeah it was an Rspec test.  I thought the app was failing at runtime and it was not apparently (anymore).  In the middle of a significant refactor and missed it.

Thank you sir!
