### ISSUE TITLE
on_duplicate_key_update : based on foreign key or custom field in Mysql

### ISSUE THREAD

**Issue by reddoorz-ashishmittal** [zdennis/activerecord-import#616]
Is it possible to upsert based on foreign key conflict and update particular attributes?
Book.import [book], on_duplicate_key_update: {conflict_target: [:id], columns: [:title]}

**Comment by jkowens** [comment]
I hope I understand correctly, but any unique index defined for a MySQL table should allow you to do an upsert. There is no need to specify the conflict target or constraint name with MySQL.

```
Book.import [book], on_duplicate_key_update: [:title]
```

**Comment by reddoorz-ashishmittal** [comment]
Thanks for the help, now I got what I have to do.
