### ISSUE TITLE
Unsupported adapter imports only first row

### ISSUE THREAD

**Issue by rahul342** [zdennis/activerecord-import#624]
I am adding a new adapter on existing codebase which is using `activerecord-import`. I wasn't aware of this gem being used in the code so the adapter didn't load and silently failed because of https://github.com/zdennis/activerecord-import/issues/129. I guess that is fine.

The problem is existing code calling `import!` seems to just run but only updates the first row.

With the default mysql2 adapter, here's the query that got executed
```
Class Create Many Without Validations Or Callbacks (1.2ms)  
INSERT INTO `geohashes`
 (`id`,`created_at`,`updated_at`,`geohash`,`region_id`,`subregion_id`) 
VALUES 
(NULL,'2019-05-24 18:12:01','2019-05-24 18:12:01','9q8yv4',1,NULL),
(NULL,'2019-05-24 18:12:01','2019-05-24 18:12:01','9q8yv1',1,NULL) 
ON DUPLICATE KEY UPDATE `geohashes`.`updated_at`=VALUES(`updated_at`)
```

With the new adapter

```
(1.0ms)  
INSERT INTO `geohashes` 
(`id`,`created_at`,`updated_at`,`geohash`,`region_id`,`subregion_id`)
 VALUES
 (NULL,'2019-05-24 18:12:59','2019-05-24 18:12:59','9q8yv4',1,NULL)
```

It simply skipped the rest of the rows! Luckily there were tests that caught this, but seems very dangerous.

May be we can still allow for silent rescue when adapter is not found, but I would propose that the expected behavior when calling `import` on unsupported adapter should be to raise error. If I am missing something, let me know. I can try and understand the gem's code and propose a patch.

Thanks for creating this!

**Comment by jkowens** [comment]
I believe if an adapter is not supported it will attempt to still insert every record, executing `n` inserts for `n` number of records. See: https://github.com/zdennis/activerecord-import/blob/79d5697fc3f2967c59039a7dfeaf653ee2476ccd/lib/activerecord-import/import.rb#L815

Is that not happening?
