### ISSUE TITLE
Results for postgresql is nil when importing empty array

### ISSUE THREAD

**Issue by gyfis** [zdennis/activerecord-import#635]
I know this is an ugly edge case, but when you `.import` an empty array, the resulting `results` for PostgreSQL is nil, where it probably should be an empty array (since `ids` is an empty array in the result):

```ruby
> import_result = RowTitle.import([:title], [], returning: :title)
=> #<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=0, ids=[], results=nil>
> import_result.ids
=> []
> import_result.results
=> nil
```

It behaves the same when inputting an empty array without column titles into the `.import` method.

**Comment by jkowens** [comment]
Yep, that should be consistent. We'd have to make that update part of a major release if is decided to fix.

**Comment by gyfis** [comment]
@jkowens Cool! I prepared a PR: #636
