### ISSUE TITLE
type binary (blob, clob, nclob in oracle) doesn't get saved

### ISSUE THREAD

**Issue by saslani** [zdennis/activerecord-import#637]
- Database adapter: oracle_enhanced
- Rails 6 stable
- Ruby 2.6.3
- gem "activerecord-oracle_enhanced-adapter", git: "https://github.com/rsim/oracle-enhanced.git", branch: "release60"
- gem "ruby-oci8", "2.2.7"

Migration: any column with type binary (oracle: blob), text (oracle: clob) or ntext (oracle nclob) gets saved as an empty string.

**Comment by toao** [comment]
@jkowens I just stumbled upon this issue, it's still there and ```activerecord-import-oracle_enhanced``` unfortunately does not fix it.

Example SQL looks like this:
```
INSERT INTO "FOO" ("BAR","BAZ","CREATED_AT","UPDATED_AT") WITH names ("BAR","BAZ","CREATED_AT","UPDATED_AT") 
AS (SELECT 'foobar1337',empty_clob(),'2022-01-21 14:22:39.719127','2022-01-21 14:22:39.719127' FROM DUAL
union all SELECT 'baz42',empty_clob(),'2022-01-21 14:22:39.719127','2022-01-21 14:22:39.719127' FROM DUAL)
```

The ```BAZ``` column should contain the clob data, but instead of the actual content ```empty_clob()``` is passed instead.
