### ISSUE TITLE
Great to have untouched_instances when using on_duplicate_key_ignore

### ISSUE THREAD

**Issue by puneetpandey** [zdennis/activerecord-import#638]
It would be nice to have `untouched_instances` as **Return Info**, for the records that cannot qualify primary or unique key constraints or when using `on_duplicate_key_ignore`.

**Comment by puneetpandey** [comment]
no helper method available for Sqlite3 Or I should take a look at `ON CONFLICT DO NOTHING`?

**Comment by jkowens** [comment]
SQLite3 also supports `on_duplicate_key_ignore`, and it generates an `ON CONFLICT DO NOTHING` statement similar to Postgres.

**Comment by jkowens** [comment]
Closing because it doesn't look like this is a feature we will be able to add. Will reopen if any technical details on how to retrieve such data from database is discovered or provided.
