### ISSUE TITLE
Ability to update has_many associations fields in recursive imports?

### ISSUE THREAD

**Issue by pilgunboris** [zdennis/activerecord-import#640]
Hello! Are there any plans on adding the ability to update `has_many` associations fields together with main object update with option `recursive: true` (so existing associations would be updated and new ones created)? This scenario works for the main collection, so probably it might be added for associations as well.

Example:
```Ruby
author1 = Author.create!(name: 'John Doe', country: 'SomeCountry')
author1.books.create!(name: 'Book1', pages_number: 123)

author1.country = 'Another Country'
author.books.first.pages_number = 333
author1.books.build(name: 'Book2', pages_number: 777)

# WAY-1:

Author.import [author1], recursive: true,
  on_duplicate_key_update: { 
    conflict_target: { 
      authors: :id, 
      books: :id 
    }, 
    columns: { 
      authors: [:name, :country], 
      books: [:name, :page_number] 
    },
  validate: false

# WAY-2:

Author.import [author1], recursive: true,
  on_duplicate_key_update: { 
    authors: { conflict_target: :id, columns: [:name, :country] },
    books: { conflict_target: :id, columns: [:name, :page_number] },
  validate: false
```
So at the end it should create new book `Book2` with all initialized fields and update fields `country` in `author1` and `pages_number` in `Book1`.

I guess the main problem here is an extra query to retrieve a list of existing associations IDs to know what of them to create and what to update.

Such ability would be really helpful for data syncing since now it takes 2 operations - first create missing objects, second - update existing.

**Comment by jkowens** [comment]
Hi @pilgunboris, we don't have any plans at the moment for such a feature. I agree it would be useful, but it get's a little messy trying to determine the right hash options. For instance, I think it would be confusing to have to use `authors` as a key when `Author` doesn't have a `has_many` relationship called `authors`. And then for those that are not using "recursive" import, do they have to add that extra hash?

```
Author.import [author1],
  on_duplicate_key_update: { 
    authors: { conflict_target: :id, columns: [:name, :country] }
  },
  validate: false
```

These are some of the things that make it difficult to pursue. I'm open to more input and further discussion though!

**Comment by pilgunboris** [comment]
Hi @jkowens, I think it makes sense to keep the current syntax for those who don't need this extra functionality and for back-compatibility but also add alternative ability to specify fields in associations just like in my example for better flexibility. 
What do you think?

I'm not familiar with the source code so far, but I'll try to investigate how to implement it.

**Comment by jkowens** [comment]
Yes, if we could retain backwards compatibility that would be an option. If you have some time to investigate implementation, that would be fantastic. Thanks 👍

**Comment by brandonsturgeon** [comment]
I would very much appreciate this feature 👍 

I'm not sure how I'll rewrite this not that I found out this isn't possible 😅

**Comment by karandocs** [comment]
Is there any alternative to achieve this now?

**Comment by pilgunboris** [comment]
@jkowens could you please confirm - does #746 addresses this issue? 
Except for that part where need to specify fields to update in associations of course - but this was just a suggestion of how it might work.

If it does save initialized associations and updates all changed fields in existing ones then I think this issue is resolved.

**Comment by jkowens** [comment]
@pilgunboris yes #746 does address this issue when using the parameter `on_duplicate_key_update: :all` 👍

**Comment by pilgunboris** [comment]
@jkowens thanks! Closing it then 👍
