### ISSUE TITLE
Issue with inserting the json column

### ISSUE THREAD

**Issue by NarenPushparaju** [zdennis/activerecord-import#644]
when I initialize an object with a JSON column and when I try to change the JSON column the updated value for the JSON column is not updating. Here's an example,

```
columns = [:name, :display_data]
people_list = []

1.times do 
  p = Person.new(name: 'dlkfjer', email: 'kssjdf', display_data: {full_name: 'rwhhwg', email: 'erowrhguh'})
  p.display_data['dkfnf'] = 'sdflkjsgld'
  people_list << p
end

response = Person.import(columns, people_list, validate: false, batch_size: 1000)
```
In the above example, display_data is a JSON column and the insert happens like the following:

`INSERT INTO "people" ("name","display_data","created_at","updated_at") VALUES (NULL,'{"full_name":"rwhhwg","email":"erowrhguh"}','2019-10-08 18:20:24.066662','2019-10-08 18:20:24.066700')RETURNING id`

Can anyone explain why the updated value is not inserting up ? is this an issue?

**Comment by jkowens** [comment]
Can you show the result of `p.inspect` after updating `display_data`?

**Comment by NarenPushparaju** [comment]
@jkowens Here's the result `#<Person id: nil, created_at: nil, updated_at: nil, project_id: nil, data: {}, email: "kssjdf", identify_data: {}, mail_preference: nil, spammed_mail_type: nil, spammed_mail_id: nil, user_id: nil, un_read_messages_count: 0, chat_email: nil, person_un_read_messages_count: 0, initial_data: nil, avatar_image: nil, profile_data: nil, gravatar_image_url: nil, display_data: {"full_name"=>"rwhhwg", "email"=>"erowrhguh", "dkfnf"=>"sdflkjsgld"}, is_blocked: false, is_dummy: false, avatar_background: "#ffffff", account_id: nil, fb_person_id: nil, name: "dlkfjer", tsv_email_name: nil> `

**Comment by jkowens** [comment]
Interesting, I'm not sure why it would be missing that new attribute. Could you also provide the version of ActiveRecord and ActiveRecord-Import that you are using? If you can share a sample repo that demonstrates this issue that would be super helpful.

**Comment by NarenPushparaju** [comment]
@jkowens Here are my versions:
ActiveRecord version - 5.0.3
ActiveRecord-Import - 0.15.0
Sorry, I couldn't able to share my repo at this moment.

**Comment by NarenPushparaju** [comment]
yeah! Thanks.

**Comment by NarenPushparaju** [comment]
It's working fine after updating. Thanks!
