### ISSUE TITLE
Document `validate_with_context` Option

### ISSUE THREAD

**Issue by jdalt** [zdennis/activerecord-import#653]
The `README` should make light of the `validate_with_context` feature.

I struggled to find a way to avoid certain very expensive validations (that I could pre-validate en masse) and only found that I could pass a validation context when reading the source code. 

I think this feature should be called out in the options section: https://github.com/zdennis/activerecord-import#options

Thanks so much for creating and maintaining this gem! I've worked in Rails for several years and this solves a huge class of problems that I had never found a good solution for. This was the missing piece in my performance strategy, and I'm grateful to have found your work.

**Comment by jkowens** [comment]
@jdalt thank you for the kind words! Feel free to send up a PR that adds documentation for this option. We'll get it merged in 👍

**Comment by jdalt** [comment]
Thanks for the quick reply! I'm on it.

**Comment by jdalt** [comment]
@jkowens https://github.com/zdennis/activerecord-import/pull/654
