### ISSUE TITLE
If model uses AR optimistic locking, lock_version attribute is always reset to 1

### ISSUE THREAD

**Issue by timanovsky** [zdennis/activerecord-import#655]
This applies to at least Postgres implementation. 
**Repro:**

1. Create a model with `lock_version` numeric attribute, this will activate AR optimistic locking
2. Import with `import(... , on_duplicate_key_update: [])`
3. The generated SQL will look like: `INSERT INTO ... ON CONFLICT (...) DO UPDATE SET "updated_at"=EXCLUDED."updated_at","lock_version"=EXCLUDED."lock_version"+1  RETURNING ... `

Where `EXCLUDED."lock_version"` is 0 in the original fresh object. 

**Expected:**
Gererated SQL be `ON CONFLICT (...) DO UPDATE SET "updated_at"=EXCLUDED."updated_at","lock_version"="lock_version"+1` or even better 
`ON CONFLICT (...) DO UPDATE SET "updated_at"=EXCLUDED."updated_at","lock_version"=COALESCE("lock_version", 0)+1`

OR

Don't touch `lock_version` at all and let user do it with custom SQL. Now if you try to specify `lock_version` in `on_duplicate_key_update: []` array it will raise an error `PG::SyntaxError: ERROR:  multiple assignments to same column "lock_version"`

I think it is a bug/typo in https://github.com/zdennis/activerecord-import/pull/500 , namely here: https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/adapters/postgresql_adapter.rb#L208 it should refer to a `lock_version` in the table, not in inserted object.

**Comment by jkowens** [comment]
Good catch, that makes sense. Are you able to put together a PR for this issue?

**Comment by timanovsky** [comment]
@jkowens Hi, created the PR. 
BTW kudos for making CI experience so seamless, it made it really easy!

**Comment by jkowens** [comment]
Awesome, thanks for submitting a patch! 💯 🎉
