### ISSUE TITLE
Incompatible with CarrierWave?

### ISSUE THREAD

**Issue by davideluque** [zdennis/activerecord-import#666]
Hello guys,

I have a model that has a [CarrierWave](https://github.com/carrierwaveuploader/carrierwave) uploader.

```ruby
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end
```

This is how the uploader looks like
```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def cache_dir
    "uploads/tmp/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  process resize_to_fit: [800, 5000]

  version :thumb do
    process resize_to_fit: [50, 50]
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

end
```

I am adding the image to the model like this, according to [CarrierWave's documentation](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-remote-image-urls-to-your-seedfile) for remote image urls.
```ruby
p = Post.new({remote_image_url: "https://via.placeholder.com/350x150"})
Post.import([p])
```

Also trying this way.
```ruby
img = File.new(File.join(Rails.root, "app/assets/images/generic/generic_one.jpeg"))
p = Post.new({image: img})
Post.import([p])
```

The model is saved to the database but the image is not set although it is uploaded. Do you guys have an idea of what could be the problem?

Thanks a lot!

**Comment by jkowens** [comment]
I believe CarrierWave works with callbacks which AR-Import does not execute.

See https://github.com/zdennis/activerecord-import#callbacks for possible workarounds.

**Comment by davideluque** [comment]
> I believe CarrierWave works with callbacks which AR-Import does not execute.
> 
> See https://github.com/zdennis/activerecord-import#callbacks for possible workarounds.

Thank you. I will take a look at that and post here if I find a workaround.

**Comment by jkowens** [comment]
Hi @davideluque, did executing the callbacks work out?

**Comment by davideluque** [comment]
Hi @jkowens, For reasons of time, I had to do without the use of the gem in my development. However, I have on my list to explore the solution to optimize my development. I will write if I conclude something. Meanwhile, if you wish, you can close the PR.

**Comment by gabrielrodriguez7** [comment]
Hi @davideluque! executing manually the callbacks it works for me

```ruby
[p].each do |post|
  post.run_callbacks(:save) { false }
  post.run_callbacks(:create) { false }
end

Post.import([p])
```

**Comment by gabrielrodriguez7** [comment]
Hi @davideluque! executing manually the callbacks it works for me. Also had to run 'store!' for each item to keep in permanent storage:

```ruby
[p].each do |post|
  post.run_callbacks(:save) { false }
  post.run_callbacks(:create) { false }
  post.image.store!
end

Post.import([p])
```

**Comment by jtcontreras90** [comment]
Hi @gabrielrodriguez7! I modified your script to not run unnecessary callbacks for anyone that may be looking how to do it:
```ruby
[p].each do |post|
  post.write_image_identifier
end
Post.import([p])
[p].each do |post|
  post.store_image!
end
```
I run store_image! after the import as it's in an `after_commit` callback.

This way I had no N+1 in the process
