### ISSUE TITLE
Is there any way to upsert array column

### ISSUE THREAD

**Issue by aniketstiwari** [zdennis/activerecord-import#668]
Is there any way I can update array fields instead of replacing them.  For example

 I have a table users which has columns 
user_id  - primary_key
friends - an array of integers
created_at - DateTime
update_at - DateTime
description - string

user = []
user << User.new(user_id: 23291, friends: [1,2,3], updated_at: DateTime.now())
User.import user, on_duplicate_key_update: {conflict_target: [:user_id], columns: [:friends, :updated_at]}

Every time I run the above command the array field is getting replace instead of append. Is there any way to achieve this?

**Comment by jkowens** [comment]
You'll have to use the custom SQL option for `:columns`. I imagine it would look something like:

```
User.import user, on_duplicate_key_update: {
  conflict_target: [:user_id],
  columns: "friends = array_append(excluded.friends), updated_at = excluded.updated_at"
}
```

See "Using Custom SQL" here: https://github.com/zdennis/activerecord-import#duplicate-key-update

**Comment by aniketstiwari** [comment]
@jkowens  This won't work because of the array_append append element whereas in my case I need to append array. Also, I tried with array_cat but it is also not working

**Comment by jkowens** [comment]
Did you get this working with array_cat?

**Comment by jkowens** [comment]
@aniketstiwari that's great, glad you found a solution!
