### ISSUE TITLE
Blank UUID values not inserting

### ISSUE THREAD

**Issue by ralampay** [zdennis/activerecord-import#670]
When importing data from some file and using the import command, if the column is mapped to a uuid data type and the value is blank (like a blank string), it fails to import the record.

**Comment by jkowens** [comment]
Can you provide some sample code of how you are using import? Are you importing using models, arrays, or hashes?

**Comment by ralampay** [comment]
I use UUID as primary and foreign keys in my database. So if I have something like:

```
data = [{ id: "000048d7-312a-4c63-9e73-9f026b9f93af", center_id: "fffffac7-bfa2-4384-b585-03bc68fce53d" }]
columns = [:id, :branch_id]
Model.import(columns, data)
```

it will fail.

**Comment by jkowens** [comment]
I imagine that is correct behavior, wouldn't a nil value violate a not-null constraint? Unless you defined the column to generate a uuid value if null?

**Comment by ralampay** [comment]
The column is nullable. so I think it doesn't accept '' as blank. Even nil doesn't work.

**Comment by jkowens** [comment]
Can you include the generated insert statement SQL (and the resulting SQL error) with your example? That should make this easier to pinpoint the issue.

**Comment by jkowens** [comment]
Closing for now, waiting for more information.
