### ISSUE TITLE
It's not importing bulk 

### ISSUE THREAD

**Issue by Sri-K** [zdennis/activerecord-import#672]
Hi, I am getting an issue of not inserting the records as bulk and it's insert one by one. My example is below and any help would be much appreciated. I am using Rails 3 Ruby 1.9.3.

```
def import
  columns = [:Master_Code, :Master_Name, :created_by, :updated_by]
  values = filter_results.map! do |hash|
    [hash[:code], hash[:description], CurrentUser.name, CurrentUser.name]
  end

  ModelName.import columns, values, validate: false
end
```

The above method inserts one by one like the below

```
   (28.0ms)  INSERT INTO "dba"."ModelName" ("Master_Code","Master_Name","created_by","updated_by","created_at","updated_at") VALUES ('Q','UAT','DBA','DBA','2
020-04-21 22:23:40.977','2020-04-21 22:23:40.977')
   (14.0ms)  INSERT INTO "dba"."ModelName" ("Master_Code","Master_Name","created_by","updated_by","created_at","updated_at") VALUES ('S','S Volume','DBA','DBA','
2020-04-21 22:23:40.977','2020-04-21 22:23:40.977')
   (13.0ms)  INSERT INTO "dba"."ModelName" ("Master_Code","Master_Name","created_by","updated_by","created_at","updated_at") VALUES ('t','Test','DBA','DBA','
2020-04-21 22:23:40.977','2020-04-21 22:23:40.977')
```

Also I have tried all the different ways like in the documentation. Each give me a different errors like `Invalid arguments: Argument Error, etc`

Can someone help me and point me out where I am doing wrong please?

**Comment by jkowens** [comment]
Can you provide the following:

- Database and version
- Specific Rails version
- activerecord-import version

**Comment by Sri-K** [comment]
Hi @jkowens , Thanks for the reply.

Database: **Sqlanywhere ( Sybase )**
Rails: **3.2.22.5**
activerecord-import: **gem "activerecord-import-in4systems", '~>0.2.13'**

I think because of the database, one of the old member of my company(who is no more working) modified the gem to support the sybase database. Not sure how or who modified and created this gem `gem "activerecord-import-in4systems", '~>0.2.13'`. But it's used to work before. 

Thanks

**Comment by jkowens** [comment]
@Sri-K I don't know that @zdennis created that gem. It looks more likely that it was created by  @ccouzens.

Sybase is not a core supported database, so I don't think I'll be able to help.

**Comment by Sri-K** [comment]
Thanks @jkowens for trying though !

**Comment by jkowens** [comment]
To build a proper adapter for SQL Anywhere look at this example for Oracle:

https://github.com/keeguon/activerecord-import-oracle_enhanced

A similar methodology can be used for SQL Anywhere.

See: https://github.com/zdennis/activerecord-import#additional-adapters
