### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by shaicoleman** [zdennis/activerecord-import#675]
Would you consider relicensing this under the MIT license?

The Ruby license is a non-standard weak copyleft license, which gets flagged as requiring legal review.
I think it would make sense to license it the same as Rails/ActiveRecord, i.e. the MIT License.

**Comment by jkowens** [comment]
Good question, I will defer to @zdennis. What do you think?

**Comment by zdennis** [comment]
@jkowens, I have no problem with that.

**Comment by jkowens** [comment]
License updated 😎
