### ISSUE TITLE
Experiencing huge performance penalty after upgrading to 1.0.4

### ISSUE THREAD

**Issue by lvonk** [zdennis/activerecord-import#676]
Hi,

We had an unused dependency on `activerecord-import` and after doing a periodic `bundle update` we noticed a huge performance penalty in one of our rake tasks that generates test users on our development machines. The rake task just drops and re-creates the databases and inserts some records into various tables. 
This whole process used to take ~ 29seconds, but after upgrading it took `1:39.44`. We pinpointed this problem to this gem, downgrading to 1.0.3 fixed the issue for us. We eventually removed it since we came to the conclusion it was not even used, which makes it kind of weirder but might help in resolving the issue.

**Comment by jkowens** [comment]
I'm not seeing any discernible differences in our benchmarks between 1.0.3 and 1.04. The code changes were pretty minimal too. If I'm understanding correctly, you're saying the import portion of the lib wasn't even being used which makes this even more weird.

This was probably the most notable change: https://github.com/zdennis/activerecord-import/pull/648

If anyone else has any insight please share, thanks!

**Comment by lvonk** [comment]
Hi @jkowens 

I will try to run with and without that that change. And yes, the whole gem was unused.
