### ISSUE TITLE
possible to use on_duplicate_key_update == [:column1, :column2,...] with recursive imports on postgres?

### ISSUE THREAD

**Issue by breathe** [zdennis/activerecord-import#682]
I'd like to pass a list of the columns to upsert (across all rows in the recursive import) and be sure that only those columns are ever going to be upserted on primary key conflict ... is this supported by activerecord-import somehow?

Code I'm using yields an ActiveRecord::StatementError if I try to use recursive import with on_duplicate_key_update ...

**Comment by jkowens** [comment]
From what I remember I don't think `on_duplicate_key_update` is passed to associated models. Can you post the resulting SQL statement to see what is causing the error?

**Comment by breathe** [comment]
Apologies -- I believe I misidentified the issue in the original issue report ...

Its been awhile and I did end up not using the recursive option -- but was still having issues which ended up being actually that I had more than one instance of the same entity with id=foo in the insertion list ...  I thought it would just apply the upserts in order but it actually fails the upsert with an error that doesn't do much of anything to indicate the cause.

I think this issue can be closed --

**Comment by jkowens** [comment]
Ok, will close for now but feel free to reopen if you come across this again and can provide some more details.
