### ISSUE TITLE
Ruby 2.6.1 Message undefined method `[]=' for #<Enumerator::Chain:0x00007fc0b2d2b110> 

### ISSUE THREAD

**Issue by abramin** [zdennis/activerecord-import#686]
Using Ruby 2.6.1, Rails 3.2.22.19, 1.0.5 of this gem:

Get 
`Message undefined method []= for #<Enumerator::Chain:0x00007fc0b2d2b110>`

when running import.

The error seems to be due to the new `Enumerator::chain` code added in Ruby 2.6
https://ruby-doc.org/core-2.6/Enumerator/Chain.html

Running this code with Ruby 2.1# hit this block
https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L54-L57

and `@validate_callbacks.respond_to?(:chain, true)` returned false.

Now, `@validate_callbacks.respond_to?(:chain, true)` returns `true`, since `@validate_callbacks` is an Enumerator.

It enters the block but fails on `chain[i] = callback`

This would work as `chain.to_a[i] = callback`
Have monkey patched it in my project and it resolves the issues.

However I´m not sure what the original intention of that block was.
Any help appreciated, cheers.

**Comment by jkowens** [comment]
@abramin I'm actually surprised you got Rails 3.2 running with Ruby 2.6! I was under the impression the highest supported Ruby was 2.2 or maybe 2.3.

The reason for that block is to modify the validations being called for a model. We need to filter out uniqueness and presence validators for performance reasons.

I think possibly a better monkey patch would be:

```
        if @validate_callbacks.respond_to?(:chain, true) && @validate_callbacks.send(:chain)
          @validate_callbacks.send(:chain).tap do |chain|
            callback.instance_variable_set(:@filter, filter)
            chain[i] = callback
          end
        else
          callback.raw_filter = filter
          callback.filter = callback.send(:_compile_filter, filter)
          @validate_callbacks[i] = callback
        end
```

I think that will make sure your validators are still called.

**Comment by abramin** [comment]
Thanks @jkowens - yeah it´s a temporary situation until we upgrade to Rails 4. I don´t think Rails 3 supports Ruby 2.6 technically but got it to work with only minor changes.

I´ll add the second clause to the `if` check, but the ` chain[i] = callback` still fails since `Enumerator` doesn´t respond to `[]=` so the `to_a` is necessary.

Appreciate the quick response.

**Comment by jkowens** [comment]
Ok, sounds good. I'm going to close this because I think it's an issue specific to using newer Rubies with Rails 3.

**Comment by clushie** [comment]
With the commercial https://rails-lts.com fork support goes up to ruby 2.7, thanks for leaving the monkey-patch for reference.
