### ISSUE TITLE
 Problem while using recursive Activerecord import

### ISSUE THREAD

**Issue by himanikaushik143** [zdennis/activerecord-import#688]
I have two models one for appointment and another for its sessions . Appointment has_many sessions and session belongs to appointment . I am suppose to create appointment with sessions using import , recursive: true but I am facing that appointment is creating but associated sessions are not creating.
here's the snippet of the code that might help to understand the case:

```
appointment = []
appointment.push Appointment.new(apt_params)
ActiveRecord::Base.transaction do
   session_params.each do |key, session|
    appt_session = appointment.first.appt_sessions.build(appt_session_params)
   end
   unless Appointment.import appointment, recursive: true
    raise ActiveRecord::Rollback
   end
end
```

**Comment by jkowens** [comment]
Can you confirm you are using Postgresql?

**Comment by himanikaushik143** [comment]
I m using mysql , won't it work with mysql?

**Comment by jkowens** [comment]
No, sorry "recursive" import is only available with Postgresql because it will return the inserted ids for the records. Unfortunately MySQL does not do that.

**Comment by himanikaushik143** [comment]
alright thanks
