### ISSUE TITLE
Getting empty ids and results array in response of an ActiveRecord import request

### ISSUE THREAD

**Issue by himanikaushik143** [zdennis/activerecord-import#689]
After using Activerecord import I found that its creating/updating the records intended but I m getting empty array of ids and results in response. Here is the rails console output :

`appt = Appointment.import(appointment, all_or_none: true)
D, [2020-07-23T12:41:37.657164 #7635] DEBUG -- :   Appointment Create Many Without Validations Or Callbacks (0.4ms)  INSERT INTO `appointments` (`id`.......) VALUES (NULL,....) ON DUPLICATE KEY UPDATE `appointments`.`updated_at`=VALUES(`updated_at`)
#<struct ActiveRecord::Import::Result failed_instances=[], num_inserts=1, ids=[], results=[]>`

**Comment by jkowens** [comment]
Are you using MySQL? We are only able to populate inserted ids when using Postgresql.

**Comment by himanikaushik143** [comment]
yes I m using mysql
