### ISSUE TITLE
Add Support for Generate Columns

### ISSUE THREAD

**Issue by msharp9** [zdennis/activerecord-import#701]
When I try to bulk import an array of records I keep getting the following error:

```
Java::OrgPostgresqlUtil::PSQLException: ERROR: cannot insert into column "column_name"
  Detail: Column "column_name" is a generated column.
```

Using regular `.save` methods works fine but when using `.import` it tries to update the generated column with a null value.

Looking through I found this issue: https://github.com/zdennis/activerecord-import/issues/521 but the fix assumes that the generated column is virtual and not stored.  Not all generated columns are virtual.

**Comment by jkowens** [comment]
@msharp9 good to know. Would you be able to look into fixing the issue?

**Comment by jkowens** [comment]
Maybe issue #681 is related as well.

**Comment by msharp9** [comment]
I didn't see that issue.  Yes, I believe it is related.  Looks like once https://github.com/rails/rails/pull/39368 is merged it will likely fix this issue.

**Comment by jkowens** [comment]
Still waiting on ActiveRecord to add support for generated virtual columns in Postgresql. We'll probably need to add documentation about what version of AR supports those column types.

**Comment by jkowens** [comment]
Generated columns will be supported in Rails 7. 

https://weblog.rubyonrails.org/2021/9/17/this-week-in-rails-rails-7-alpha-released/
