### ISSUE TITLE
`to_sql': wrong number of arguments (given 0, expected 1..2)

### ISSUE THREAD

**Issue by helmutrs** [zdennis/activerecord-import#703]
I'm trying to use your GEM without using ruby on rails. So I have my 
Gemfile:
gem 'mysql2', '~> 0.5.3'
gem 'smarter_csv', '~> 1.2', '>= 1.2.6'
gem 'activerecord', '~> 6.0', '>= 6.0.3.2'
gem 'activerecord-import', '~> 1.0', '>= 1.0.6'

When I'm trying to do a bulk import:
`chunk.group_by(&:keys).each_value do |v|
   GrantStreet.import v
end`

it gave me an error:
/usr/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql': wrong number of arguments (given 0, expected 1..2) (ArgumentError)

looking at the error, it takes me to: rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb 
`
      # Converts an arel AST to SQL
      def to_sql(arel_or_sql_string, binds = [])
       sql, _ = to_sql_and_binds(arel_or_sql_string, binds)
       sql
end
`

**Comment by jkowens** [comment]
What kind of object is `v`?

**Comment by jkowens** [comment]
I think `v` would have to be an array of ActiveRecord objects or a `Hash` object that has key and values that map to attributes in your GrantStreet model. My guess is that `v` isn't an expected object type. Feel free to reopen with more info.

**Comment by helmutrs** [comment]
@jkowens  v is array of hashes that has  columns names as that the actual table. When I loop v (array of hashes) and inside the loop each each hash (hash-v) ModalName (< ActiveRecord::Base) **create** hash-v, it actually works, but if I do ModelName.import v it gave me the actual problem.

**Comment by jkowens** [comment]
Ok, it sounds like hash-v must be some type of Hash subclass that adds a `to_sql` method.

**Comment by helmutrs** [comment]
@jkowens basically it would be like this:
`books = [
  { title: "Book 1", author: "George Orwell" },
  { title: "Book 2", author: "Bob Jones" }
]

# without validations
Book.import columns, books, validate: false`
