### ISSUE TITLE
Import has_many recursive on_duplicate_key_ignore

### ISSUE THREAD

**Issue by facuhump2409** [zdennis/activerecord-import#712]
I like to know if there's a way of updating a table that has a many to many relationship but if the record is already there ignore it. Cause I have a Offer which has many categories coming from an API and sometimes I get the same offer and I want to update the categories if they change or keep the ones in the DB if nothing has changed
![image](https://user-images.githubusercontent.com/32522610/97348736-5581bd80-186d-11eb-84ef-94646bfeddc9.png)
The first time works fine, but the second time as it tries to insert the same tuple (offer_id,category_id) in the category_single_offer (brand_id,offer_id) table I get an error coming from the constraint that avoids having repeated records
![image](https://user-images.githubusercontent.com/32522610/97348924-95e13b80-186d-11eb-8b18-7a8070e1c71c.png)
Is there a way to ignore these cases similar to on_duplicate_key_ignore but for many to many relations?
Thanks in advance

**Comment by jkowens** [comment]
No, there isn't a way to do that right now. We could consider providing an option to just ignore duplicate keys when doing a "recursive" import.

For now, could you try importing categories first and then doing the offer import?

**Comment by facuhump2409** [comment]
Yeap, I’ll make that, thanks

**Comment by facuhump2409** [comment]
![image](https://user-images.githubusercontent.com/32522610/97987111-83a95500-1db9-11eb-8912-3970b33d6a06.png)
@jkowens  And is there a way to avoid having that validation when importing recursively? Because it makes the import very slow with a lot of records

**Comment by jkowens** [comment]
I think you'd have to turn off validations entirely using `validate: false`.
