### ISSUE TITLE
Unique index is being ignored on import with on_duplicate_key_update

### ISSUE THREAD

**Issue by nhh** [zdennis/activerecord-import#713]
Hi,

the following code ignores my unique index:

```Performance.import performances, on_duplicate_key_update: { constraint_name: 'idx_performances_for_upsert', columns: :all }```

The following error is returned, and namely hints the ignored unique constraint:

`ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "idx_performances_for_upsert"`

I am creating my unique index as following:

```
execute <<-SQL

      CREATE UNIQUE INDEX idx_performances_for_upsert ON performances(
        customer_id,
        resolution,
        origin_date,
        COALESCE(chapter_label_system, '50dfea57-507d-4f84-aa72-0eb80c7393db'),
        COALESCE(portfolio_label_system, '05af6a23-0cdc-4dea-8d12-27f0d94cf1e5')
      );

      ALTER TABLE performances ADD CONSTRAINT paranoid_chapter_label_system CHECK (chapter_label_system <> '50dfea57-507d-4f84-aa72-0eb80c7393db');
      ALTER TABLE performances ADD CONSTRAINT paranoid_portfolio_label_system CHECK (portfolio_label_system <> '05af6a23-0cdc-4dea-8d12-27f0d94cf1e5');

SQL
```

How can I use activerecord-import to respect my unique index?

**Comment by jkowens** [comment]
Can you confirm what version of Postgres you have installed and the version of activerecord-import?

**Comment by nhh** [comment]
@jkowens 

activerecord-import (1.0.6)
'postgres:11'

Did you notice that I am using an index instead of an constraint? (I am not aware of the difference, but its worth noticing)

Thank you for responding!

**Comment by nhh** [comment]
I also verified that the index exists:

```
Indexes:
    "performances_pkey" PRIMARY KEY, btree (id)
    "idx_performances_for_upsert" UNIQUE, btree (customer_id, resolution, origin_date, COALESCE(chapter_label_system, '50dfea57-507d-4f84-aa72-0eb80c7393db'::character varying), COALESCE(portfolio_label_system, '05af6a23-0cdc-4dea-8
d12-27f0d94cf1e5'::character varying))

Check constraints:
    "paranoid_chapter_label_system" CHECK (chapter_label_system::text <> '50dfea57-507d-4f84-aa72-0eb80c7393db'::text)
    "paranoid_portfolio_label_system" CHECK (portfolio_label_system::text <> '05af6a23-0cdc-4dea-8d12-27f0d94cf1e5'::text)

```

I must be using this wrong 🤔

**Comment by jkowens** [comment]
Hm I don't see any obvious issue. Are you able to find the INSERT statment sql? I would test that sql directly in a psql console.

**Comment by nhh** [comment]
I rember wondering why there is no "ON CONFLICT..." at the end of the sql statement. 🤔 I will deliver a complete query tomorrow.

Thank you!

**Comment by jkowens** [comment]
Hey, just checking in. Anything more on why the "ON CONFLICT" wasn't added to the insert statement?

**Comment by nhh** [comment]
Sorry for not responding. The unique constraint is enforced by Postgres. It seems, that `activerecord-import` does not generate the necessary "ON CONFLICT" part. I dont have more information on that and its ok for now, because we just truncate the table on a daily basis. You can close this issue for now until I provide steps to reproduce! Thank you for checking in:)
