### ISSUE TITLE
Using activerecord-import with Rails 6.1.0.rc1 results in SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by codeodor** [zdennis/activerecord-import#715]
Using activerecord-import with Rails 6.1.0.rc1 results in SystemStackError: stack level too deep any time we attempt to establish our own connection. 

The line in question is: 

```
activerecord-import-1.0.7/lib/activerecord-import/import.rb:250:in `establish_connection'
```

**Comment by codeodor** [comment]
It doesn't seem to happen if I just run one single test, but if I run my whole suite it always ends up triggering it. 

If I comment out the line `prepend ActiveRecord::Import::Connection` that adds the AR Import gem's `establish_connection` then it no longer triggers the error. (I don't yet know if AR Import works without doing that, though).

**Comment by jkowens** [comment]
Hey @codeodor, thanks for the report. I had a feeling we would see some issues with Rails 6.1 since it sounds like there have some big updates in ActiveRecord. I think commenting out that prepend will basically disable AR Import. If you happen upon any leads please keep us updated!

**Comment by codeodor** [comment]
Thanks @jkowens. In the one place I'm using AR Import, it still seems to work when commenting out that line. That's the good news! But, I'm not sure why AR Import has overridden AR::Base connection method? 

It looks like it needs to run this: 

`ActiveRecord::Import.load_from_connection_pool connection_pool`

But does it need to run it on every AR::Base model, and what does that do? 

I traced it back to 10 years ago: https://github.com/zdennis/activerecord-import/blame/3c08fad1a2cfa9d7880730f068ddb318aa7b2968/lib/activerecord-import.rb

But could it not just get the connection and do that inside the import method? (And is that necessary, even?) 

Those are earnest questions. I don't know it well enough, so I'm just throwing things out there. :)

**Comment by codeodor** [comment]
When running the tests on mysql2 with that prepend removed, we do get more errors, most of which seem to be of the sort:

`ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '99' for key 'PRIMARY'`

Strangely, sqlite3 tests work better with that line removed: only 4 failures and 3 errors vs 0 failures and 138 errors with it on.

**Comment by codeodor** [comment]
If we move that line to the bulk_import method, all the tests seem to go back to passing (the ones that passed to begin with, before any changes were made, anyway). 

I will check if it gets rid of the problem in my app like this.

**Comment by jkowens** [comment]
Hey thanks for all digging into this! I'll have to see look this over a little bit, but I think your proposed solution seems very reasonable 👍

**Comment by jkowens** [comment]
@codeodor can you take a look at #717? I cherry picked a couple of your commits and got the test suite passing with AR 6.1. I’m curious if you will still see errors.

**Comment by jkowens** [comment]
What's weird is the PR that introduced the `prepend` was fixing a stack level too deep error: https://github.com/zdennis/activerecord-import/issues/647 😅

**Comment by codeodor** [comment]
@jkowens yes I still get stack level too deep errors when running against the main repo, but if I run it against mine that has the change to where the connection pool is loaded, it seems to run without error.

**Comment by jkowens** [comment]
Ok, I figured it would. Does the stack trace indicate another library that AR-Import might be conflicting with?

**Comment by codeodor** [comment]
No, there's just about 20k lines of:

```
.../bundler/gems/activerecord-import-324acd077683/lib/activerecord-import/import.rb:250:in `establish_connection'
```
And then 3 lines from my app.

**Comment by jkowens** [comment]
Haha ok thanks. I wonder if maybe it's a new Rails setting that we don't have in the test suite that is involved. I guess I'll have to create a demo Rails 6.1 app and play around a bit 😅

**Comment by jkowens** [comment]
I've created a demo app with the Rails 6.1 release. So far AR-Import seems to work without issue. Can you create a sample project that reproduces the issue you are seeing?

**Comment by codeodor** [comment]
Hey, to clarify: I didn't have an issue directly with an attempted import. I didn't even try it. The problem was that AR::Import code was causing my app to have this error when I made my own calls to AR::Base#establish_connection. 

I'm gonna try to give an example app later this week, but I am a little swamped so I apologize in advance for the delay.

**Comment by jkowens** [comment]
@codeodor after finally doing some research into this, I _think_ I discovered the root cause of the issue. It seems like your code or another gem in your project is using `alias_method` on AR::Base#establish_connection. Can you confirm if this is happening?

See: 

- https://bugs.ruby-lang.org/issues/11120
- https://blog.bearer.sh/module-overrides-ruby-prepend-alias/

**Comment by codeodor** [comment]
That is an incredible find. I thought I was decent at searching, but I didn't find this stuff!

Unfortunately, I searched my project and my gems folder with the regex `/alias_method.+:establish_connection/` and it came up empty. So, I don't think that's it. Unless you think maybe I should be looking for some other string?

**Comment by codeodor** [comment]
Unless ... I do `stub` it in some tests. Maybe that's doing it?

**Comment by codeodor** [comment]
(But this has also been like this for years -- so if so, why is it only now suddenly a problem?)  I'll try running the suite without those tests to see how it behaves.

**Comment by jkowens** [comment]
We switched over to `prepend` instead of `alias_method` in v1.0.4. So a fairly recent change. Now that I'm looking back as to why I see it is probably related to this issue 🤦‍♂️ 

Ref #647

**Comment by codeodor** [comment]
That's amazing. This was the problem. I solved it by not stubbing AR::Base.establish_connection in my tests, and just creating the DB and migrating it when running. Tests take a little longer to run, but it'll work for me.

Be nice if there was a way to un-prepend it for testing purposes though. 

Thanks a lot for your help. I don't think I'd have ever discovered that in a million years of digging. Truly a great find. Thanks!

**Comment by jkowens** [comment]
Whew man, I'm glad you were able to get to the bottom of this one. I feel bad this negatively impacted your tests. I wonder if mocking libraries are working on this issue with prepended modules?

**Comment by codeodor** [comment]
Could be that they are, or they already have. I use a crossbreed between rspec mocks and minitest for `stub_any_instance` and I'm not sure if it runs through that or not -- I'll need to check.

But I do wonder if they would then have the opposite problem: any gem that uses `alias_method` they may then be in conflict with. 

I'll check that out at a later time, though. I'm just glad to know I don't need to run a fork of this project, and even more glad to know it was limited to my tests anyway, because this had me very fearful of deploying to production.

I still have a few issues to work through but this was a major one on my list, so I appreciate your attention to it, and I apologize for the length of time it took to identify. I do appreciate it though!

Thanks,
Sam
