### ISSUE TITLE
Rails 6.1 crashes when activerecord-import is in the gemfile

### ISSUE THREAD

**Issue by dorner** [zdennis/activerecord-import#718]
When I include the latest versions of both active_record and activerecord-import in my Gemfile, any attempt to e.g. run `rails db:migrate` crashes with the following output:

```
rails aborted!
NoMethodError: undefined method `spec' for #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x00007fef893ae1e0>
Did you mean?  inspect
```

This error goes away if I either remove activerecord-import or downgrade to Rails 6.0.

**Comment by jkowens** [comment]
Are you using the latest version of activerecord-import?

**Comment by dorner** [comment]
I could have sworn I was but I went back and checked and I wasn't. 😮 So sorry - ignore me!

**Comment by jkowens** [comment]
Haha no worries 👍

**Comment by t-juryl** [comment]
For whoever is dealing with this issue in the future, you need to update `activerecord-import` to version `1.0.0` or greater
