### ISSUE TITLE
Validation fails for existing (valid) records

### ISSUE THREAD

**Issue by LaurelOlson** [zdennis/activerecord-import#721]
If a record already exists in the database, the validation on import does not take into consideration the fields on the existing record. It only considers the fields passed in as args (as a hash). As a result, unless all required params are passed into `import`, validations fail, even if the existing model with the new fields applied is valid.

Example:

```
class Product
  belongs_to :category
end

class Category
  has_many :products
end

category = Category.create
product = Product.create(category: category)

Product.import! { name: "Ball" }, on_duplicate_key_update: :all
# fails with ActiveRecord::RecordInvalid (Validation failed: Category must exist)
```

**Comment by jkowens** [comment]
When importing an array of hashes, you'll have to supply the associated ids:

```
Product.import! [{ category_id: category.id, name: "Ball"}], on_duplicate_key_update: :all
```

If you are using Postgres, you might be interested in taking a look at the "recursive" import option: https://github.com/zdennis/activerecord-import#recursive

**Comment by LaurelOlson** [comment]
Thanks for the reply and suggestions @jkowens - I reviewed the example I originally provided and realized it's not complete, sorry about that. The use case is there is a foreign key on the table but that data is not available when doing the import without loading in each record from DB to fetch it. I'm passing in a conflict target which is also passed in the data. I would expect that since the conflict_target is provided and matches an existing (valid) record, the import would succeed _without_ specifying the foreign key, since the existing record has the foreign key.

I have a workaround as follows that makes the `belongs_to` optional and then manually validates on a specific context. Ideally, this wouldn't be necessary since it requires the additional step of passing the context in order for the validation to occur.

```
class Product
  belongs_to :category, optional: true
  validates :reference, unique: true
  validates :category_id, presence: true, on: :process
end

class Category
  has_many :products
end

category = Category.create
product = Product.new(category: category, reference: "123)
product.save(context: :process) # validate category_id existence

Product.import! { name: "Ball", reference: "123" }, on_duplicate_key_update: { conflict_target: [:reference],  columns: :all }
# fails with ActiveRecord::RecordInvalid (Validation failed: Category must exist) if `category` is not optional
```

**Comment by jkowens** [comment]
@LaurelOlson ah I understand now. The upsert handling all happens at the database level..we just pass that off to Postgres when executing the `INSERT` statement. That means that all the ActiveRecord validations happen first. Could you possibly turn off validations for the import? (make sure to have constraints at the the db level if you do)

```
Product.import! [{ name: "Ball", reference: "123" }], on_duplicate_key_update: { conflict_target: [:reference],  columns: :all }, validate: false
```

**Comment by LaurelOlson** [comment]
@jkowens OK yea that's what I thought - I have DB constraints so that should work. Thanks!

**Comment by LaurelOlson** [comment]
FYI for anyone who comes across this issue: 

Turns out the DB constraint doesn't work after all - the import throws `ActiveRecord::NotNullViolation`. This has [come up before](https://github.com/zdennis/activerecord-import/issues/431) and is a limitation:

> Ah, so that confirms it...Postgres checks NOT NULL constraints before evaluating ON CONFLICT.
> 
> More here:
> 
> https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT
> 
> and here:
> 
> https://stackoverflow.com/questions/43483610/when-does-a-not-null-constraint-run-and-can-it-wait-until-the-transaction-is-goi

**Comment by jkowens** [comment]
Sorry I forgot about that! Thanks for the update.
