### ISSUE TITLE
ActiveModelImportResult[:num_inserts]  does not work In mysql

### ISSUE THREAD

**Issue by tashirosota** [zdennis/activerecord-import#723]
Showld not num_inserts return if does not work, it gets confusing.

**Comment by tashirosota** [comment]
What do you think of [this approach?](https://github.com/tashirosota/activerecord-import/pull/2/files)

**Comment by jkowens** [comment]
Hi @tashirosota, `num_inserts` should be working for MySQL. If it isn't I believe that is a bug to be fixed. Can you post an example with result?

**Comment by tashirosota** [comment]
@jkowens 
Sorry I was misunderstanding.
I thought num_inserts means record increased count.
This mistake is easy to happen.In fact our other team member made the same mistake.
How about adding warning log like [this](https://github.com/zdennis/activerecord-import/pull/724)?
