### ISSUE TITLE
good practice to not require gem in all environments?

### ISSUE THREAD

**Issue by jjb** [zdennis/activerecord-import#730]
Thanks for a great project!

I think for many uses of the gem, it won't be needed at app runtime, so one would want to include it like this:

    gem 'activerecord-import', require: false

and then do this at the top of one's script

    require 'activerecord-import/base'
    require 'activerecord-import/active_record/adapters/postgresql_adapter'

Does this sound reasonable?

Maybe it should be mentioned in the readme? I spun my wheels for a while with the same error here: https://github.com/zdennis/activerecord-import/issues/615

if you agree, I can make a PR.

**Comment by jkowens** [comment]
Manually requiring the library is mentioned here: https://github.com/zdennis/activerecord-import#manually-loading

Improvements to the readme are always welcome though 👍

**Comment by jjb** [comment]
whoops! not sure how i missed that, thanks.
