### ISSUE TITLE
ActiveRecord::StatementInvalid PG::CardinalityViolation: ERROR: ON CONFLICT DO UPDATE 

### ISSUE THREAD

**Issue by serhanbalci** [zdennis/activerecord-import#733]
I did not understand why I am getting this error. Anybody ever faces this error with this gem in the Ruby on Rails project. 

`PG::CardinalityViolation: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second-time HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values. `

Thanks.

**Comment by jkowens** [comment]
I think this is a case where there is a duplicate within the array of values that are being inserted. With Postgres you will need to make sure the values you are importing are distinct.

**Comment by serhanbalci** [comment]
Thanks, @jkowens. I hope to update the record not try to insert. For example;  I want to insert products with different IDs and names and I wish to update the same id and name. is this correct usage? Thanks.

```
    Product.import(%i[name id], additional_attributes, on_duplicate_key_update: {
                              conflict_target: %i[name id],
                              columns: %i[name value],
                              validate: false
                            })
```

**Comment by jkowens** [comment]
I assume `additional_attributes` is your array of values? That is where you have duplicate entries. Otherwise your usage is correct.

**Comment by serhanbalci** [comment]
Yes its array of values, thanks I will try to debug.

**Comment by WaseekSenju** [comment]
@serhanbalci I am getting the same error. Do you remember was this issue due being passed or what?

**Comment by serhanbalci** [comment]
@WaseekSenju sorry dude I don't remember :)
