### ISSUE TITLE
Typo in Duplicate Key Update Section

### ISSUE THREAD

**Issue by RicardoZeballos** [zdennis/activerecord-import#734]
Typo in Duplicate Key Update Section 2nd Example

The example is incorrect.
book.reload.title  # => "Book1"              (stayed the same) 
book.reload.author # => "Updated Book Title" (changed)

**Comment by jkowens** [comment]
Please provide more detail, how should it read?

**Comment by jkowens** [comment]
This looks fine to me, closing for now.
