### ISSUE TITLE
Does activerecord-import support SQL SERVER and on_duplicate_key_update?

### ISSUE THREAD

**Issue by daveomcd** [zdennis/activerecord-import#747]
So far I have gotten this gem to work with my Rails 5.1.6 app.  It works great for inserting records, but I can't figure out a way to update records if they already exist in my table.  I have a unique constraint on my table but when running the following I get an error as if it doesn't recognize `on_duplicate_key_update`.  Just trying to figure out if this is supported or if there is even a hacky way to go about accomplishing updating records if they exist.  Thanks!

`BlockingStatistic.import results.to_a, batch_size: 100, on_duplicate_key_update: :all`

```
 BEGIN TRANSACTION
   (9.3ms)  INSERT INTO [blocking_statistics] ([player_id],[club_id],[status],[season],[pro_game_id],[pass_block_snaps],[run_block_snaps],[sacks_allowed],[hits_allowed],[hurries_allowed],[beaten_by_defender],[penalties],[disruptions_allowed_not_beaten],[disruptions_allowed],[run_block_wins],[run_block_pulls],[run_block_pull_wins],[run_block_losses],[running_yards_created],[created_at],[updated_at]) VALUES (2469,16,N'started',2020,13907,47,33,0,0,2,3,1,3,5,4,0,0,3,2.8220781,'09-11-2021 15:21:08.353','09-11-2021 15:21:08.353'); SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident
  SQL (3.5ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
Traceback (most recent call last):
        2: from (irb):2
        1: from app/models/blocking_statistic.rb:34:in `import_records'
ActiveRecord::RecordNotUnique (TinyTds::Error: Cannot insert duplicate key row in object 'dbo.blocking_statistics' with unique index 'index_blocking_statistics_on_pro_game_id_and_player_id'. The duplicate key value is (13907, 2469).: INSERT INTO [blocking_statistics] ([player_id],[club_id],[status],[season],[pro_game_id],[pass_block_snaps],[run_block_snaps],[sacks_allowed],[hits_allowed],[hurries_allowed],[beaten_by_defender],[penalties],[disruptions_allowed_not_beaten],[disruptions_allowed],[run_block_wins],[run_block_pulls],[run_block_pull_wins],[run_block_losses],[running_yards_created],[created_at],[updated_at]) VALUES (2469,16,N'started',2020,13907,47,33,0,0,2,3,1,3,5,4,0,0,3,2.8220781,'09-11-2021 15:21:08.353','09-11-2021 15:21:08.353'); SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident)
```

**Comment by jkowens** [comment]
@daveomcd unfortunately `on_duplicate_key_update` only works for MySQL, SQLite, and PostgreSQL. There is a gem that adds basic SQL Server support, but it doesn't look like it addresses upsert functionality:

https://github.com/keeguon/activerecord-import-sqlserver

**Comment by daveomcd** [comment]
@jkowens thanks!  Yeah I looked at it.  Looks like it hasn't been updated in quite some time either - also has a PR that still hasn't been addressed.

Does `activerecord-import` have a "update" method that I can use outside the `on_duplicate_key_update` ?  Just trying to figure out the best way of updating records without deleting records out and reinserting.

**Comment by jkowens** [comment]
No, activerecord-import only does inserts. We were able to add upsert for the mentioned databases because they have upsert capability with their insert statements.

**Comment by daveomcd** [comment]
@jkowens, thanks!  The import bulk is huge, so I just need to figure out a process for updating if exists now.  Thanks again for the quick replies and all the help.

**Comment by jkowens** [comment]
@daveomcd sorry I couldn’t provide more help. I’ve read that you can use MERGE in MSSQL to do upserts but that would be a customized effort for your import set I would assume.
