### ISSUE TITLE
Update Ruby Version on required_ruby_version

### ISSUE THREAD

**Issue by mrkurko** [zdennis/activerecord-import#748]
Update the ruby version because the method **positive?** was introduce on ruby higher 2.4

It used on [Here](https://github.com/zdennis/activerecord-import/blob/309d42abe8c27aef23d82e57addadc275126773e/lib/activerecord-import/import.rb#L812)
activerecord-import.gemspec line 19

**Comment by jkowens** [comment]
Thanks for point this out, I totally missed that. `Numeric#positive?` was introduced in Ruby 2.3, so I will make that the minimum required version.

**Comment by jkowens** [comment]
Actually I changed my mind, requiring ruby 2.4 and ActiveRecord 4.2 👍
