### ISSUE TITLE
can't use on_duplicate_key_update in mySQL

### ISSUE THREAD

**Issue by iFaujack** [zdennis/activerecord-import#768]
Hello, 

I had an issue when I tried passing opt params on duplicate key update. like the gem can't read my params.

Code 
`::Development::MultipleBreak.import data, validate: false, on_duplicate_key_update: [:name, :company_id]`

SQL Log
`INSERT INTO tbl_multiple_break (id,name,company_id) VALUES (100,'test 101',1) `

in my project connected to 2 DB's, primary connection to Postgres DB and secondary to MariaDB.
when I tried to model for Postgres DB didn't have an issue and worked well and exec on conflict do. but in my secondary DB the SQL always only `insert into tbl_xxx (columns) values(xxx)` 

because of that, when trying to import data with an existing id in DB always throws an error `(ActiveRecord::RecordNotUnique) `

**Comment by iFaujack** [comment]
when I do insert multiple data SQL log shows the data insert into the table one by one.

currently, I'm using mysql2 gem with version 0.5.2 for the DB adapter.


`
(21.7ms)  INSERT INTO `tbl_multiple_break` (`id`,`name`,`company_id`) VALUES (103,'test 101',1)    
(0.8ms)  INSERT INTO `tbl_multiple_break` (`id`,`name`,`company_id`) VALUES (101,'test',2)
`

**Comment by jkowens** [comment]
Yeah, exactly as I suspected. I'm guessing your multiple db setup is the reason for the issue.  It doesn't seem like the overwritten `establish_connection` is being called for MariaDB.

https://github.com/zdennis/activerecord-import/blob/74ea5b1f2f6a9c1e958bff1e29eb46de32860735/lib/activerecord-import/import.rb#L251

You could try manually requiring the activerecord-import adapter for MySQL:

```
require 'activerecord-import/active_record/adapters/mysql2_adapter'
```

**Comment by iFaujack** [comment]
thank you for your help. 
i tried to manually requiring this 
`require 'activerecord-import/active_record/adapters/mysql2_adapter'` 

upsert process works well for my secondary DB (MySQL),

**Comment by jkowens** [comment]
Great glad to hear that. Hopefully at some point someone is able to figure out how to load that automatically with multi db support 😄
