### ISSUE TITLE
Handle conflict targets differently

### ISSUE THREAD

**Issue by mnort9** [zdennis/activerecord-import#770]
Is it possible to set different conflict options depending on which unique index was violated? 

For example, if `field_a` is violated then ignore, but if `field_b` is violated then update columns

**Comment by jkowens** [comment]
I'm not aware of a way to make that work. We basically turn parameters into a SQL statement to execute against the database, so the underlying database would have to support a way of doing that. For instance, I don't think Postgres allows multiple conflict targets with different updates to be specified.

**Comment by jkowens** [comment]
Closing for now.
