### ISSUE TITLE
QUESTION: Difference between ActiveRecord-Import & upsert_all in Rails 7?

### ISSUE THREAD

**Issue by OskarEichler** [zdennis/activerecord-import#772]
Hey guys,
Great work on this gem! We've been using it for the past few years and recently upgraded to Rails 7. With Rails 7 comes quite a few [new config options](https://blog.kiprosh.com/rails-7-adds-new-options-to-upsert_all/) for upsert_all, and I wanted to know what exactly the differences are now that still exist between ActiveRecord-Import and upsert_all?

**Comment by jkowens** [comment]
I definitely recommend switching to the Rails default upsert_all. I don't have a list of all the differences but I think a couple things may be the "recursive" import option for Postgres users and also the ability to import models that can be validated before import.

**Comment by OskarEichler** [comment]
Did a bit more research on upsert_all, and definitely see a couple of downsides that I would like to clarify here:

- There still is no synchronize method in core Rails that I'm aware of?
- The returned results from upsert_all are not Models but just an array of hashes.
- There is no good way of doing run_callbacks since the the returned results is not an array of models.

Kind of thinking to just stick with ActiveRecord-Import since it feels much more refined, but maybe more people can chip in here to get a better sense of the pro's and con's.

**Comment by jkowens** [comment]
Looks like @OskarEichler outlined some of the differences, going to close this issue.
