### ISSUE TITLE
Allow import of ignored columns - Suggested Feature

### ISSUE THREAD

**Issue by kgilje** [zdennis/activerecord-import#795]
I don't know how common this would be for others, but I have models where I obfuscate personal information like username columns from the website interface.  To do this I use the ignore_columns function in the model.  However, inside the import with no validation, the columns are restricted to what you get by model_name.class_hash.  I wrote a work around that reproduced portions of that import code that compared columns instead to ActiveRecord::Base.connection.schema_cache.columns_hash(model_name.table_name) which picks up the the ignored columns and all their attributes in addition to the "normal" columns. 

Where my import breaks with the current code using ignored columns in the input csv.
https://github.com/zdennis/activerecord-import/blob/748309d1ae03fc1fe56d58e54c634a003408c706/lib/activerecord-import/import.rb#L795

Not sure of the complication level of a change like this, but it could be useful to others.

**Comment by jkowens** [comment]
Resolved by #799
