### ISSUE TITLE
Empty ON CONFLICT targets

### ISSUE THREAD

**Issue by zernie** [zdennis/activerecord-import#796]
Postgres allows to provide empty `ON CONFLICT` targets which works on all uniq constraints, but `activerecord-import` always tries to insert the `(id)` target

**Comment by jkowens** [comment]
>conflict_target
Specifies which conflicts ON CONFLICT takes the alternative action on by choosing arbiter indexes. Either performs unique index inference, or names a constraint explicitly. For ON CONFLICT DO NOTHING, it is optional to specify a conflict_target; when omitted, conflicts with all usable constraints (and unique indexes) are handled. For ON CONFLICT DO UPDATE, a conflict_target must be provided.

The PG documentation indicates that a conflict target must be provided for ON CONFLICT DO UPDATE. 

The `conflict_target` or `constraint_name` can be specified as show in this example:

```
Book.import [book], on_duplicate_key_update: {conflict_target: [:id], columns: [:title]}
```
