### ISSUE TITLE
Question about performance: What are the order of things?

### ISSUE THREAD

**Issue by james-em** [zdennis/activerecord-import#797]
Hi,

I'm using this gem to perform bulk importation in Postgres and I am having high RAM usage and my production server mostly gets unresponsive.

Here is an equivalent example of what I am currently doing. Truth is in reality i'm initializing my records array from a foreign MySQL database to import it in a new Postgres database. Some tables have 1 900 000 rows of data.

```
records = 500000.times.map { |i| MyModel.new(id: i, name: i.to_s) }
MyModel.import! records, validate: false, on_duplicate_key_update: :all, batch_size: 100 # Import to Postgres DB
```

**Question**

Generating the 500K array is very fast. I have no complaint. Once I call the `import!` method, now it can take a very long while. It's very long even before the first batch is persisted and it's long very long when it's appears to be done at like 100%.

So my question is, what is actually happening precisely under the hood in my scenario? Does it generate the 500K SQL queries prior executing the batches or it actually generate the first batch SQL, execute it, then proceed to generate the second batch SQL, execute it and so on? Or is it perhaps because it keeps everything in one single transaction?

Could performance be improved by editing maybe the order of the process?

**Comment by jkowens** [comment]
Yeah, the built in batch_size option is not efficient. You already have all 500K records in memory at that point. It then tries to slice it down to batches. I recommend managing batching yourself so a smaller number of models are initialized. I would batch inserts into at least 1K, if not more.

**Comment by james-em** [comment]
> Yeah, the built in batch_size option is not efficient. You already have all 500K records in memory at that point. It then tries to slice it down to batches. I recommend managing batching yourself so a smaller number of models are initialized. I would batch inserts into at least 1K, if not more.

Thanks for the quick reply! It's indeed a valid suggestion!

Just wondering as curiosity, when you say "batch_size" option is not efficient, would you say that doing

```
records = 500000.times.map { |i| MyModel.new(id: i, name: i.to_s) }

# Doing this
records.each_slice(1000).to_a.each do |slice|
  MyModel.import! slice, validate: false, on_duplicate_key_update: :all # Import to Postgres DB
end

# Is more efficient than doing
MyModel.import! records, validate: false, on_duplicate_key_update: :all, batch_size: 1000 # Import to Postgres DB
```

Would the slice way be more efficient than simply passing everything at once with the batch_size option? In this case both 500K records are pre-initialized

**Comment by jkowens** [comment]
Yeah that's true, if you have to load all the records at once while importing, that's probably not going to help. I was thinking if you were incrementally reading them from another source.

**Comment by james-em** [comment]
> Yeah that's true, if you have to load all the records at once while importing, that's probably not going to help. I was thinking if you were incrementally reading them from another source.

I don't have to, but if I did, would each_slice(1000) be exactly the same as doing batch_size: 1000 or the gem builds all the SQL queries for all batches at once first in RAM before executing the batches?

**Comment by jkowens** [comment]
I would expect it to perform about the same doing `each_slice(1000)` as providing `batch_size: 1000`. It would be interesting to see some benchmarks tho.
