### ISSUE TITLE
Support `trilogy` adapter

### ISSUE THREAD

**Issue by tmimura39** [zdennis/activerecord-import#815]
A new MySQL adapter (trilogy) has been introduced to rails. https://github.com/rails/rails/pull/47880

activerecord-import should also support trilogy.

> Trilogy is a client library for MySQL-compatible database servers, designed for performance, flexibility, and ease of embedding.

* https://github.com/trilogy-libraries/trilogy
* https://github.com/trilogy-libraries/activerecord-trilogy-adapter

I have verified that the application works correctly with the following code.
```ruby
require "active_record/connection_adapters/trilogy_adapter"
require "activerecord-import/adapters/mysql2_adapter"

class ActiveRecord::ConnectionAdapters::TrilogyAdapter
  include ActiveRecord::Import::Mysql2Adapter
end
```

**Comment by jkowens** [comment]
Any input on PR #811?

**Comment by tmimura39** [comment]
Oops, I missed that pull request.

thanks 👍

**Comment by zmariscal** [comment]
I'm currently trying to figure out how to properly test this change. The changes I have currently on my PR work as is with a rather large Rails application. 

When running he mysql test in a Docker container I see the following:
```
201 runs, 289 assertions, 1 failures, 56 errors, 0 skips
rake aborted!
```

I still need to investigate why the CI is ❌, but I'll try to identify the issue and report back.

**Comment by zmariscal** [comment]
I almost have a 🟢 test running. I discovered a small issue with the Trilogy adapter. Opening a PR against the project to see if I can get that merged. 🤞🏼 I can, after that I can hopefully merge this PR.

**Comment by zmariscal** [comment]
I have opened a PR around add trilogy support [here](https://github.com/zdennis/activerecord-import/pull/825)

**Comment by zmariscal-ut** [comment]
@jkowens with my PR merged now can we close this issue?

**Comment by zmariscal** [comment]
@jkowens with my PR merged now can we close this issue?

**Comment by jkowens** [comment]
Yep 👍
