### ISSUE TITLE
Cutting a new version of the gem

### ISSUE THREAD

**Issue by zmariscal** [zdennis/activerecord-import#829]
# Purpose
It looks like the last release was this [one](https://github.com/zdennis/activerecord-import/releases/tag/v1.5.1) and there's been a [number of commits](https://github.com/zdennis/activerecord-import/commits/master) since the last release. 

Specifically it'd be great to not have to point to the branch `master` to get the Trilogy adapter change.

**Comment by dorner** [comment]
Still waiting - this would be great!

**Comment by jkowens** [comment]
Just released v1.6.0 🚀

**Comment by jkowens** [comment]
@zmariscal hey so I see jruby tests started failing. It seems like it must be related to a newer version of jruby or activerecord-jdbc-adapter being released. Any chance you could take a look?

**Comment by zmariscal** [comment]
@jkowens sure! Here's a PR that fixes that. Sorry for the trouble.
