### ISSUE TITLE
recursive_on_duplicate_key_update doesn't work with non-standard association name

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [zdennis/activerecord-import#843]
If I have a class structure like this:

```ruby
class Foo < ActiveRecord::Base
  has_many :items, class_name: "FooItem"
end

class FooItem < ActiveRecord::Base
end
```

And try to import using `recursive_on_duplicate_key_update`, like this:

```ruby
Foo.import(records,
  on_duplicate_key_update: {columns: :all},
  recursive_on_duplicate_key_update: {items: {columns: :all}})
```

Then activerecord-import won't do an upsert for the association, only for the main records.

The issue is that `options[:recursive_on_duplicate_key_update][table_name]` returns `nil` here:

https://github.com/zdennis/activerecord-import/blob/fca8b823ae695b03714837cc6603f51525c60505/lib/activerecord-import/import.rb#L865

The code is looking for a key matching the table name of the association instead of the name of the association itself. The documentation says: "The hash key is the association name".

**Comment by jkowens** [comment]
Hi @jacob-carlborg-apoex , thanks for reporting this issue. I assume if you do the following it will work?

```
Foo.import(records,
  on_duplicate_key_update: {columns: :all},
  recursive_on_duplicate_key_update: {foo_items: {columns: :all}})
  ```
  If you are able to provide a PR to correct this issue that would be appreciated!

**Comment by jacob-carlborg-apoex** [comment]
Yes, with `foo_items` it works.

> If you are able to provide a PR to correct this issue that would be appreciated!

What's the policy on breaking changes? Changing this would be a breaking change. Should the code try to look for both names or should this be a breaking change?

**Comment by jkowens** [comment]
Good point, we can go ahead and make a breaking change. We can release in in v2.0 since we loosely follow semver 😅
