### ISSUE TITLE
inserted id

### ISSUE THREAD

**Issue by diogomaximo** [zdennis/activerecord-import#94]
How can i get the inserted ids of my array object?
Can i do something like that:
ids = Entry.import entries

**Comment by gudata** [comment]
Any solution on this?

**Comment by jkowens** [comment]
@diogomaximo if using Postgres and activerecord-import 0.8.0+ you can do

```
result = Entry.import entries
ids = result.ids
```

Issue #230 would provide the same functionality to MySQL and SQLite once implemented.
